/* All user-facing copy in three languages — ported verbatim from rumampu22.html. */

export type Lang = 'en' | 'ms' | 'zh';

export type StringTable = { langname: string; months: string[] } & Record<string, string | string[]>;

export const STRINGS: Record<Lang, StringTable> = {
en: {
  langname: 'English',
  months: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
  tab_home: 'Home',
  tab_money: 'Money',
  tab_test: 'House',
  tab_prepare: 'Prepare',
  back: 'Back',
  add: 'Add',
  edit: 'Edit',
  done: 'Done',
  cancel: 'Cancel',
  keep: 'Keep',
  remove: 'Remove',
  saved: 'Saved',
  unknown: 'Unknown',
  lang_pick: 'Language',
  prov_user: 'your data',
  prov_official: 'official',
  prov_calc: 'calculated',
  prov_assume: 'assumption',
  provf_user: 'User Data: a figure you entered yourself.',
  provf_official: 'Official Source: a published figure; source and date shown.',
  provf_calc: 'Derived Calculation: arithmetic on your own records. Nothing else added.',
  provf_assume: 'Stress-Test Assumption: an editable default, not a fact about you.',
  ob1: 'RuMampu checks how a home payment fits your quieter months, not just your average ones.',
  ob2: 'It lays the numbers out clearly. The decision is always yours.',
  ob3: 'Begin with whatever you have. Even one week of income is a good start.',
  ob_skip: 'Skip',
  ob_next: 'Next',
  ob_start: 'Start',
  ob_slogan: 'Let your real months do the counting.',
  pl_sec: 'This month’s plan',
  sp_add_t: 'A second pot',
  sp_add_b: 'A second pot lets you put money aside just for your cash buffer, and Upfront cash would count it separately. How pots move money is still with the team, so this is a preview.',
  sp_pots: 'Savings pots',
  rx_custom: 'Custom',
  rx_try_go: 'Test it',
  sp_pot: 'Savings pot',
  sp_pot1: 'Main pot',
  sp_pot1h: 'Holds your saving plan and cash buffer',
  sp_addpot: 'Add a pot for your buffer',
  sp_pot_soon: 'Pot mechanics are with the team. Preview only.',
  uf_pot: 'Savings pot',
  uf_withpot: 'You have plus the pot: {z} of {n}.',
  mo_savings: 'Savings',
  sv_name_t: 'Name this test',
  sv_name_l: 'Name',
  sv_edit_t: 'Saved test',
  sv_pay_l: 'Monthly cost tested (RM)',
  sv_open_l: 'Open this result',
  sv_edit_l: 'Edit this test',
  sv_del: 'Delete this test',
  sv_del2: 'Tap again to delete',
  fg_tag: 'Get back into your account.',
  cm_tag: 'A reset link is on its way.',
  hh_test: 'Test a house',
  sv_chip: 'Saved',
  hh_test_d: 'Check a home against your recorded months.',
  hh_prep: 'Prepare for a house',
  hh_prep_d: 'Upfront cash, cash buffer, documents.',
  sv_title: 'Saved tests',
  sv_none: 'No test kept yet. Run a test and save it for this session to find it here.',
  sv_kept_where: 'Saved for this session in House › Saved tests.',
  au_made: 'Your account has been created. Log in to continue.',
  fg_title: 'Forgot password',
  fg_hint: 'Enter your email and we will send you a reset link.',
  fg_send: 'Send reset link',
  cm_title: 'Check your email',
  cm_body: 'A reset link is on its way to {e}. Open it to set a new password.',
  cm_resend: 'Resend link',
  cm_back: 'Back to log in',
  mh_title: 'How we use your email',
  mh_body: 'Only to sign you in and to reset your password. Never for marketing, never shared, never sold.',
  pf_acct: 'Account',
  pf_acct_g: 'Guest · linked to this browser/device',
  pf_pw: 'Password',
  pf_prev: 'Preview only in this prototype.',
  inc_q_day: 'How much did you earn today?',
  inc_q_week: 'How much did you earn this week?',
  inc_q_month: 'How much did you earn this month?',
  ex_q_day: 'How much did you spend today?',
  ex_q_week: 'How much did you spend this week?',
  ex_q_month: 'How much did you spend this month?',
  inc_weekany: 'Pick any day in that week.',
  mo_quiet_ask: 'If RuMampu knows your quiet months, your house tests are more accurate.',
  wholemonth: 'Whole month',
  mo_view_t: 'Tiles',
  mo_view_l: 'List',
  rg_tile_d: 'The span of payments your recorded months could carry.',
  cp_tile: 'Compare payments',
  cp_tile_d: 'Try several amounts against the same months.',
  pf_months: 'Months recorded',
  pf_houses: 'Houses built',
  pf_days: 'Days saved',
  pf_prep_h: 'Get ready for the purchase',
  pf_togo: '{v} to go',
  pf_ready2: 'Covered',
  pf_buffer_h: 'For quiet months',
  pf_docs_h: 'Checklist',
  pf_after_h: 'After buying',
  pf_about: 'About RuMampu',
  pf_credit: 'Ruma, our mascot, is AI-assisted. Every figure in the app comes from your own record.',
  pf_version: 'Prototype v19 · EN · BM · 中文',
  tx_intro_t: 'Let’s test a house',
  tx_intro: 'Tell me the price. I’ll check it against your {n} recorded months and show you which ones would have run short.',
  tx_ctx: 'Your quietest month leaves {lo} · a usual month {hi}',
  tx_house: 'The house',
  tx_price: 'Property price',
  tx_dep: 'Deposit',
  tx_dep_other: 'Other',
  tx_inst: 'Monthly instalment',
  tx_loan: '{r}% over {y} years',
  tx_other: 'Other monthly costs',
  tx_total: 'Total monthly cost',
  tx_run: 'Run the test',
  tx_known: 'I already know my monthly payment',
  tx_known_lbl: 'Monthly payment (RM)',
  tx_back_price: 'Work it out from the price instead',
  tx_loan_t: 'Loan details',
  tx_costs_t: 'Other monthly costs',
  tx_costs_h: 'Maintenance, insurance and the like. Estimates are fine, you can change them any time.',
  rx_ok_t: 'All {n} months would carry it',
  rx_ok: 'This home’s {c} a month fits inside every recorded month.',
  rx_warn_t: '{s} of {n} months would run short',
  rx_warn: 'In {months}, {c} a month would have left you short. Largest gap {g}.',
  rx_bad: 'Most of your recorded months could not carry {c} a month. Largest gap {g}.',
  rx_leg_bar: 'Money left each month after work costs and commitments',
  rx_leg_line: 'This home’s monthly cost',
  rx_leg_gap: 'Shortfall',
  rx_try_t: 'House monthly cost · What would work',
  rx_try: 'Your recorded months could have carried about {p} a month.',
  rx_try_ok: 'This home’s cost sits inside the payment every recorded month could carry.',
  rx_try_btn: 'Try {p}',
  rx_trying: 'Testing {p} instead of this home’s {c}.',
  rx_use_home: 'Back to this home',
  rx_drop: 'If income drops',
  rx_keep: 'Save test',
  rx_change: 'Edit house',
  rx_how: 'How this was worked out',
  sp_title: 'What are you scanning?',
  sp_in_h: 'Earnings page or payout screenshot',
  sp_out_h: 'A receipt or bill',
  cvr_ok_t: 'Your record covers your quiet months',
  cvr_ok: '{slow} are inside {a} to {b}, so the house test already counts them.',
  cvr_gap_t: 'Your record has not seen {m} yet',
  cvr_gap: 'You said {m} is usually slower, but your record only runs {a} to {b}. Until then the test may look better than a real slow month.',
  cvr_gap_do: 'Keep recording through {m}. The test will pick those months up on its own.',
  cvr_flat_t: 'Every month counts the same',
  cvr_info_t: 'What this means for the test',
  cvr_pick_hint: 'Pick every month that is usually slower.',
  ex_limit_of: '{v} of your {l} monthly limit',
  ex_edit_limit: 'Edit limit',
  ex_set_limit: 'Set a monthly limit',
  ex_limit_title: 'Monthly spending limit',
  ex_limit_hint: 'What you want to keep daily spending under each month. Nothing is blocked, the bar just shows how far along you are.',
  ex_limit_saved: 'Monthly limit updated.',
  ex_q_amt: 'How much did you spend?',
  ex_q_cat: 'What was it for?',
  ex_recent: 'Recent expenses',
  ex_oflimit: '{v} of {l} limit',
  xe_title: 'Edit expense',
  xe_del: 'Delete expense',
  xe_save: 'Save changes',
  xe_saved: 'Expense updated.',
  xe_deleted: 'Expense removed.',
  exc_hint: 'Export a .csv from your bank or e-wallet, then choose it here.',
  exc_cat: 'Category for these rows',
  exc_done: '{n} expenses added, {a} to {b}.',
  io_in: 'In',
  io_out: 'Out',
  ht_title: 'House test',
  ht_rec: '{n} months recorded · {a} to {b}',
  ht_short: '{s} of {n} months would run short',
  ht_ok: 'All {n} months would carry it',
  ht_gap: 'Largest gap {g}',
  ht_go: 'Test',
  ht_rego: 'Re-test',
  ht_open: 'Open test',
  mo_sofar: '{m} so far',
  mo_in: 'In',
  mo_out: 'Out',
  mo_left: 'Left',
  mo_fixed: 'Income and daily spending recorded this month.',
  mo_quiet: 'Your quiet months',
  mo_quietest: 'Quietest',
  mo_usual: 'Usual',
  mo_quiet_note: 'Remaining balance after work costs and commitments. The house test counts on the quiet ones.',
  mo_trend: 'Income after work costs, last {n} months',
  mo_permo: '/ month',
  mo_pace: 'Spending pace',
  mo_pace_note: '{v} of {l} limit · day {d} of {n}',
  mo_nolimit: 'No limit set',
  mo_rec: 'Record',
  mo_setup: 'Set up',
  mo_insights: 'Insights',
  perx_day: 'Per day',
  perx_week: 'Per week',
  perx_month: 'Per month',
  inc_for: 'This amount is for',
  inc_weekend: 'Week ending',
  inc_monthof: 'Which month?',
  ie_title: 'Edit entry',
  ie_save: 'Save changes',
  ie_saved: 'Entry updated.',
  ie_deleted: 'Entry removed.',
  ie_del: 'Delete entry',
  im_type: 'Manual',
  im_scan: 'Scan',
  im_csv: 'Import',
  sc_hint: 'Works with Grab, foodpanda and Lalamove earnings pages.',
  sc_pick: 'Take a photo or choose a screenshot',
  sc_sample: 'Try a sample',
  sc_reading: 'Reading your earnings…',
  sc_found: '{n} entries found. Untick any you do not want.',
  sc_low: 'Low confidence, please check',
  sc_add: 'Add {n} entries',
  sc_added: '{n} entries added from your scan.',
  sc_tag: 'scanned',
  cv_hint: 'Export a .csv from your platform or bank, then choose it here.',
  cvi_pick: 'Choose a .csv file',
  cv_tpl: 'Download template',
  cv_sample: 'Try a sample file',
  cv_map: 'Check the columns',
  cv_date: 'Date',
  cv_amt: 'Amount',
  cv_desc: 'Description',
  cv_src: 'Source for these rows',
  cv_fromdesc: 'From description',
  cv_import: 'Import {n} rows',
  cv_done: '{n} entries added, {a} to {b}.',
  cv_skipped: '{n} duplicates skipped.',
  cv_none: 'No usable rows found. Check the date and amount columns.',
  cv_tag: 'CSV',
  inc_q_amt: 'How much did you earn?',
  inc_q_when: 'When?',
  inc_q_src: 'From where?',
  inc_today: 'Today',
  inc_yday: 'Yesterday',
  inc_pick: 'Pick a date',
  inc_recent: 'Recent entries',
  inc_sofar: '{m} so far: {v}',
  hm_togo: '{g} short of your upfront cash estimate',
  hm_ready: 'Your upfront cash estimate is covered',
  hd_morning: 'Good morning',
  hd_afternoon: 'Good afternoon',
  hd_evening: 'Good evening',
  hd_welcome: 'Welcome!',
  hd_guest: 'Welcome, guest',
  ai_title: 'Ask RuMampu',
  ai_hi: 'Hi! Ask me about your record, your saving plan, or a house you have in mind. I only answer from your own numbers.',
  ai_q1: 'Can I afford a RM 250k home?',
  ai_q2: 'How is my saving plan going?',
  ai_q3: 'What did I spend most on?',
  ai_ph: 'Type a question',
  ai_send: 'Send',
  ai_a_afford: 'Your quieter months carry about {m} a month after work costs and commitments. Run the house test for the full answer.',
  ai_a_plan: 'You have saved {s} of {t} this month, {d} of {n} days done. Today’s amount is {a}.',
  ai_a_spend: 'In {mo} you spent most on {c}: {v}.',
  ai_a_default: 'I answer only from your own record, nothing invented. Try one of the questions below.',
  vl_score: 'Score',
  vl_bestscore: 'Best',
  vl_moves: 'Moves',
  vl_short: 'Swipe to grow your village.',
  vl_how: 'How to play',
  vl_s1: 'Every day you save adds a Pondok to the plot.',
  vl_s2: 'Swipe left, right, up or down: all the houses slide that way.',
  vl_s3: 'Two houses of the same kind that meet merge into the next size.',
  vl_s4: 'Keep going: Pondok, Kampung house, Terrace, Condo, then Istana.',
  vl_s5: 'Sixteen saved days is enough for one Istana.',
  vl_start: 'Let’s start!',
  vl_sub: 'A mini 2048 game: swipe to slide the houses; two alike merge into a bigger one.',
  vl_play: 'Play',
  vl_done: 'Done',
  vl_daily: 'Daily plan',
  vl_title: 'Saving village',
  vl_houses: '{n} houses',
  vl_builtn: '{b} built',
  vl_onplot: '{n} on the plot',
  vl_best: 'Best: {t}',
  vl_hint: 'Every saved day adds a Pondok. Slide two alike together to build bigger.',
  vl_built: 'You built a {t}!',
  vl_t1: 'Pondok',
  vl_t2: 'Kampung house',
  vl_t3: 'Terrace',
  vl_t4: 'Condo',
  vl_t5: 'Istana',
  pl_title: 'Saving plan',
  pl_target: 'Monthly target',
  pl_today: 'Today',
  pl_save_today: 'Save today',
  pl_saved_today: 'Saved ✓',
  pl_progress: '{s} of {t} saved',
  pl_days: '{d} of {n} days',
  pl_hint: 'A small, different amount each day. Together they reach your target by month end.',
  pl_shuffle: 'Shuffle the days left',
  pl_reached: 'Target reached!',
  pl_note: 'Tap a day to mark it saved. Each saved day is added to your Total balance. Changing the target re-splits only the days you have not saved yet.',
  pl_toast: 'Saved {a} today. Total balance is now {c}.',
  pl_untoast: 'Removed {a} from today.',
  k_hi: 'Hi there!',
  k_intro: 'Before you start, we have just a few questions',
  k_begin: 'Begin',
  k_next: 'Next',
  k_j_taxi: 'E-hailing',
  k_j_bar: 'Bartender',
  k_own: 'Add your own',
  k_own_h: 'Name of your work',
  hm_saving: 'Total balance',
  hm_mysav: 'My balance',
  hm_income: 'Income',
  hm_exp: 'Expenses',
  tab_profile: 'Profile',
  pf_title: 'Profile',
  pf_guest_t: 'Guest mode',
  pf_guest: 'Your record may remain available on this browser/device. No RuMampu account is created.',
  pf_create: 'Create an account',
  pf_signed_t: 'Signed in',
  pf_signed: 'Your record is kept for next time.',
  pf_lang: 'Language',
  pf_export: 'Export my record',
  pf_export_done: 'Record export is ready.',
  pf_export_failed: 'Record export failed. Please try again.',
  pf_delete: 'Delete account and record',
  pf_delete_guest: 'Delete guest record',
  pf_delete2: 'Tap again to delete',
  pf_delete_confirm: 'Tap delete again to permanently remove this account and record.',
  pf_delete_guest_confirm: 'Tap delete again to permanently remove this guest record.',
  pf_delete_done: 'Record deleted.',
  pf_delete_failed: 'Record could not be deleted. Please try again.',
  pf_prepare: 'Prepare for a house',
  qk_title: 'What would you like to add?',
  qk_income: 'Income',
  qk_expense: 'Expense',
  qk_scan: 'Scan a receipt',
  k_title: 'Getting to know you',
  k_skip: 'Skip',
  k_q1: 'What do you do?',
  k_q1h: 'Pick all that apply. These become your income sources.',
  k_q2: 'How much did you earn last month?',
  k_q2h: 'One rough figure is enough to start. Optional.',
  k_ph: 'e.g. 3,000',
  k_go: 'Start using RuMampu',
  k_j_ehail: 'E-hailing',
  k_j_deliv: 'Food delivery',
  k_j_free: 'Freelancer',
  k_j_part: 'Part-time',
  k_j_stall: 'Small business',
  k_j_other: 'Other',
  k_saved: 'Your record has started. Everything is editable.',
  wf_step: 'Step {n} of 3',
  wf_langq: 'Which language feels like home?',
  wf_next: 'Next',
  wf_hi: 'Hi, I’m Ruma!',
  wf_blend: '<b>RuMampu</b> blends <i>rumah</i> and <i>mampu</i>: can I afford a home?',
  wf_f1t: 'Your real record',
  wf_f1d: 'Log your income and spending',
  wf_f2t: 'The house test',
  wf_f2d: 'I check a home you want against what you record',
  wf_f3t: 'Private by design',
  wf_f3d: 'Your numbers stay yours, nothing invented',
  wf_copy: '© 2026 RuMampu by Cendol Compiler · Made in Malaysia for people with irregular income · SDG 11',
  wf_meet: 'Nice to meet you →',
  au_hello: 'Hello!',
  au_create: 'Create an account',
  au_ctag: 'Keep your record for next time.',
  au_login: 'Log in',
  au_email: 'Email',
  au_pw: 'Password',
  au_show: 'Show',
  au_hide: 'Hide',
  au_eph: 'name@example.com',
  au_pph: 'Your password',
  au_p8: 'At least 8 characters',
  au_cpw: 'Confirm password',
  au_again: 'Type it again',
  au_mix: 'Use a mix of letters and numbers.',
  au_mailhow: 'How we use your email',
  au_forgot: 'Forgot password?',
  au_or: 'or continue with',
  au_google: 'Continue with Google',
  au_new: 'New here?',
  au_createbtn: 'Create an account',
  au_createacct: 'Create account',
  au_guest: 'Continue as guest',
  au_guest2: 'Continue as guest instead',
  au_guestnote: 'Your record may remain available on this browser/device. No RuMampu account is created.',
  au_mailonly: 'We use your email only to sign you in and to reset your password.',
  au_have: 'Already have an account?',
  au_mailhow_t: 'We use your email only to sign you in and to send a reset link. Nothing else.',
  au_forgot_t: 'Password reset flow (design stub).',
  au_backlogin: '← Back to log in',
  home_rec: 'You have {n} months of income recorded.',
  home_rec_thin: '{n} months is a thin record. Every entry you add lets the test see more.',
  home_test: 'Test a house',
  home_retest: 'Re-test the house',
  headline: '{s} of your {n} recorded months would have run short.',
  headline_zero: 'None of your {n} recorded months would have run short.',
  gap_lbl: 'Largest gap',
  covspan: '{a} to {b} recorded',
  cov_unchecked: 'Quiet months not set yet',
  cov_missed: 'Your records haven’t seen {m} yet. You said it is usually slower.',
  money_income: 'Income',
  money_workcosts: 'Work costs',
  money_commit: 'Commitments',
  money_pattern: 'Income pattern',
  money_coverage: 'Quiet months',
  net_lbl: 'Income after work costs',
  per_month: '/ month, average',
  inc_empty: 'Add last week’s earnings. That’s enough to start.',
  inc_amount: 'Amount (RM)',
  inc_date: 'Date',
  inc_source: 'Source',
  inc_add: 'Add income',
  inc_neg: 'An amount below zero can’t be saved.',
  inc_outlier: 'Well above your usual entries. Keep it?',
  src_ehail: 'E-hailing',
  src_freelance: 'Freelance',
  src_parttime: 'Part-time (fixed)',
  src_own: '+ Your own source',
  src_name: 'Source name',
  entry_saved: 'Entry saved',
  wc_petrol: 'Petrol',
  wc_service: 'Servicing',
  wc_platform: 'Platform fees',
  wc_data: 'Phone data',
  wc_roadtax: 'Road tax & insurance',
  wc_own: '+ Your own cost',
  wc_note: 'Every later screen uses this number.',
  cm_living: 'Living costs',
  cm_debts: 'Debt repayments',
  cm_savings: 'Savings',
  cm_rent: 'Rent',
  cm_food: 'Food',
  cm_util: 'Utilities',
  cm_motor: 'Motor loan',
  cm_ptptn: 'PTPTN',
  cm_family: 'Family support',
  cm_save: 'Monthly savings',
  cm_total: 'Total commitments',
  pt_avg: 'Average',
  pt_med: 'Median',
  pt_high: 'Highest',
  pt_low: 'Lowest',
  pt_range: 'plus or minus RM {x}, month by month',
  pt_quietx: 'Your quietest recorded month is {m}: {v} after work costs.',
  pt_namex: 'You can name the months you usually earn less under {L}.',
  tx_price_ph: 'e.g. 250,000',
  tx_need_price: 'Enter the property price first. The price is yours to bring.',
  au_demo: 'DEMO',
  rx_tryres: '{s} of {n} months would run short at {p}.',
  rc_live_guest: 'Every screen updates as you add. Your record may remain available on this browser/device. No RuMampu account is created.',
  rc_live_acct: 'Every screen updates as you add. Signed in: your record is kept for next time.',
  pt_none: 'No recorded month fell below that line.',
  pt_some: 'Below that line: {m}.',
  cv_q: 'Are there times of year when you usually earn less?',
  cv_yes: 'Yes',
  cv_no: 'No',
  cv_notsure: 'Not sure',
  cv_pick: 'Tap the months that are usually slower.',
  cv_unseen: 'You said {slow} is usually slower. Your records cover {a} to {b}, so this test hasn’t seen a slow month yet.',
  cv_seen: 'You said {slow} is usually slower. Your records cover {a} to {b}, and a slow month is in there.',
  cv_narrow: 'Your recorded amounts sit unusually close together. Weaker months may be missing from the record.',
  cv_varied: 'Your recorded amounts differ month to month. The test still only knows {a} to {b}.',
  cv_note: 'More months only help if the right months are in there.',
  th_title: 'The house',
  th_price: 'Property price (RM)',
  th_fin: 'Financing amount',
  th_dep: 'Deposit (RM)',
  th_dep0: 'RM 0 is allowed. 100% financing exists.',
  th_rate: 'Rate (% / year)',
  th_ten: 'Tenure (years)',
  th_inst: 'Monthly instalment',
  th_known: 'I already know my monthly payment',
  th_knownamt: 'Monthly payment (RM)',
  th_next: 'Total monthly cost',
  tc_title: 'Total monthly cost',
  tc_point: 'The instalment is not the whole cost.',
  tc_inst: 'Instalment',
  tc_break: 'What’s inside',
  tc_run: 'Run the test',
  hc_maint: 'Maintenance & sinking fund',
  hc_insure: 'Home insurance',
  hc_assess: 'Assessment tax',
  hc_quit: 'Quit rent',
  hc_parking: 'Parking',
  hc_other: 'Other',
  pc_title: 'Before the house',
  pc_msg: 'In {m}, your quietest recorded month, income came in RM {x} below your everyday costs, before any home cost.',
  pc_msg2: 'A home payment on top would leave every month short, at any price. A quick look at income and costs first gives the test firmer ground.',
  pc_btn: 'Go to Money',
  rs_title: 'Result',
  rs_how: 'How this was worked out',
  rs_how_body: 'Each bar is one recorded month: income after work costs, minus commitments. The line is the total monthly home cost, RM {c}. A month runs short when its bar ends below the line.',
  rs_limit_slow: 'This test hasn’t seen {m}, which you said is usually slower. The count below doesn’t include that quieter time of year yet.',
  rs_limit_thin: 'Only {n} months recorded. Not enough for this count to carry weight yet.',
  rs_range: 'Carrying range',
  rs_compare: 'Compare payments',
  rs_shock: 'If income drops',
  rg_lead: 'Your recorded months carried payments of RM {a} to RM {b} a month.',
  rg_how: 'What the two ends mean',
  rg_how_body: 'RM {a}: every recorded month covered it. RM {b}: half of them did.',
  rg_price: 'At {r}% over {y} years, that is about RM {p} to RM {q} in price.',
  rg_pin: 'your test',
  rg_ind: 'Indicative only. Not a valuation, not an offer.',
  cp_note: 'Same recorded months, three payments.',
  cp_short: '{s} of {n} short',
  cp_gap: 'largest gap RM {g}',
  cp_pay: 'Payment {i} (RM)',
  sh_note: 'A hypothetical about your recorded months, not about what lies ahead.',
  sh_custom: 'Custom',
  sh_pct: 'Drop (%)',
  sh_head: 'At −{p}%: {s} of {n} recorded months would have run short.',
  pr_upfront: 'Upfront cash',
  pr_buffer: 'Cash buffer',
  pr_docs: 'Documents & financing',
  pr_pv: 'Iteration 3 preview',
  pr_pv_note: 'After buying. Direction only, not shipping yet.',
  uf_have: 'You have',
  uf_need: 'You need',
  uf_gap: 'Gap',
  uf_dep: 'Deposit',
  uf_legal: 'Legal fees',
  uf_stampT: 'Stamp duty (transfer)',
  uf_stampL: 'Stamp duty (loan)',
  uf_val: 'Valuation',
  uf_disb: 'Disbursements',
  uf_move: 'Moving',
  uf_basic: 'Basics (fridge, bed, curtains)',
  uf_dep0: 'Deposit RM 0: upfront cash is fees and setting up, not the deposit.',
  bf_def: 'The smallest amount you’d have needed at the start to get through the short months in your record without going below zero.',
  bf_basis: 'From your own record, {a} to {b}. Not a general rule.',
  bf_zero: 'With this house, your recorded months never went below zero. The figure works out to RM 0.',
  bf_bal: 'Running balance by month',
  dc_bank: 'Bank statements, 6 months',
  dc_ehail: 'E-hailing earnings summary',
  dc_statdec: 'Statutory declaration of income',
  dc_epf: 'EPF statement',
  dc_commitlist: 'List of existing commitments',
  dc_sjkp: 'SJKP published criteria',
  dc_sj1: 'Malaysian citizen, age 18 to 70',
  dc_sj2: 'Gross income within SJKP’s published limit',
  dc_sj3: 'First home',
  dc_src: 'Source: sjkp.com.my, Aug 2026',
  dc_65: '65% check: needs review',
  dc_65_note: 'SJKP measures gross income; RuMampu measures income after work costs. Until that gap is settled, no pass or fail is shown here.',
  dc_plain: 'RuMampu does not apply for you and cannot tell you whether a bank will say yes.',
  pv_banner: 'Iteration 3 preview',
  pv_switch: 'Switch mode',
  pv_switch_btn: 'I’ve bought the home',
  pv_switch_note: 'Estimates become actuals. The purchase itself happens outside RuMampu.',
  pv_month: 'This month',
  pv_in: 'Actual income in',
  pv_out: 'Actual home costs out',
  pv_left: 'Cash left',
  pv_shortby: 'Short by',
  pv_then: 'Earlier test vs what happened',
  pv_then_a: 'Your earlier test: {s} short months out of {n} recorded.',
  pv_then_b: 'Since buying: {s2} of your first {n2} months have run short.',
  pv_then_why: 'The earlier record had no year-end month in it. Two arrived after buying.',
  see_pattern: 'Income pattern',
  see_coverage: 'Coverage check',
  money_record: 'Your record',
  rc_months: '{n} months recorded',
  rc_entries: '{e} entries, latest {d}',
  rc_tests: 'Kept tests',
  rc_none: 'No test kept yet. Run one from the Test tab.',
  rc_live: 'Your financial record may remain available on this browser/device. It is linked to an anonymous guest ID, not a RuMampu account.',
  rc_keep_line: 'Every new week you record gives the next test more of your real months.',
  rs_keep: 'Keep this test',
  rs_kept: 'Test kept',
  entry_saved_n: 'Entry saved. You now have {n} income entries.',
  inc_past: 'Add a past month',
  inc_past_hint: 'One total for that month is enough.',
  pt_bymonth: 'Month by month',
  pv_keep: 'Keep recording after buying. The same record keeps working.',
  money_expenses: 'Daily expenses',
  ex_sofar: '{m} so far',
  ex_days: '{d} days recorded',
  ex_add: 'Add expense',
  ex_scan: 'Scan a receipt',
  ex_preview: 'Preview',
  ex_bycat: 'By category',
  xc_meals: 'Meals',
  xc_groc: 'Groceries',
  xc_transp: 'Tolls & parking',
  xc_family: 'Family',
  xc_other: 'Other',
  xc_own: '+ Your own category',
  ex_saved: 'Saved. {m} so far: RM {x}.',
  ex_rule: 'A month counts as fully recorded from 20 logged days. RuMampu’s own rule.',
  ex_feeds: '{m} used your recorded expenses, RM {x}, in place of the food and family estimate.',
  ex_scan_pick: 'Take or choose a photo of the receipt.',
  ex_scan_sample: 'Use a sample receipt',
  ex_reading: 'Reading the receipt…',
  ex_check: 'Read from your receipt. Check it before saving.',
  ex_merchant: 'Shop',
  ex_total: 'Total (RM)',
  ex_retake: 'Retake',
  ex_fromr: 'from receipt',
  ex_cat: 'Category',
  ex_monthly: 'Monthly summary',
  ex_see_sum: 'See monthly summary',
  ex_set_lims: 'Set spending limits',
  ex_full: 'fully recorded',
  ex_used: 'used in the test',
  ex_partial: '{d} days, rest of month unknown',
  ex_limits: 'Spending limits',
  lm_note: 'The monthly limits are yours to set. RuMampu only counts.',
  lm_total: 'Whole month',
  lm_limit: 'Limit (RM)',
  lm_left: 'RM {x} left',
  lm_over: 'RM {x} past your limit',
  lm_none: 'no limit set',
  hb_spend: 'Spending · {m}',
  hb_income: 'Income · {m}',
  /* App-only keys (backend sync/error copy) kept from the previous build. */
  retry: 'Retry',
  home_rec_one: 'You have 1 month of income recorded.',
  home_rec_thin_one: '1 month is a thin record. Every entry you add lets the test see more.',
  inc_recorded: 'Recorded income',
  inc_sync_loading: 'Loading your saved income record…',
  inc_sync_error: 'The saved record could not be reached. Check the backend and try again.',
  inc_invalid_date: 'Use a valid date in YYYY-MM-DD format.',
  inc_invalid_amount: 'Enter a valid cash amount using numbers only, with up to 2 decimal places.',
  inc_save_failed: 'Income could not be saved. Please try again.',
  inc_saving: 'Saving…',
  wc_name: 'Work-cost name',
  xc_name: 'Category name',
  wc_add: 'Add work cost',
  wc_category: 'Work-cost category',
  wc_month: 'Month',
  wc_month_note: 'Showing {m}. Choose the current month or a month with records.',
  wc_income_formula: '{income} income − {costs} recorded work costs for this month.',
  wc_cost_total: '{costs} recorded work costs for this month.',
  wc_no_income: 'No income recorded for {m}. Add income before RuMampu can calculate this figure.',
  wc_month_unavailable: 'Choose the current month or a month that has income or work-cost records.',
  wc_entry_amount: 'Work-cost amount',
  wc_edit_amount: 'Edit work-cost amount',
  wc_so_far: 'Current month: recorded so far, not a forecast or a full-month total.',
  wc_no_costs: 'No work costs recorded for this month. This does not confirm that no costs occurred.',
  wc_summary_unavailable: 'The monthly result is unavailable until the latest records are loaded.',
  wc_recorded: 'Recorded work costs',
  wc_empty: 'No work-cost entries recorded yet.',
  wc_entry_invalid: 'Select a category and enter a valid amount and date.',
  wc_sync_loading: 'Loading your work costs…',
  wc_sync_error: 'Work costs could not be synced. Try again.',
  wc_save_failed: 'Work cost could not be saved. Please try again.',
  cm_sync_loading: 'Loading your commitments…',
  cm_sync_error: 'Commitments could not be synced. Try again.',
  cm_save_failed: 'Commitment could not be saved. Please try again.',
  pt_range_total: 'Recorded range',
  pt_std: 'Standard deviation',
  pt_month_count: '{n} recorded months',
  pt_loading: 'Calculating your income pattern from the saved record…',
  pt_error: 'The calculated income pattern could not be reached. Your saved income has not changed.',
  pt_api_required: 'Epic 2 analysis is available only in connected API mode. Set EXPO_PUBLIC_APP_MODE=api and start the backend.',
  pt_empty: 'Your income pattern starts with a recorded month.',
  pt_empty_note: 'Add income to see usable income month by month.',
  pt_add_income: 'Add income',
  pt_limited_one: 'This is one recorded month. It shows that month’s facts, but cannot yet describe a broader pattern.',
  pt_limited_two: 'This is two recorded months. The figures are factual, but the visible history is still limited.',
  pt_work_basis: 'Each recorded month uses only its own dated work-cost entries.',
  pt_rule: 'A lower-income month here means the lowest usable-income month in your current record. It is not a financial standard or a prediction.',
  cv_loading: 'Loading your saved coverage answer…',
  cv_error: 'Coverage could not be loaded or saved. You can retry without losing the last confirmed answer.',
  cv_check: 'Check coverage',
  cv_checking: 'Checking…',
  cv_select_required: 'Choose at least one slower month.',
  cv_save_failed: 'Coverage could not be saved. Please retry.',
  cv_represented: 'Represented in your recorded income: {m}.',
  cv_unrepresented: 'Not yet represented in your recorded income: {m}.',
  cv_observation: 'Across {n} recorded months, usable income ranges from {lo} to {hi}, a spread of {range}. These facts cannot confirm whether your usual slower periods are represented.',
  cv_api_required: 'Coverage checking is available only in connected API mode. Set EXPO_PUBLIC_APP_MODE=api and start the backend.',
  cv_no_history: 'There are no recorded income months to compare yet.',
  cv_previous: 'The result below is the last server-confirmed answer. Your new selection has not been saved.',
  tc_inst_desc: 'From your financing details',
  housing_running: 'Calculating…',
  housing_run_failed: 'The housing calculation could not be completed. Please try again.',
  housing_result_required: 'Run the housing test first so this screen can use the server-calculated result.',
  hc_maint_desc: 'For repairs and upkeep',
  hc_insure_desc: 'Basic home insurance',
  hc_assess_desc: 'Paid to local council',
  hc_quit_desc: 'Land rent (if applicable)',
  hc_parking_desc: 'Monthly parking cost',
  hc_other_desc: 'Any other recurring cost',
  rs_shortfall_breakdown: 'Where the shortfalls came from',
  rs_existing_shortfall: 'Already short before housing',
  rs_housing_shortfall: 'Became short because of this home',
  rs_shortfall_breakdown_note: 'Existing shortfalls were already below zero before the home cost was added. Housing-induced shortfalls are months that only became negative after this tested home cost was applied.',
  cp_price: 'RM {payment}/month ≈ RM {price} property value',
  cp_price_note: 'Indicative only, using the rate, tenure and deposit entered for this test.',
  sh_disclaimer: 'Hypothetical scenario, not prediction.',
  pr_coming: 'Coming soon',
  pr_coming_note: 'This section is under construction.',
  rc_months_one: '1 month recorded',
  rc_summary: 'Financial record',
  rc_month_metric: 'months recorded',
  rc_month_metric_one: 'month recorded',
  rc_entry_metric: 'financial entries',
  rc_latest_label: 'Latest entry',
  rc_latest: 'Latest recorded entry: {d}',
  rc_latest_empty: 'No dated income or expense entries yet.',
  rc_none_title: 'No test kept yet',
  rc_none_body: 'Run a housing test and keep the result here for this session.',
  rc_test_action: 'Go to Test',
  rc_about: 'About your record',
  rc_test_session: 'Kept for this session.',
  rc_pay_month: '{p} / month',
  rc_short_label: 'Short months',
  rc_short_value: '{s} of {n}',
  rs_keep_hint: 'Add this result to Your record for this session.',
  rs_kept_session: 'Kept for this session.',
  inc_past_no_min: 'Add whatever history you have. There is no 6 or 12 month minimum.',
  inc_past_month: 'Past month (YYYY-MM)',
  inc_past_invalid: 'Enter a valid month earlier than the current month.',
  inc_past_exists: 'That month already has income records. Choose another month.',
  inc_past_amount: 'Enter a total greater than zero.',
  inc_past_cash: 'Enter a valid cash amount using numbers only, with up to 2 decimal places.',
  inc_month_total: 'Monthly total',
  inc_import: 'Import income from CSV',
  imp_title: 'Import income',
  imp_intro: 'Choose a CSV file. RuMampu will prepare a preview before anything is added.',
  imp_format: 'Required columns: amount, date, source. Dates must be historical and use YYYY-MM-DD.',
  imp_select: 'Select CSV file',
  imp_reading: 'Reading file…',
  imp_summary: '{name}: {total} rows',
  imp_ready: '{n} ready',
  imp_attention: '{n} need attention',
  imp_row: 'Row {n}',
  imp_raw: 'Original: {amount} · {date} · {source}',
  imp_confirm: 'Confirm and add {n} records',
  imp_confirming: 'Adding records…',
  imp_confirmed: '{n} income records added. Your analyses now use them.',
  imp_failed: 'The income file could not be processed. Check the CSV and try again.',
  imp_view_pattern: 'View income pattern',
  imp_no_ready: 'No valid rows are ready to add.',
  pt_chart_accessibility: 'Month-by-month calculated usable income',
  pt_scroll: 'Scroll horizontally to see all recorded months.',
  ex_days_one: '1 day recorded',
  ex_empty: 'No daily expenses recorded yet.',
  ex_sync_loading: 'Loading your saved expenses…',
  ex_sync_error: 'Expenses could not be synced. Try again.',
  ex_saving: 'Saving…',
  ex_amount_positive: 'Enter an amount greater than zero.',
  ex_date_invalid: 'Enter a valid calendar date.',
  ex_save_failed: 'The expense could not be saved. Try again.',
  ex_take_photo: 'Take a photo',
  ex_choose_photo: 'Choose a photo',
  ex_image_failed: 'The receipt image could not be opened. Try again.',
  ex_scan_failed: 'The receipt could not be read right now. Try again, or add the expense manually.',
  ex_not_receipt: 'That photo doesn’t look like a receipt. Try a clearer photo of the receipt itself.',
  ex_ai_suggested: 'AI suggestion',
  ex_scan_partial: 'Some details couldn’t be read from the receipt. Fill in the empty fields before saving.',
  as_title: 'Ask RuMampu',
  as_hint: 'Ask about your money or a result…',
  as_send: 'Send',
  as_empty: 'Ask me about your income, spending, or your housing test result. I only use what you have recorded.',
  as_thinking: 'Thinking…',
  as_error: 'The assistant couldn’t reply just now. Try again.',
  as_limit: 'The assistant has reached today’s message limit. Try again tomorrow.',
  as_disclaimer: 'Explanations from your own record. Not financial advice.',
  ex_partial_one: '1 day, rest of month unknown',
},
ms: {
  langname: 'Bahasa Melayu',
  months: ['Jan','Feb','Mac','Apr','Mei','Jun','Jul','Ogo','Sep','Okt','Nov','Dis'],
  tab_home: 'Utama',
  tab_money: 'Wang',
  tab_test: 'Rumah',
  tab_prepare: 'Sedia',
  back: 'Kembali',
  add: 'Tambah',
  edit: 'Ubah',
  done: 'Selesai',
  cancel: 'Batal',
  keep: 'Kekalkan',
  remove: 'Buang',
  saved: 'Disimpan',
  unknown: 'Tidak diketahui',
  lang_pick: 'Bahasa',
  prov_user: 'data anda',
  prov_official: 'rasmi',
  prov_calc: 'dikira',
  prov_assume: 'andaian',
  provf_user: 'Data Pengguna: angka yang anda masukkan sendiri.',
  provf_official: 'Sumber Rasmi: angka diterbitkan; sumber dan tarikh dinyatakan.',
  provf_calc: 'Kiraan Terbitan: aritmetik ke atas rekod anda sendiri. Tiada tokok tambah.',
  provf_assume: 'Andaian Ujian Tekanan: nilai lalai boleh ubah, bukan fakta tentang anda.',
  ob1: 'RuMampu melihat bagaimana bayaran rumah muat dengan bulan yang lebih perlahan, bukan hanya purata anda.',
  ob2: 'Ia membentangkan angka dengan jelas. Keputusan sentiasa di tangan anda.',
  ob3: 'Mulakan dengan apa yang ada. Pendapatan seminggu pun sudah satu permulaan yang baik.',
  ob_skip: 'Langkau',
  ob_next: 'Seterusnya',
  ob_start: 'Mula',
  ob_slogan: 'Biar bulan sebenar anda yang mengira.',
  pl_sec: 'Pelan bulan ini',
  sp_add_t: 'Tabung kedua',
  sp_add_b: 'Tabung kedua membolehkan anda mengasingkan wang khas untuk penampan tunai, dan Wang pendahuluan akan mengiranya berasingan. Cara tabung memindahkan wang masih dengan pasukan, jadi ini pratonton.',
  sp_pots: 'Tabung simpanan',
  rx_custom: 'Sendiri',
  rx_try_go: 'Uji',
  sp_pot: 'Tabung simpanan',
  sp_pot1: 'Tabung utama',
  sp_pot1h: 'Menyimpan pelan simpanan dan penampan tunai anda',
  sp_addpot: 'Tambah tabung untuk penampan anda',
  sp_pot_soon: 'Mekanisme tabung masih dengan pasukan. Pratonton sahaja.',
  uf_pot: 'Tabung simpanan',
  uf_withpot: 'Anda ada campur tabung: {z} daripada {n}.',
  mo_savings: 'Simpanan',
  sv_name_t: 'Namakan ujian ini',
  sv_name_l: 'Nama',
  sv_edit_t: 'Ujian disimpan',
  sv_pay_l: 'Kos bulanan diuji (RM)',
  sv_open_l: 'Buka keputusan ini',
  sv_edit_l: 'Edit ujian ini',
  sv_del: 'Padam ujian ini',
  sv_del2: 'Ketik sekali lagi untuk padam',
  fg_tag: 'Kembali ke akaun anda.',
  cm_tag: 'Pautan set semula sedang dihantar.',
  hh_test: 'Uji rumah',
  sv_chip: 'Disimpan',
  hh_test_d: 'Semak rumah berdasarkan bulan yang direkodkan.',
  hh_prep: 'Bersedia untuk rumah',
  hh_prep_d: 'Wang pendahuluan, penampan tunai, dokumen.',
  sv_title: 'Ujian disimpan',
  sv_none: 'Belum ada ujian disimpan. Jalankan ujian dan simpan untuk sesi ini untuk melihatnya di sini.',
  sv_kept_where: 'Disimpan untuk sesi ini di Rumah › Ujian disimpan.',
  au_made: 'Akaun anda telah dibuat. Log masuk untuk teruskan.',
  fg_title: 'Lupa kata laluan',
  fg_hint: 'Masukkan emel anda dan kami akan hantar pautan set semula.',
  fg_send: 'Hantar pautan set semula',
  cm_title: 'Semak emel anda',
  cm_body: 'Pautan set semula sedang dihantar ke {e}. Buka untuk tetapkan kata laluan baharu.',
  cm_resend: 'Hantar semula pautan',
  cm_back: 'Kembali ke log masuk',
  mh_title: 'Bagaimana kami guna emel anda',
  mh_body: 'Hanya untuk log masuk dan set semula kata laluan. Bukan untuk pemasaran, tidak dikongsi, tidak dijual.',
  pf_acct: 'Akaun',
  pf_acct_g: 'Tetamu · dipautkan kepada pelayar/peranti ini',
  pf_pw: 'Kata laluan',
  pf_prev: 'Pratonton sahaja dalam prototaip ini.',
  inc_q_day: 'Berapa pendapatan anda hari ini?',
  inc_q_week: 'Berapa pendapatan anda minggu ini?',
  inc_q_month: 'Berapa pendapatan anda bulan ini?',
  ex_q_day: 'Berapa anda belanja hari ini?',
  ex_q_week: 'Berapa anda belanja minggu ini?',
  ex_q_month: 'Berapa anda belanja bulan ini?',
  inc_weekany: 'Pilih mana-mana hari dalam minggu itu.',
  mo_quiet_ask: 'Jika RuMampu tahu bulan perlahan anda, ujian rumah anda lebih tepat.',
  wholemonth: 'Sebulan penuh',
  mo_view_t: 'Jubin',
  mo_view_l: 'Senarai',
  rg_tile_d: 'Julat bayaran yang mampu ditanggung oleh bulan yang direkodkan.',
  cp_tile: 'Banding bayaran',
  cp_tile_d: 'Cuba beberapa jumlah pada bulan yang sama.',
  pf_months: 'Bulan direkod',
  pf_houses: 'Rumah dibina',
  pf_days: 'Hari disimpan',
  pf_prep_h: 'Bersedia untuk pembelian',
  pf_togo: '{v} lagi',
  pf_ready2: 'Cukup',
  pf_buffer_h: 'Untuk bulan perlahan',
  pf_docs_h: 'Senarai semak',
  pf_after_h: 'Selepas membeli',
  pf_about: 'Tentang RuMampu',
  pf_credit: 'Ruma, maskot kami, dibantu AI. Setiap angka dalam aplikasi datang daripada rekod anda sendiri.',
  pf_version: 'Prototaip v19 · EN · BM · 中文',
  tx_intro_t: 'Jom uji sebuah rumah',
  tx_intro: 'Beritahu saya harganya. Saya akan semak dengan {n} bulan yang anda rekod dan tunjukkan bulan mana yang akan kekurangan.',
  tx_ctx: 'Bulan paling perlahan anda tinggal {lo} · bulan biasa {hi}',
  tx_house: 'Rumah',
  tx_price: 'Harga hartanah',
  tx_dep: 'Deposit',
  tx_dep_other: 'Lain',
  tx_inst: 'Ansuran bulanan',
  tx_loan: '{r}% selama {y} tahun',
  tx_other: 'Kos bulanan lain',
  tx_total: 'Jumlah kos bulanan',
  tx_run: 'Jalankan ujian',
  tx_known: 'Saya sudah tahu bayaran bulanan saya',
  tx_known_lbl: 'Bayaran bulanan (RM)',
  tx_back_price: 'Kira daripada harga sebaliknya',
  tx_loan_t: 'Butiran pinjaman',
  tx_costs_t: 'Kos bulanan lain',
  tx_costs_h: 'Penyelenggaraan, insurans dan seumpamanya. Anggaran sudah memadai, boleh diubah bila-bila masa.',
  rx_ok_t: 'Kesemua {n} bulan mampu menanggungnya',
  rx_ok: '{c} sebulan untuk rumah ini muat dalam setiap bulan yang direkod.',
  rx_warn_t: '{s} daripada {n} bulan akan kekurangan',
  rx_warn: 'Pada {months}, {c} sebulan akan menyebabkan anda kekurangan. Jurang terbesar {g}.',
  rx_bad: 'Kebanyakan bulan yang direkod tidak mampu menanggung {c} sebulan. Jurang terbesar {g}.',
  rx_leg_bar: 'Wang yang tinggal setiap bulan selepas kos kerja dan komitmen',
  rx_leg_line: 'Kos bulanan rumah ini',
  rx_leg_gap: 'Kekurangan',
  rx_try_t: 'Kos bulanan rumah · Apa yang boleh',
  rx_try: 'Bulan yang direkodkan mampu menanggung kira-kira {p} sebulan.',
  rx_try_ok: 'Anda berada dalam lingkungan yang setiap bulan mampu tanggung.',
  rx_try_btn: 'Cuba {p}',
  rx_trying: 'Menguji {p} dan bukan {c} rumah ini.',
  rx_use_home: 'Kembali ke rumah ini',
  rx_drop: 'Jika pendapatan jatuh',
  rx_keep: 'Simpan ujian',
  rx_change: 'Ubah rumah',
  rx_how: 'Bagaimana ia dikira',
  sp_title: 'Apa yang anda imbas?',
  sp_in_h: 'Halaman pendapatan atau tangkapan skrin bayaran',
  sp_out_h: 'Resit atau bil',
  cvr_ok_t: 'Rekod anda merangkumi bulan perlahan anda',
  cvr_ok: '{slow} berada dalam {a} hingga {b}, jadi ujian rumah sudah mengambil kiranya.',
  cvr_gap_t: 'Rekod anda belum melihat {m}',
  cvr_gap: 'Anda kata {m} biasanya lebih perlahan, tetapi rekod anda hanya dari {a} hingga {b}. Sehingga itu ujian mungkin nampak lebih baik daripada bulan perlahan sebenar.',
  cvr_gap_do: 'Teruskan merekod sepanjang {m}. Ujian akan mengambil kira bulan itu dengan sendirinya.',
  cvr_flat_t: 'Setiap bulan dikira sama',
  cvr_info_t: 'Maksudnya untuk ujian',
  cvr_pick_hint: 'Pilih setiap bulan yang biasanya lebih perlahan.',
  ex_limit_of: '{v} daripada had bulanan {l} anda',
  ex_edit_limit: 'Ubah had',
  ex_set_limit: 'Tetapkan had bulanan',
  ex_limit_title: 'Had perbelanjaan bulanan',
  ex_limit_hint: 'Jumlah perbelanjaan harian yang anda mahu kekalkan setiap bulan. Tiada yang disekat, bar hanya menunjukkan sejauh mana anda.',
  ex_limit_saved: 'Had bulanan dikemas kini.',
  ex_q_amt: 'Berapa yang anda belanjakan?',
  ex_q_cat: 'Untuk apa?',
  ex_recent: 'Perbelanjaan terkini',
  ex_oflimit: '{v} daripada had {l}',
  xe_title: 'Ubah perbelanjaan',
  xe_del: 'Buang perbelanjaan',
  xe_save: 'Simpan perubahan',
  xe_saved: 'Perbelanjaan dikemas kini.',
  xe_deleted: 'Perbelanjaan dibuang.',
  exc_hint: 'Eksport .csv daripada bank atau e-dompet anda, kemudian pilih di sini.',
  exc_cat: 'Kategori untuk baris ini',
  exc_done: '{n} perbelanjaan ditambah, {a} hingga {b}.',
  io_in: 'Masuk',
  io_out: 'Keluar',
  ht_title: 'Ujian rumah',
  ht_rec: '{n} bulan direkod · {a} hingga {b}',
  ht_short: '{s} daripada {n} bulan akan kekurangan',
  ht_ok: 'Kesemua {n} bulan mampu menanggungnya',
  ht_gap: 'Jurang terbesar {g}',
  ht_go: 'Uji',
  ht_rego: 'Uji semula',
  ht_open: 'Buka ujian',
  mo_sofar: '{m} setakat ini',
  mo_in: 'Masuk',
  mo_out: 'Keluar',
  mo_left: 'Baki',
  mo_fixed: 'Pendapatan dan perbelanjaan harian yang direkod bulan ini.',
  mo_quiet: 'Bulan perlahan anda',
  mo_quietest: 'Paling perlahan',
  mo_usual: 'Biasa',
  mo_quiet_note: 'Baki selepas kos kerja dan komitmen. Ujian rumah bergantung pada bulan yang perlahan.',
  mo_trend: 'Pendapatan selepas kos kerja, {n} bulan lepas',
  mo_permo: '/ bulan',
  mo_pace: 'Kadar perbelanjaan',
  mo_pace_note: '{v} daripada had {l} · hari {d} daripada {n}',
  mo_nolimit: 'Tiada had ditetapkan',
  mo_rec: 'Rekod',
  mo_setup: 'Tetapan',
  mo_insights: 'Pandangan',
  perx_day: 'Sehari',
  perx_week: 'Seminggu',
  perx_month: 'Sebulan',
  inc_for: 'Jumlah ini untuk',
  inc_weekend: 'Minggu berakhir',
  inc_monthof: 'Bulan yang mana?',
  ie_title: 'Ubah catatan',
  ie_save: 'Simpan perubahan',
  ie_saved: 'Catatan dikemas kini.',
  ie_deleted: 'Catatan dibuang.',
  ie_del: 'Buang catatan',
  im_type: 'Manual',
  im_scan: 'Imbas',
  im_csv: 'Import',
  sc_hint: 'Sesuai untuk halaman pendapatan Grab, foodpanda dan Lalamove.',
  sc_pick: 'Ambil gambar atau pilih tangkapan skrin',
  sc_sample: 'Cuba contoh',
  sc_reading: 'Membaca pendapatan anda…',
  sc_found: '{n} catatan dijumpai. Nyahtanda yang tidak mahu.',
  sc_low: 'Keyakinan rendah, sila semak',
  sc_add: 'Tambah {n} catatan',
  sc_added: '{n} catatan ditambah daripada imbasan anda.',
  sc_tag: 'diimbas',
  cv_hint: 'Eksport .csv daripada platform atau bank anda, kemudian pilih di sini.',
  cvi_pick: 'Pilih fail .csv',
  cv_tpl: 'Muat turun templat',
  cv_sample: 'Cuba fail contoh',
  cv_map: 'Semak lajur',
  cv_date: 'Tarikh',
  cv_amt: 'Jumlah',
  cv_desc: 'Keterangan',
  cv_src: 'Sumber untuk baris ini',
  cv_fromdesc: 'Daripada keterangan',
  cv_import: 'Import {n} baris',
  cv_done: '{n} catatan ditambah, {a} hingga {b}.',
  cv_skipped: '{n} pendua dilangkau.',
  cv_none: 'Tiada baris yang boleh diguna. Semak lajur tarikh dan jumlah.',
  cv_tag: 'CSV',
  inc_q_amt: 'Berapa pendapatan anda?',
  inc_q_when: 'Bila?',
  inc_q_src: 'Dari mana?',
  inc_today: 'Hari ini',
  inc_yday: 'Semalam',
  inc_pick: 'Pilih tarikh',
  inc_recent: 'Catatan terkini',
  inc_sofar: '{m} setakat ini: {v}',
  hm_togo: 'Kurang {g} daripada anggaran wang pendahuluan anda',
  hm_ready: 'Anggaran wang pendahuluan anda dicukupi',
  hd_morning: 'Selamat pagi',
  hd_afternoon: 'Selamat petang',
  hd_evening: 'Selamat malam',
  hd_welcome: 'Selamat datang!',
  hd_guest: 'Selamat datang, tetamu',
  ai_title: 'Tanya RuMampu',
  ai_hi: 'Hai! Tanya saya tentang rekod anda, pelan simpanan, atau rumah yang anda fikirkan. Saya hanya jawab daripada angka anda sendiri.',
  ai_q1: 'Mampukah saya beli rumah RM 250k?',
  ai_q2: 'Bagaimana pelan simpanan saya?',
  ai_q3: 'Apa perbelanjaan terbesar saya?',
  ai_ph: 'Taip soalan',
  ai_send: 'Hantar',
  ai_a_afford: 'Bulan anda yang lebih perlahan menanggung kira-kira {m} sebulan selepas kos kerja dan komitmen. Jalankan ujian rumah untuk jawapan penuh.',
  ai_a_plan: 'Anda telah simpan {s} daripada {t} bulan ini, {d} daripada {n} hari selesai. Jumlah hari ini ialah {a}.',
  ai_a_spend: 'Pada {mo} anda paling banyak berbelanja untuk {c}: {v}.',
  ai_a_default: 'Saya hanya jawab daripada rekod anda sendiri, tiada yang direka. Cuba salah satu soalan di bawah.',
  vl_score: 'Skor',
  vl_bestscore: 'Terbaik',
  vl_moves: 'Gerakan',
  vl_short: 'Leret untuk besarkan kampung anda.',
  vl_how: 'Cara bermain',
  vl_s1: 'Setiap hari anda simpan, satu Pondok ditambah ke plot.',
  vl_s2: 'Leret ke kiri, kanan, atas atau bawah: semua rumah bergerak ke arah itu.',
  vl_s3: 'Dua rumah yang sama jenis yang bertemu akan bergabung menjadi saiz seterusnya.',
  vl_s4: 'Teruskan: Pondok, Rumah kampung, Teres, Kondo, kemudian Istana.',
  vl_s5: 'Enam belas hari simpanan cukup untuk satu Istana.',
  vl_start: 'Jom mula!',
  vl_sub: 'Permainan mini 2048: leret untuk gerakkan rumah; dua yang sama bergabung jadi lebih besar.',
  vl_play: 'Main',
  vl_done: 'Selesai',
  vl_daily: 'Pelan harian',
  vl_title: 'Kampung simpanan',
  vl_houses: '{n} rumah',
  vl_builtn: '{b} dibina',
  vl_onplot: '{n} di atas plot',
  vl_best: 'Terbaik: {t}',
  vl_hint: 'Setiap hari yang disimpan menambah satu Pondok. Luncurkan dua yang sama untuk bina lebih besar.',
  vl_built: 'Anda bina {t}!',
  vl_t1: 'Pondok',
  vl_t2: 'Rumah kampung',
  vl_t3: 'Teres',
  vl_t4: 'Kondo',
  vl_t5: 'Istana',
  pl_title: 'Pelan simpanan',
  pl_target: 'Sasaran bulanan',
  pl_today: 'Hari ini',
  pl_save_today: 'Simpan hari ini',
  pl_saved_today: 'Disimpan ✓',
  pl_progress: '{s} daripada {t} disimpan',
  pl_days: '{d} daripada {n} hari',
  pl_hint: 'Jumlah kecil yang berbeza setiap hari. Bersama-sama ia mencapai sasaran anda menjelang hujung bulan.',
  pl_shuffle: 'Kocok hari yang berbaki',
  pl_reached: 'Sasaran dicapai!',
  pl_note: 'Ketik hari untuk tanda sudah simpan. Setiap hari yang disimpan ditambah ke Baki keseluruhan anda. Menukar sasaran hanya membahagi semula hari yang belum disimpan.',
  pl_toast: 'Simpan {a} hari ini. Baki keseluruhan kini {c}.',
  pl_untoast: '{a} dikeluarkan dari hari ini.',
  k_hi: 'Hai!',
  k_intro: 'Sebelum bermula, kami ada beberapa soalan ringkas',
  k_begin: 'Mula',
  k_next: 'Seterusnya',
  k_j_taxi: 'E-hailing',
  k_j_bar: 'Pelayan bar',
  k_own: 'Tambah sendiri',
  k_own_h: 'Nama kerja anda',
  hm_saving: 'Baki keseluruhan',
  hm_mysav: 'Baki saya',
  hm_income: 'Pendapatan',
  hm_exp: 'Perbelanjaan',
  tab_profile: 'Profil',
  pf_title: 'Profil',
  pf_guest_t: 'Mod tetamu',
  pf_guest: 'Rekod anda mungkin masih tersedia pada pelayar/peranti ini. Tiada akaun RuMampu dicipta.',
  pf_create: 'Buka akaun',
  pf_signed_t: 'Sudah log masuk',
  pf_signed: 'Rekod anda disimpan untuk kali seterusnya.',
  pf_lang: 'Bahasa',
  pf_export: 'Eksport rekod saya',
  pf_export_done: 'Eksport rekod sudah sedia.',
  pf_export_failed: 'Eksport rekod gagal. Sila cuba lagi.',
  pf_delete: 'Padam akaun dan rekod',
  pf_delete_guest: 'Padam rekod tetamu',
  pf_delete2: 'Ketik sekali lagi untuk padam',
  pf_delete_confirm: 'Ketik padam sekali lagi untuk membuang akaun dan rekod ini secara kekal.',
  pf_delete_guest_confirm: 'Ketik padam sekali lagi untuk membuang rekod tetamu ini secara kekal.',
  pf_delete_done: 'Rekod dipadam.',
  pf_delete_failed: 'Rekod tidak dapat dipadam. Sila cuba lagi.',
  pf_prepare: 'Bersedia untuk rumah',
  qk_title: 'Apa yang anda mahu tambah?',
  qk_income: 'Pendapatan',
  qk_expense: 'Perbelanjaan',
  qk_scan: 'Imbas resit',
  k_title: 'Mari berkenalan',
  k_skip: 'Langkau',
  k_q1: 'Apa kerja anda?',
  k_q1h: 'Pilih semua yang berkenaan. Ini menjadi sumber pendapatan anda.',
  k_q2: 'Berapa pendapatan anda bulan lepas?',
  k_q2h: 'Satu angka kasar sudah cukup untuk bermula. Pilihan.',
  k_ph: 'cth. 3,000',
  k_go: 'Mula guna RuMampu',
  k_j_ehail: 'E-hailing',
  k_j_deliv: 'Penghantaran makanan',
  k_j_free: 'Pekerja bebas',
  k_j_part: 'Separuh masa',
  k_j_stall: 'Perniagaan kecil',
  k_j_other: 'Lain-lain',
  k_saved: 'Rekod anda telah bermula. Semuanya boleh diubah.',
  wf_step: 'Langkah {n} daripada 3',
  wf_langq: 'Bahasa mana yang terasa seperti rumah?',
  wf_next: 'Seterusnya',
  wf_hi: 'Hai, saya Ruma!',
  wf_blend: '<b>RuMampu</b> gabungan <i>rumah</i> dan <i>mampu</i>: mampukah saya memiliki rumah?',
  wf_f1t: 'Rekod sebenar anda',
  wf_f1d: 'Catat pendapatan dan perbelanjaan anda',
  wf_f2t: 'Ujian rumah',
  wf_f2d: 'Saya semak rumah pilihan anda berdasarkan rekod anda',
  wf_f3t: 'Privasi terjamin',
  wf_f3d: 'Angka anda kekal milik anda, tiada yang direka',
  wf_copy: '© 2026 RuMampu oleh Cendol Compiler · Dibuat di Malaysia untuk mereka yang berpendapatan tidak tetap · SDG 11',
  wf_meet: 'Selamat berkenalan →',
  au_hello: 'Helo!',
  au_create: 'Buka<br>akaun',
  au_ctag: 'Simpan rekod anda untuk kali seterusnya.',
  au_login: 'Log masuk',
  au_email: 'E-mel',
  au_pw: 'Kata laluan',
  au_show: 'Tunjuk',
  au_hide: 'Sembunyi',
  au_eph: 'nama@contoh.com',
  au_pph: 'Kata laluan anda',
  au_p8: 'Sekurang-kurangnya 8 aksara',
  au_cpw: 'Sahkan kata laluan',
  au_again: 'Taip sekali lagi',
  au_mix: 'Guna campuran huruf dan nombor.',
  au_mailhow: 'Bagaimana kami guna e-mel anda',
  au_forgot: 'Lupa kata laluan?',
  au_or: 'atau teruskan dengan',
  au_google: 'Teruskan dengan Google',
  au_new: 'Baru di sini?',
  au_createbtn: 'Buka akaun',
  au_createacct: 'Buka akaun',
  au_guest: 'Teruskan sebagai tetamu',
  au_guest2: 'Teruskan sebagai tetamu sahaja',
  au_guestnote: 'Rekod anda mungkin masih tersedia pada pelayar/peranti ini. Tiada akaun RuMampu dicipta.',
  au_mailonly: 'E-mel anda hanya untuk log masuk dan set semula kata laluan.',
  au_have: 'Sudah ada akaun?',
  au_mailhow_t: 'E-mel anda hanya untuk log masuk dan menghantar pautan set semula. Tiada yang lain.',
  au_forgot_t: 'Aliran set semula kata laluan (stub reka bentuk).',
  au_backlogin: '← Kembali ke log masuk',
  home_rec: 'Anda ada {n} bulan pendapatan direkod.',
  home_rec_thin: '{n} bulan ialah rekod yang nipis. Setiap catatan baharu membantu ujian melihat lebih.',
  home_test: 'Uji sebuah rumah',
  home_retest: 'Uji semula rumah itu',
  headline: '{s} daripada {n} bulan direkod anda tidak akan cukup.',
  headline_zero: 'Kesemua {n} bulan direkod anda menutup kos ini.',
  gap_lbl: 'Jurang terbesar',
  covspan: '{a} hingga {b} direkod',
  cov_unchecked: 'Bulan perlahan belum ditetapkan',
  cov_missed: 'Rekod anda belum melihat {m}. Anda kata ia biasanya perlahan.',
  money_income: 'Pendapatan',
  money_workcosts: 'Kos kerja',
  money_commit: 'Komitmen',
  money_pattern: 'Corak pendapatan',
  money_coverage: 'Bulan perlahan',
  net_lbl: 'Pendapatan selepas kos kerja',
  per_month: '/ bulan, purata',
  inc_empty: 'Masukkan pendapatan minggu lepas. Itu sudah cukup untuk bermula.',
  inc_amount: 'Jumlah (RM)',
  inc_date: 'Tarikh',
  inc_source: 'Sumber',
  inc_add: 'Tambah pendapatan',
  inc_neg: 'Jumlah bawah sifar tidak dapat disimpan.',
  inc_outlier: 'Jauh lebih tinggi daripada catatan biasa anda. Kekalkan?',
  src_ehail: 'E-hailing',
  src_freelance: 'Kerja bebas',
  src_parttime: 'Separuh masa (tetap)',
  src_own: '+ Sumber anda sendiri',
  src_name: 'Nama sumber',
  entry_saved: 'Catatan disimpan',
  wc_petrol: 'Petrol',
  wc_service: 'Servis kenderaan',
  wc_platform: 'Yuran platform',
  wc_data: 'Data telefon',
  wc_roadtax: 'Cukai jalan & insurans',
  wc_own: '+ Kos anda sendiri',
  wc_note: 'Setiap skrin selepas ini menggunakan angka ini.',
  cm_living: 'Kos sara hidup',
  cm_debts: 'Bayaran hutang',
  cm_savings: 'Simpanan',
  cm_rent: 'Sewa',
  cm_food: 'Makanan',
  cm_util: 'Utiliti',
  cm_motor: 'Pinjaman motosikal',
  cm_ptptn: 'PTPTN',
  cm_family: 'Sokongan keluarga',
  cm_save: 'Simpanan bulanan',
  cm_total: 'Jumlah komitmen',
  pt_avg: 'Purata',
  pt_med: 'Penengah',
  pt_high: 'Tertinggi',
  pt_low: 'Terendah',
  pt_range: 'tambah tolak RM {x}, bulan demi bulan',
  pt_quietx: 'Bulan paling perlahan dalam rekod anda ialah {m}: {v} selepas kos kerja.',
  pt_namex: 'Anda boleh namakan bulan yang biasanya kurang pendapatan di bawah {L}.',
  tx_price_ph: 'cth. 250,000',
  tx_need_price: 'Masukkan harga hartanah dahulu. Harga datang daripada anda.',
  au_demo: 'DEMO',
  rx_tryres: '{s} daripada {n} bulan akan kekurangan pada {p}.',
  rc_live_guest: 'Setiap skrin dikemas kini apabila anda menambah. Rekod anda mungkin masih tersedia pada pelayar/peranti ini. Tiada akaun RuMampu dicipta.',
  rc_live_acct: 'Setiap skrin dikemas kini apabila anda menambah. Sudah log masuk: rekod anda disimpan untuk kali seterusnya.',
  pt_none: 'Tiada bulan direkod jatuh bawah garis itu.',
  pt_some: 'Bawah garis itu: {m}.',
  cv_q: 'Ada musim anda biasanya kurang pendapatan?',
  cv_yes: 'Ya',
  cv_no: 'Tidak',
  cv_notsure: 'Tak pasti',
  cv_pick: 'Tandakan bulan yang biasanya perlahan.',
  cv_unseen: 'Anda kata {slow} biasanya perlahan. Rekod anda meliputi {a} hingga {b}, jadi ujian ini belum melihat bulan perlahan.',
  cv_seen: 'Anda kata {slow} biasanya perlahan. Rekod anda meliputi {a} hingga {b}, dan bulan perlahan ada di dalamnya.',
  cv_narrow: 'Angka direkod anda terlalu rapat antara satu sama lain. Bulan lemah mungkin tiada dalam rekod.',
  cv_varied: 'Angka direkod anda berbeza dari bulan ke bulan. Ujian ini tetap hanya kenal {a} hingga {b}.',
  cv_note: 'Bulan tambahan hanya membantu jika bulan yang betul ada di dalamnya.',
  th_title: 'Rumah itu',
  th_price: 'Harga hartanah (RM)',
  th_fin: 'Jumlah pembiayaan',
  th_dep: 'Bayaran muka (RM)',
  th_dep0: 'RM 0 dibenarkan. Pembiayaan 100% wujud.',
  th_rate: 'Kadar (% / tahun)',
  th_ten: 'Tempoh (tahun)',
  th_inst: 'Ansuran bulanan',
  th_known: 'Saya sudah tahu bayaran bulanan saya',
  th_knownamt: 'Bayaran bulanan (RM)',
  th_next: 'Jumlah kos bulanan',
  tc_title: 'Jumlah kos bulanan',
  tc_point: 'Ansuran bukan keseluruhan kos.',
  tc_inst: 'Ansuran',
  tc_break: 'Apa di dalamnya',
  tc_run: 'Jalankan ujian',
  hc_maint: 'Penyelenggaraan & tabung penjelas',
  hc_insure: 'Insurans rumah',
  hc_assess: 'Cukai pintu',
  hc_quit: 'Cukai tanah',
  hc_parking: 'Parkir',
  hc_other: 'Lain-lain',
  pc_title: 'Sebelum rumah',
  pc_msg: 'Pada {m}, bulan paling perlahan dalam rekod anda, pendapatan RM {x} di bawah kos harian anda, sebelum sebarang kos rumah.',
  pc_msg2: 'Bayaran rumah di atasnya akan menjadikan semua bulan kurang, pada apa jua harga. Semak dahulu pendapatan dan kos supaya ujian ini berpijak lebih kukuh.',
  pc_btn: 'Pergi ke Wang',
  rs_title: 'Keputusan',
  rs_how: 'Bagaimana ia dikira',
  rs_how_body: 'Setiap bar ialah satu bulan direkod: pendapatan selepas kos kerja, tolak komitmen. Garisan ialah jumlah kos rumah bulanan, RM {c}. Bulan dikira kurang bila barnya berakhir di bawah garisan.',
  rs_limit_slow: 'Ujian ini belum melihat {m}, yang anda kata biasanya perlahan. Kiraan di bawah belum merangkumi musim yang lebih perlahan itu.',
  rs_limit_thin: 'Baru {n} bulan direkod. Belum cukup untuk kiraan ini membawa makna.',
  rs_range: 'Julat terbawa',
  rs_compare: 'Banding bayaran',
  rs_shock: 'Jika pendapatan turun',
  rg_lead: 'Bulan-bulan direkod anda membawa bayaran RM {a} hingga RM {b} sebulan.',
  rg_how: 'Maksud dua hujung itu',
  rg_how_body: 'RM {a}: semua bulan direkod menutupnya. RM {b}: separuh daripadanya.',
  rg_price: 'Pada {r}% selama {y} tahun, itu sekitar RM {p} hingga RM {q} harga rumah.',
  rg_pin: 'ujian anda',
  rg_ind: 'Petunjuk sahaja. Bukan penilaian, bukan tawaran.',
  cp_note: 'Bulan direkod yang sama, tiga bayaran.',
  cp_short: '{s} daripada {n} kurang',
  cp_gap: 'jurang terbesar RM {g}',
  cp_pay: 'Bayaran {i} (RM)',
  sh_note: 'Andaian ke atas bulan direkod anda, bukan tentang masa hadapan.',
  sh_custom: 'Sendiri',
  sh_pct: 'Turun (%)',
  sh_head: 'Pada −{p}%: {s} daripada {n} bulan direkod tidak akan cukup.',
  pr_upfront: 'Tunai permulaan',
  pr_buffer: 'Penampan tunai',
  pr_docs: 'Dokumen & pembiayaan',
  pr_pv: 'Pratonton Iterasi 3',
  pr_pv_note: 'Selepas membeli. Hala tuju sahaja, belum dilancarkan.',
  uf_have: 'Anda ada',
  uf_need: 'Anda perlu',
  uf_gap: 'Jurang',
  uf_dep: 'Bayaran muka',
  uf_legal: 'Yuran guaman',
  uf_stampT: 'Duti setem (pindah milik)',
  uf_stampL: 'Duti setem (pinjaman)',
  uf_val: 'Penilaian hartanah',
  uf_disb: 'Perbelanjaan pelbagai guaman',
  uf_move: 'Pindah rumah',
  uf_basic: 'Asas (peti sejuk, katil, langsir)',
  uf_dep0: 'Deposit RM 0: tunai permulaan ialah yuran dan persiapan, bukan deposit.',
  bf_def: 'Jumlah terkecil yang anda perlukan pada permulaan untuk melepasi bulan-bulan kurang dalam rekod anda tanpa jatuh bawah sifar.',
  bf_basis: 'Daripada rekod anda sendiri, {a} hingga {b}. Bukan peraturan umum.',
  bf_zero: 'Dengan rumah ini, bulan direkod anda tidak pernah jatuh bawah sifar. Kiraannya RM 0.',
  bf_bal: 'Baki berjalan ikut bulan',
  dc_bank: 'Penyata bank, 6 bulan',
  dc_ehail: 'Ringkasan pendapatan e-hailing',
  dc_statdec: 'Surat akuan berkanun pendapatan',
  dc_epf: 'Penyata KWSP',
  dc_commitlist: 'Senarai komitmen sedia ada',
  dc_sjkp: 'Kriteria terbitan SJKP',
  dc_sj1: 'Warganegara Malaysia, umur 18 hingga 70',
  dc_sj2: 'Pendapatan kasar dalam had terbitan SJKP',
  dc_sj3: 'Rumah pertama',
  dc_src: 'Sumber: sjkp.com.my, Ogo 2026',
  dc_65: 'Semakan 65%: perlu semakan semula',
  dc_65_note: 'SJKP mengukur pendapatan kasar; RuMampu mengukur pendapatan selepas kos kerja. Selagi beza itu belum selesai, tiada keputusan ditunjukkan di sini.',
  dc_plain: 'RuMampu tidak memohon bagi pihak anda dan tidak dapat memberitahu sama ada bank akan kata ya.',
  pv_banner: 'Pratonton Iterasi 3',
  pv_switch: 'Tukar mod',
  pv_switch_btn: 'Saya sudah beli rumah itu',
  pv_switch_note: 'Anggaran bertukar kepada angka sebenar. Pembelian berlaku di luar RuMampu.',
  pv_month: 'Bulan ini',
  pv_in: 'Pendapatan sebenar masuk',
  pv_out: 'Kos rumah sebenar keluar',
  pv_left: 'Baki tunai',
  pv_shortby: 'Kurang sebanyak',
  pv_then: 'Ujian awal vs yang berlaku',
  pv_then_a: 'Ujian awal anda: {s} bulan kurang daripada {n} direkod.',
  pv_then_b: 'Sejak membeli: {s2} daripada {n2} bulan pertama anda kurang.',
  pv_then_why: 'Rekod awal tiada bulan hujung tahun di dalamnya. Dua bulan begitu tiba selepas membeli.',
  see_pattern: 'Corak pendapatan',
  see_coverage: 'Semakan liputan',
  money_record: 'Rekod anda',
  rc_months: '{n} bulan direkod',
  rc_entries: '{e} catatan, terkini {d}',
  rc_tests: 'Ujian disimpan',
  rc_none: 'Belum ada ujian disimpan. Jalankan satu dari tab Uji.',
  rc_live: 'Rekod kewangan anda mungkin masih tersedia pada pelayar/peranti ini. Ia dipautkan kepada ID tetamu tanpa nama, bukan akaun RuMampu.',
  rc_keep_line: 'Setiap minggu baharu yang anda rekodkan memberi ujian seterusnya lebih banyak bulan sebenar anda.',
  rs_keep: 'Simpan ujian ini',
  rs_kept: 'Ujian disimpan',
  entry_saved_n: 'Catatan disimpan. Anda kini mempunyai {n} catatan pendapatan.',
  inc_past: 'Tambah bulan lalu',
  inc_past_hint: 'Satu jumlah untuk bulan itu sudah cukup.',
  pt_bymonth: 'Bulan demi bulan',
  pv_keep: 'Terus merekod selepas membeli. Rekod yang sama terus berfungsi.',
  money_expenses: 'Perbelanjaan harian',
  ex_sofar: '{m} setakat ini',
  ex_days: '{d} hari direkod',
  ex_add: 'Tambah perbelanjaan',
  ex_scan: 'Imbas resit',
  ex_preview: 'Pratonton',
  ex_bycat: 'Ikut kategori',
  xc_meals: 'Makan',
  xc_groc: 'Barang dapur',
  xc_transp: 'Tol & parkir',
  xc_family: 'Keluarga',
  xc_other: 'Lain-lain',
  xc_own: '+ Kategori anda',
  ex_saved: 'Disimpan. {m} setakat ini: RM {x}.',
  ex_rule: 'Sebulan dikira lengkap apabila 20 hari direkodkan. Peraturan RuMampu sendiri.',
  ex_feeds: '{m} menggunakan perbelanjaan direkod anda, RM {x}, menggantikan anggaran makanan dan keluarga.',
  ex_scan_pick: 'Ambil atau pilih gambar resit.',
  ex_scan_sample: 'Guna resit contoh',
  ex_reading: 'Membaca resit…',
  ex_check: 'Dibaca daripada resit anda. Semak sebelum menyimpan.',
  ex_merchant: 'Kedai',
  ex_total: 'Jumlah (RM)',
  ex_retake: 'Ambil semula',
  ex_fromr: 'daripada resit',
  ex_cat: 'Kategori',
  ex_monthly: 'Ringkasan bulanan',
  ex_see_sum: 'Lihat ringkasan bulanan',
  ex_set_lims: 'Tetapkan had perbelanjaan',
  ex_full: 'lengkap direkod',
  ex_used: 'digunakan dalam ujian',
  ex_partial: '{d} hari, hari lain tidak diketahui',
  ex_limits: 'Had perbelanjaan',
  lm_note: 'Had bulanan ini anda yang tetapkan. RuMampu hanya mengira.',
  lm_total: 'Keseluruhan bulan',
  lm_limit: 'Had (RM)',
  lm_left: 'RM {x} lagi',
  lm_over: 'RM {x} melebihi had anda',
  lm_none: 'tiada had ditetapkan',
  hb_spend: 'Perbelanjaan · {m}',
  hb_income: 'Pendapatan · {m}',
  /* App-only keys (backend sync/error copy) kept from the previous build. */
  retry: 'Cuba sekali lagi',
  home_rec_one: 'Anda ada 1 bulan duit masuk direkod.',
  home_rec_thin_one: '1 bulan ialah rekod yang nipis. Setiap catatan baharu membantu ujian nampak lebih.',
  inc_sync_loading: 'Sedang muat rekod duit masuk tersimpan anda…',
  inc_sync_error: 'Tak boleh dapat rekod simpan. Semak server dan cuba lagi.',
  inc_invalid_date: 'Gunakan tarikh betul bentuk YYYY-MM-DD.',
  inc_invalid_amount: 'Masukkan jumlah wang yang sah menggunakan nombor sahaja, dengan maksimum 2 tempat perpuluhan.',
  inc_save_failed: 'Duit masuk tak boleh simpan. Sila cuba lagi.',
  inc_saving: 'Menyimpan…',
  wc_name: 'Nama kos kerja',
  xc_name: 'Nama kategori',
  wc_add: 'Tambah kos kerja',
  wc_category: 'Kategori kos kerja',
  wc_month: 'Bulan',
  wc_month_note: 'Memaparkan {m}. Pilih bulan semasa atau bulan yang mempunyai rekod.',
  wc_income_formula: '{income} pendapatan − {costs} kos kerja direkod untuk bulan ini.',
  wc_cost_total: '{costs} kos kerja direkod untuk bulan ini.',
  wc_no_income: 'Tiada pendapatan direkod untuk {m}. Tambah pendapatan sebelum RuMampu boleh mengira angka ini.',
  wc_month_unavailable: 'Pilih bulan semasa atau bulan yang mempunyai rekod pendapatan atau kos kerja.',
  wc_entry_amount: 'Amaun kos kerja',
  wc_edit_amount: 'Edit amaun kos kerja',
  wc_so_far: 'Bulan semasa: rekod setakat ini, bukan ramalan atau jumlah sebulan penuh.',
  wc_no_costs: 'Tiada kos kerja direkod untuk bulan ini. Ini tidak bermakna tiada kos berlaku.',
  wc_summary_unavailable: 'Hasil bulanan tidak tersedia sehingga rekod terkini dimuatkan.',
  wc_recorded: 'Kos kerja direkod',
  wc_empty: 'Belum ada kos kerja direkod.',
  wc_entry_invalid: 'Pilih kategori dan masukkan amaun serta tarikh yang sah.',
  wc_sync_loading: 'Memuatkan kos kerja anda…',
  wc_sync_error: 'Kos kerja tak boleh disegerakkan. Cuba lagi.',
  wc_save_failed: 'Kos kerja tak boleh simpan. Sila cuba lagi.',
  cm_sync_loading: 'Memuatkan tanggungan anda…',
  cm_sync_error: 'Tanggungan tak boleh disegerakkan. Cuba lagi.',
  cm_save_failed: 'Tanggungan tak boleh simpan. Sila cuba lagi.',
  pt_range_total: 'Julat direkod',
  pt_std: 'Sisihan piawai',
  pt_month_count: '{n} bulan direkod',
  pt_loading: 'Mengira cara duit masuk daripada rekod tersimpan…',
  pt_error: 'Cara duit masuk yang dikira tak boleh dicapai. Duit masuk tersimpan anda tak berubah.',
  pt_api_required: 'Analisis Epic 2 hanya ada dalam mod API bersambung. Tetapkan EXPO_PUBLIC_APP_MODE=api dan mulakan backend.',
  pt_empty: 'Cara duit masuk mula dengan satu bulan direkod.',
  pt_empty_note: 'Tambah duit masuk untuk nampak duit boleh guna bulan demi bulan.',
  pt_add_income: 'Tambah duit masuk',
  pt_limited_one: 'Ini satu bulan direkod. Ia tunjuk fakta bulan tu, tapi belum boleh gambarkan cara yang lebih luas.',
  pt_limited_two: 'Ini dua bulan direkod. Angka ni berdasarkan fakta, tapi sejarah yang nampak masih terhad.',
  pt_work_basis: 'Setiap bulan direkod hanya menggunakan catatan kos kerja bertarikh bulan itu sendiri.',
  pt_rule: 'Bulan kurang duit masuk di sini ialah bulan duit boleh guna terendah dalam rekod semasa anda. Ia bukan piawaian kewangan atau ramalan.',
  cv_loading: 'Memuatkan jawapan liputan tersimpan…',
  cv_error: 'Liputan tak boleh dimuatkan atau disimpan. Anda boleh cuba lagi tanpa hilang jawapan terakhir yang disahkan.',
  cv_check: 'Semak liputan',
  cv_checking: 'Menyemak…',
  cv_select_required: 'Pilih sekurang-kurangnya satu bulan lembap.',
  cv_save_failed: 'Liputan tak boleh simpan. Sila cuba lagi.',
  cv_represented: 'Dalam rekod duit masuk anda: {m}.',
  cv_unrepresented: 'Belum dalam rekod duit masuk anda: {m}.',
  cv_observation: 'Dalam {n} bulan direkod, duit boleh guna antara {lo} dan {hi}, dengan julat {range}. Fakta ni tak boleh sahkan sama ada tempoh lembap biasa anda ada.',
  cv_api_required: 'Semakan liputan hanya ada dalam mod API bersambung. Tetapkan EXPO_PUBLIC_APP_MODE=api dan mulakan backend.',
  cv_no_history: 'Belum ada bulan duit masuk direkod untuk dibandingkan.',
  cv_previous: 'Hasil di bawah ialah jawapan terakhir yang disahkan oleh pelayan. Pilihan baharu anda belum disimpan.',
  tc_inst_desc: 'Daripada butiran pembiayaan anda',
  housing_running: 'Sedang kira…',
  housing_run_failed: 'Pengiraan rumah tak boleh selesai. Sila cuba lagi.',
  housing_result_required: 'Jalankan ujian rumah dulu supaya skrin ni boleh guna hasil yang dikira oleh pelayan.',
  hc_maint_desc: 'Untuk pembaikan dan penyelenggaraan',
  hc_insure_desc: 'Insurans rumah asas',
  hc_assess_desc: 'Dibayar kepada pihak berkuasa tempatan',
  hc_quit_desc: 'Sewa tanah (jika berkenaan)',
  hc_parking_desc: 'Kos parkir bulanan',
  hc_other_desc: 'Kos berulang lain',
  rs_shortfall_breakdown: 'Punca kekurangan',
  rs_existing_shortfall: 'Sudah kurang sebelum kos rumah',
  rs_housing_shortfall: 'Jadi kurang sebab rumah ni',
  rs_shortfall_breakdown_note: 'Kekurangan sedia ada dah bawah kosong sebelum kos rumah ditambah. Kekurangan sebab rumah ialah bulan yang jadi negatif lepas kos rumah ujian ni digunakan.',
  cp_price: 'RM {payment}/bulan ≈ nilai rumah RM {price}',
  cp_price_note: 'Anggaran je, guna kadar, tempoh dan deposit yang dimasukkan untuk ujian ni.',
  sh_disclaimer: 'Senario hipotesis, bukan ramalan.',
  pr_coming: 'Akan datang',
  pr_coming_note: 'Bahagian ni sedang dibina.',
  rc_months_one: '1 bulan direkod',
  rc_summary: 'Rekod kewangan',
  rc_month_metric: 'bulan direkod',
  rc_month_metric_one: 'bulan direkod',
  rc_entry_metric: 'catatan kewangan',
  rc_latest_label: 'Catatan terkini',
  rc_latest: 'Catatan terkini: {d}',
  rc_latest_empty: 'Belum ada catatan duit masuk atau perbelanjaan bertarikh.',
  rc_none_title: 'Belum ada ujian disimpan',
  rc_none_body: 'Jalankan ujian rumah dan simpan hasilnya di sini untuk sesi ini.',
  rc_test_action: 'Pergi ke Cuba',
  rc_about: 'Tentang rekod anda',
  rc_test_session: 'Disimpan untuk sesi ni.',
  rc_pay_month: '{p} / bulan',
  rc_short_label: 'Bulan kurang',
  rc_short_value: '{s} daripada {n}',
  rs_keep_hint: 'Tambah hasil ni ke Rekod anda untuk sesi ni.',
  rs_kept_session: 'Disimpan untuk sesi ni.',
  inc_recorded: 'Pendapatan direkodkan',
  inc_past_no_min: 'Tambah sejarah yang anda ada. Tak ada minimum 6 atau 12 bulan.',
  inc_past_month: 'Bulan lalu (YYYY-MM)',
  inc_past_invalid: 'Masukkan bulan betul yang lebih awal daripada bulan sekarang.',
  inc_past_exists: 'Bulan tu dah ada rekod duit masuk. Pilih bulan lain.',
  inc_past_amount: 'Masukkan jumlah yang lebih besar daripada kosong.',
  inc_past_cash: 'Masukkan jumlah wang yang sah menggunakan nombor sahaja, dengan maksimum 2 tempat perpuluhan.',
  inc_month_total: 'Jumlah bulanan',
  inc_import: 'Import duit masuk daripada CSV',
  imp_title: 'Import duit masuk',
  imp_intro: 'Pilih fail CSV. RuMampu akan sediakan pratonton sebelum sebarang data ditambah.',
  imp_format: 'Lajur wajib: amount, date, source. Tarikh mesti tarikh lalu dalam format YYYY-MM-DD.',
  imp_select: 'Pilih fail CSV',
  imp_reading: 'Membaca fail…',
  imp_summary: '{name}: {total} baris',
  imp_ready: '{n} sedia',
  imp_attention: '{n} perlu perhatian',
  imp_row: 'Baris {n}',
  imp_raw: 'Asal: {amount} · {date} · {source}',
  imp_confirm: 'Sahkan dan tambah {n} rekod',
  imp_confirming: 'Menambah rekod…',
  imp_confirmed: '{n} rekod duit masuk ditambah. Analisis anda sekarang gunakannya.',
  imp_failed: 'Fail duit masuk tak boleh diproses. Semak CSV dan cuba lagi.',
  imp_view_pattern: 'Lihat cara duit masuk',
  imp_no_ready: 'Tiada baris sah yang sedia untuk ditambah.',
  pt_chart_accessibility: 'Duit boleh guna dikira bulan demi bulan',
  pt_scroll: 'Tatal secara mendatar untuk lihat semua bulan direkod.',
  ex_days_one: '1 hari direkod',
  ex_empty: 'Belum ada perbelanjaan harian direkod.',
  ex_sync_loading: 'Memuatkan perbelanjaan tersimpan anda…',
  ex_sync_error: 'Perbelanjaan tak boleh disegerakkan. Cuba lagi.',
  ex_saving: 'Menyimpan…',
  ex_amount_positive: 'Masukkan jumlah yang lebih besar daripada kosong.',
  ex_date_invalid: 'Masukkan tarikh kalendar yang sah.',
  ex_save_failed: 'Perbelanjaan tak boleh simpan. Cuba lagi.',
  ex_take_photo: 'Ambil foto',
  ex_choose_photo: 'Pilih foto',
  ex_image_failed: 'Gambar resit tak boleh buka. Cuba lagi.',
  ex_scan_failed: 'Resit tak boleh dibaca buat masa ni. Cuba lagi, atau tambah perbelanjaan secara manual.',
  ex_not_receipt: 'Gambar tu tak nampak macam resit. Cuba ambil gambar resit yang lebih jelas.',
  ex_ai_suggested: 'Cadangan AI',
  ex_scan_partial: 'Ada maklumat tak boleh dibaca daripada resit. Isi ruang kosong dulu sebelum simpan.',
  as_title: 'Tanya RuMampu',
  as_hint: 'Tanya pasal duit anda atau sesuatu keputusan…',
  as_send: 'Hantar',
  as_empty: 'Tanya saya pasal duit masuk, perbelanjaan, atau keputusan ujian rumah anda. Saya hanya guna apa yang anda rekod.',
  as_thinking: 'Tengah fikir…',
  as_error: 'Pembantu tak dapat jawab buat masa ni. Cuba lagi.',
  as_limit: 'Pembantu dah sampai had mesej hari ni. Cuba lagi esok.',
  as_disclaimer: 'Penjelasan daripada rekod anda sendiri. Bukan nasihat kewangan.',
  ex_partial_one: '1 hari, hari lain tak diketahui',
},
zh: {
  langname: '中文',
  months: ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'],
  tab_home: '主页',
  tab_money: '收支',
  tab_test: '房屋',
  tab_prepare: '准备',
  back: '返回',
  add: '添加',
  edit: '修改',
  done: '完成',
  cancel: '取消',
  keep: '保留',
  remove: '删除',
  saved: '已保存',
  unknown: '未知',
  lang_pick: '语言',
  prov_user: '你的记录',
  prov_official: '官方',
  prov_calc: '计算所得',
  prov_assume: '假设',
  provf_user: '用户数据：你自己输入的数字。',
  provf_official: '官方来源：已公布的数字，注明来源和日期。',
  provf_calc: '推导计算：只对你自己的记录做算术，别无其他。',
  provf_assume: '压力测试假设：可修改的默认值，不是关于你的事实。',
  ob1: 'RuMampu 帮你看看，房屋月供在收入较慢的月份是否也过得去，而不只看平均。',
  ob2: '它把数字清楚地摆出来，决定始终在你手上。',
  ob3: '有什么就从什么开始，一周的收入已是很好的起点。',
  ob_skip: '跳过',
  ob_next: '下一步',
  ob_start: '开始',
  ob_slogan: '让真实的月份，替你算一算。',
  pl_sec: '本月计划',
  sp_add_t: '第二个储蓄罐',
  sp_add_b: '第二个储蓄罐可以专门为现金缓冲存钱，首付现金页会单独计算它。储蓄罐如何转移资金仍待团队决定，此处仅为预览。',
  sp_pots: '储蓄罐',
  rx_custom: '自定义',
  rx_try_go: '测试',
  sp_pot: '储蓄罐',
  sp_pot1: '主储蓄罐',
  sp_pot1h: '存放你的储蓄计划和现金缓冲',
  sp_addpot: '为缓冲添加一个储蓄罐',
  sp_pot_soon: '储蓄罐机制待团队决定，仅为预览。',
  uf_pot: '储蓄罐',
  uf_withpot: '你的现金加储蓄罐：{z}，需要 {n}。',
  mo_savings: '储蓄',
  sv_name_t: '为这次测试命名',
  sv_name_l: '名称',
  sv_edit_t: '已存测试',
  sv_pay_l: '测试的每月成本 (RM)',
  sv_open_l: '打开此结果',
  sv_edit_l: '编辑此测试',
  sv_del: '删除此测试',
  sv_del2: '再点一次确认删除',
  fg_tag: '找回你的账户。',
  cm_tag: '重置链接已发出。',
  hh_test: '测试房屋',
  sv_chip: '已存',
  hh_test_d: '用已记录的月份检验一套房。',
  hh_prep: '为买房做准备',
  hh_prep_d: '首付现金、现金缓冲、文件。',
  sv_title: '已存测试',
  sv_none: '还没有保存的测试。运行一次测试，并仅为本次会话保存后会显示在这里。',
  sv_kept_where: '已为本次会话保存到 房屋 › 已存测试。',
  au_made: '账户已创建。请登录继续。',
  fg_title: '忘记密码',
  fg_hint: '输入邮箱，我们会发送重置链接。',
  fg_send: '发送重置链接',
  cm_title: '请查收邮件',
  cm_body: '重置链接已发往 {e}。打开即可设置新密码。',
  cm_resend: '重新发送链接',
  cm_back: '返回登录',
  mh_title: '我们如何使用你的邮箱',
  mh_body: '仅用于登录和重置密码。不做营销，不共享，不出售。',
  pf_acct: '账户',
  pf_acct_g: '访客 · 关联到此浏览器/设备',
  pf_pw: '密码',
  pf_prev: '原型中仅为预览。',
  inc_q_day: '你今天赚了多少？',
  inc_q_week: '你这周赚了多少？',
  inc_q_month: '你这个月赚了多少？',
  ex_q_day: '你今天花了多少？',
  ex_q_week: '你这周花了多少？',
  ex_q_month: '你这个月花了多少？',
  inc_weekany: '选这周的任意一天即可。',
  mo_quiet_ask: '告诉 RuMampu 你的淡季月份，房屋测试会更准。',
  wholemonth: '整月',
  mo_view_t: '磁贴',
  mo_view_l: '列表',
  rg_tile_d: '你已记录的月份能承担的付款范围。',
  cp_tile: '比较付款',
  cp_tile_d: '用同样的月份试几个金额。',
  pf_months: '已记录月份',
  pf_houses: '已建房子',
  pf_days: '已存天数',
  pf_prep_h: '为购房做好准备',
  pf_togo: '还差 {v}',
  pf_ready2: '已足够',
  pf_buffer_h: '应对淡季',
  pf_docs_h: '清单',
  pf_after_h: '购房之后',
  pf_about: '关于 RuMampu',
  pf_credit: '我们的吉祥物 Ruma 由 AI 辅助创作。应用里的每个数字都来自你自己的记录。',
  pf_version: '原型 v19 · EN · BM · 中文',
  tx_intro_t: '来测试一套房吧',
  tx_intro: '告诉我房价，我会用你记录的 {n} 个月来检验，并告诉你哪些月份会不够。',
  tx_ctx: '最淡的月份剩 {lo} · 一般月份 {hi}',
  tx_house: '房子',
  tx_price: '房价',
  tx_dep: '首付',
  tx_dep_other: '其他',
  tx_inst: '每月供款',
  tx_loan: '{r}%，{y} 年',
  tx_other: '其他每月费用',
  tx_total: '每月总成本',
  tx_run: '开始测试',
  tx_known: '我已经知道每月供款',
  tx_known_lbl: '每月供款 (RM)',
  tx_back_price: '改为按房价计算',
  tx_loan_t: '贷款详情',
  tx_costs_t: '其他每月费用',
  tx_costs_h: '维修、保险等。估算即可，随时可以修改。',
  rx_ok_t: '{n} 个月都负担得起',
  rx_ok: '这套房每月 {c}，在每个记录月份都撑得住。',
  rx_warn_t: '{n} 个月中有 {s} 个月会不够',
  rx_warn: '在{months}，每月 {c} 会让你不够用。最大缺口 {g}。',
  rx_bad: '大部分记录月份都负担不起每月 {c}。最大缺口 {g}。',
  rx_leg_bar: '扣除工作成本和固定支出后每月剩下的钱',
  rx_leg_line: '这套房的每月成本',
  rx_leg_gap: '缺口',
  rx_try_t: '房屋每月成本 · 什么才可行',
  rx_try: '你已记录的月份约能承担每月 {p}。',
  rx_try_ok: '你在每个记录月份都能承担的范围内。',
  rx_try_btn: '试试 {p}',
  rx_trying: '正在测试 {p}，而不是这套房的 {c}。',
  rx_use_home: '回到这套房',
  rx_drop: '如果收入下降',
  rx_keep: '保存测试',
  rx_change: '修改房子',
  rx_how: '这是怎么算的',
  sp_title: '你要扫描什么？',
  sp_in_h: '收入页面或结算截图',
  sp_out_h: '收据或账单',
  cvr_ok_t: '你的记录已涵盖淡季月份',
  cvr_ok: '{slow}都在 {a} 至 {b} 之间，房屋测试已经把它们算进去了。',
  cvr_gap_t: '你的记录还没见过{m}',
  cvr_gap: '你说{m}通常较淡，但你的记录只有 {a} 至 {b}。在那之前，测试结果可能比真正的淡季看起来更好。',
  cvr_gap_do: '继续记录到{m}。测试会自动把这些月份算进去。',
  cvr_flat_t: '每个月同等看待',
  cvr_info_t: '这对测试意味着什么',
  cvr_pick_hint: '选出所有通常较淡的月份。',
  ex_limit_of: '{v}，你的每月上限 {l}',
  ex_edit_limit: '修改上限',
  ex_set_limit: '设定每月上限',
  ex_limit_title: '每月开销上限',
  ex_limit_hint: '你希望每月日常开销控制在多少以内。不会阻止任何操作，进度条只是显示你用了多少。',
  ex_limit_saved: '每月上限已更新。',
  ex_q_amt: '你花了多少？',
  ex_q_cat: '用在什么上？',
  ex_recent: '最近开销',
  ex_oflimit: '{v}，上限 {l}',
  xe_title: '编辑开销',
  xe_del: '删除开销',
  xe_save: '保存更改',
  xe_saved: '开销已更新。',
  xe_deleted: '开销已删除。',
  exc_hint: '从银行或电子钱包导出 .csv 文件，然后在这里选择。',
  exc_cat: '这些记录的类别',
  exc_done: '已添加 {n} 笔开销，{a} 至 {b}。',
  io_in: '收入',
  io_out: '支出',
  ht_title: '房屋测试',
  ht_rec: '已记录 {n} 个月 · {a} 至 {b}',
  ht_short: '{n} 个月中有 {s} 个月会不够',
  ht_ok: '{n} 个月都负担得起',
  ht_gap: '最大缺口 {g}',
  ht_go: '测试',
  ht_rego: '重新测试',
  ht_open: '打开测试',
  mo_sofar: '{m} 至今',
  mo_in: '收入',
  mo_out: '支出',
  mo_left: '结余',
  mo_fixed: '本月已记录的收入和日常开销。',
  mo_quiet: '你的淡季月份',
  mo_quietest: '最淡',
  mo_usual: '一般',
  mo_quiet_note: '扣除工作成本和固定支出后的剩余结余。房屋测试以淡季月份为准。',
  mo_trend: '扣除工作成本后的收入，最近 {n} 个月',
  mo_permo: '/ 月',
  mo_pace: '开销进度',
  mo_pace_note: '{v}，上限 {l} · 第 {d} 天，共 {n} 天',
  mo_nolimit: '未设上限',
  mo_rec: '记录',
  mo_setup: '设置',
  mo_insights: '洞察',
  perx_day: '每日',
  perx_week: '每周',
  perx_month: '每月',
  inc_for: '这笔金额是',
  inc_weekend: '周结束日',
  inc_monthof: '哪个月？',
  ie_title: '编辑记录',
  ie_save: '保存更改',
  ie_saved: '记录已更新。',
  ie_deleted: '记录已删除。',
  ie_del: '删除记录',
  im_type: '手动',
  im_scan: '扫描',
  im_csv: '导入',
  sc_hint: '支持 Grab、foodpanda 和 Lalamove 的收入页面。',
  sc_pick: '拍照或选择截图',
  sc_sample: '试试示例',
  sc_reading: '正在读取你的收入…',
  sc_found: '找到 {n} 条记录。不需要的可以取消勾选。',
  sc_low: '识别把握较低，请检查',
  sc_add: '添加 {n} 条记录',
  sc_added: '已从扫描添加 {n} 条记录。',
  sc_tag: '扫描',
  cv_hint: '从平台或银行导出 .csv 文件，然后在这里选择。',
  cvi_pick: '选择 .csv 文件',
  cv_tpl: '下载模板',
  cv_sample: '试试示例文件',
  cv_map: '检查列',
  cv_date: '日期',
  cv_amt: '金额',
  cv_desc: '描述',
  cv_src: '这些记录的来源',
  cv_fromdesc: '按描述归类',
  cv_import: '导入 {n} 行',
  cv_done: '已添加 {n} 条记录，{a} 至 {b}。',
  cv_skipped: '跳过 {n} 条重复。',
  cv_none: '没有可用的行。请检查日期和金额列。',
  cv_tag: 'CSV',
  inc_q_amt: '你赚了多少？',
  inc_q_when: '什么时候？',
  inc_q_src: '来自哪里？',
  inc_today: '今天',
  inc_yday: '昨天',
  inc_pick: '选择日期',
  inc_recent: '最近记录',
  inc_sofar: '{m} 至今：{v}',
  hm_togo: '距离你的首付现金估算还差 {g}',
  hm_ready: '你的首付现金估算已足够',
  hd_morning: '早上好',
  hd_afternoon: '下午好',
  hd_evening: '晚上好',
  hd_welcome: '欢迎！',
  hd_guest: '欢迎，访客',
  ai_title: '问问 RuMampu',
  ai_hi: '嗨！可以问我关于你的记录、储蓄计划，或你想买的房子。我只根据你自己的数字回答。',
  ai_q1: '我买得起 RM 250k 的房子吗？',
  ai_q2: '我的储蓄计划进展如何？',
  ai_q3: '我花得最多的是什么？',
  ai_ph: '输入问题',
  ai_send: '发送',
  ai_a_afford: '扣除工作成本和固定支出后，你收入较慢的月份大约每月能承担 {m}。运行房屋测试可以得到完整答案。',
  ai_a_plan: '本月你已存 {s}，目标 {t}，{n} 天中完成了 {d} 天。今天的金额是 {a}。',
  ai_a_spend: '{mo} 你花得最多的是{c}：{v}。',
  ai_a_default: '我只根据你自己的记录回答，绝不虚构。试试下面的问题。',
  vl_score: '分数',
  vl_bestscore: '最高',
  vl_moves: '步数',
  vl_short: '滑动，让村庄成长。',
  vl_how: '玩法说明',
  vl_s1: '每存一天，就会在地块上多一间小屋。',
  vl_s2: '向左、右、上或下滑动，所有房子都会朝那个方向移动。',
  vl_s3: '两间相同的房子碰在一起，就会合并成更大的一间。',
  vl_s4: '一路升级：小屋、甘榜屋、排屋、公寓，最后是皇宫。',
  vl_s5: '存满十六天，就足够盖一座皇宫。',
  vl_start: '开始吧！',
  vl_sub: '迷你 2048 小游戏：滑动移动房子，两间相同的会合并成更大的。',
  vl_play: '开始玩',
  vl_done: '完成',
  vl_daily: '每日计划',
  vl_title: '储蓄村庄',
  vl_houses: '{n} 栋房子',
  vl_builtn: '已建 {b} 栋',
  vl_onplot: '地块上 {n} 栋',
  vl_best: '最高：{t}',
  vl_hint: '每存一天就多一间小屋。把两间相同的房子滑到一起，就能盖更大的。',
  vl_built: '你盖了一栋{t}！',
  vl_t1: '小屋',
  vl_t2: '甘榜屋',
  vl_t3: '排屋',
  vl_t4: '公寓',
  vl_t5: '皇宫',
  pl_title: '储蓄计划',
  pl_target: '每月目标',
  pl_today: '今天',
  pl_save_today: '今天存入',
  pl_saved_today: '已存 ✓',
  pl_progress: '已存 {s}，目标 {t}',
  pl_days: '{n} 天中已完成 {d} 天',
  pl_hint: '每天存一个不同的小数目，到月底就能达到目标。',
  pl_shuffle: '重新打乱剩余天数',
  pl_reached: '目标达成！',
  pl_note: '点一下某天即可标记已存。每个已存的日子都会加入你的总余额。更改目标只会重新分配尚未存入的日子。',
  pl_toast: '今天存入 {a}，总余额现为 {c}。',
  pl_untoast: '已取消今天的 {a}。',
  k_hi: '你好！',
  k_intro: '开始之前，我们有几个简短的问题',
  k_begin: '开始',
  k_next: '下一步',
  k_j_taxi: '电召车',
  k_j_bar: '调酒师',
  k_own: '自己添加',
  k_own_h: '你的工作名称',
  hm_saving: '总余额',
  hm_mysav: '我的余额',
  hm_income: '收入',
  hm_exp: '开销',
  tab_profile: '我的',
  pf_title: '我的',
  pf_guest_t: '访客模式',
  pf_guest: '你的记录可能会继续保留在此浏览器/设备上。不会创建 RuMampu 账号。',
  pf_create: '注册账户',
  pf_signed_t: '已登录',
  pf_signed: '你的记录会保留到下次。',
  pf_lang: '语言',
  pf_export: '导出我的记录',
  pf_export_done: '记录导出已准备好。',
  pf_export_failed: '记录导出失败。请重试。',
  pf_delete: '删除账户和记录',
  pf_delete_guest: '删除访客记录',
  pf_delete2: '再点一次确认删除',
  pf_delete_confirm: '再点一次删除，将永久移除此账户和记录。',
  pf_delete_guest_confirm: '再点一次删除，将永久移除此访客记录。',
  pf_delete_done: '记录已删除。',
  pf_delete_failed: '无法删除记录。请重试。',
  pf_prepare: '为买房做准备',
  qk_title: '你想添加什么？',
  qk_income: '收入',
  qk_expense: '开销',
  qk_scan: '扫描收据',
  k_title: '认识一下你',
  k_skip: '跳过',
  k_q1: '你做什么工作？',
  k_q1h: '可多选。这些将成为你的收入来源。',
  k_q2: '上个月你赚了多少？',
  k_q2h: '一个大概数字就够了。可选填。',
  k_ph: '例如 3,000',
  k_go: '开始使用 RuMampu',
  k_j_ehail: '电召车',
  k_j_deliv: '送餐',
  k_j_free: '自由职业',
  k_j_part: '兼职',
  k_j_stall: '小生意',
  k_j_other: '其他',
  k_saved: '你的记录已经开始。一切都可以修改。',
  wf_step: '第 {n} 步，共 3 步',
  wf_langq: '哪种语言让你最自在？',
  wf_next: '下一步',
  wf_hi: '嗨，我是 Ruma！',
  wf_blend: '<b>RuMampu</b> 取自 <i>rumah</i>（房子）和 <i>mampu</i>（负担得起）：我买得起房吗？',
  wf_f1t: '真实记录',
  wf_f1d: '记下你的收入和开销',
  wf_f2t: '房屋测试',
  wf_f2d: '我用你记录的收支来检验你想要的房子',
  wf_f3t: '隐私优先',
  wf_f3d: '你的数字只属于你，绝不虚构',
  wf_copy: '© 2026 RuMampu · Cendol Compiler 出品 · 马来西亚制造，为收入不稳定的人而生 · SDG 11',
  wf_meet: '很高兴认识你 →',
  au_hello: '你好！',
  au_create: '注册账户',
  au_ctag: '保存记录，下次继续。',
  au_login: '登录',
  au_email: '邮箱',
  au_pw: '密码',
  au_show: '显示',
  au_hide: '隐藏',
  au_eph: 'name@example.com',
  au_pph: '你的密码',
  au_p8: '至少 8 个字符',
  au_cpw: '确认密码',
  au_again: '再输入一次',
  au_mix: '请混合使用字母和数字。',
  au_mailhow: '我们如何使用你的邮箱',
  au_forgot: '忘记密码？',
  au_or: '或继续使用',
  au_google: '使用 Google 继续',
  au_new: '新用户？',
  au_createbtn: '注册账户',
  au_createacct: '注册账户',
  au_guest: '以访客身份继续',
  au_guest2: '改以访客身份继续',
  au_guestnote: '你的记录可能会继续保留在此浏览器/设备上。不会创建 RuMampu 账号。',
  au_mailonly: '你的邮箱仅用于登录和重置密码。',
  au_have: '已有账户？',
  au_backlogin: '← 返回登录',
  au_mailhow_t: '你的邮箱仅用于登录和发送重置链接，别无他用。',
  au_forgot_t: '密码重置流程（设计示意）。',
  home_rec: '你已记录 {n} 个月的收入。',
  home_rec_thin: '{n} 个月的记录还很薄。每多记一笔，测试就多看到一点。',
  home_test: '测试一套房',
  home_retest: '重新测试这套房',
  headline: '在已记录的 {n} 个月中，{s} 个月的钱不够。',
  headline_zero: '已记录的 {n} 个月都够付这笔成本。',
  gap_lbl: '最大缺口',
  covspan: '已记录 {a} 至 {b}',
  cov_unchecked: '淡季月份尚未设定',
  cov_missed: '你的记录还没见过{m}。你说那时通常较慢。',
  money_income: '收入',
  money_workcosts: '工作开销',
  money_commit: '固定开支',
  money_pattern: '收入形态',
  money_coverage: '淡季月份',
  net_lbl: '扣除工作开销后的收入',
  per_month: '/ 月，平均',
  inc_empty: '先记上周的收入，就足够开始了。',
  inc_amount: '金额 (RM)',
  inc_date: '日期',
  inc_source: '来源',
  inc_add: '添加收入',
  inc_neg: '低于零的金额无法保存。',
  inc_outlier: '比你平常的记录高很多。保留吗？',
  src_ehail: '电召车',
  src_freelance: '自由接单',
  src_parttime: '兼职（固定）',
  src_own: '＋自定来源',
  src_name: '来源名称',
  entry_saved: '已记录',
  wc_petrol: '汽油',
  wc_service: '车辆保养',
  wc_platform: '平台抽成',
  wc_data: '手机流量',
  wc_roadtax: '路税与车险',
  wc_own: '＋自定开销',
  wc_note: '之后每个页面都用这个数字。',
  cm_living: '生活开销',
  cm_debts: '还债',
  cm_savings: '储蓄',
  cm_rent: '房租',
  cm_food: '伙食',
  cm_util: '水电',
  cm_motor: '摩托车贷款',
  cm_ptptn: 'PTPTN',
  cm_family: '家用',
  cm_save: '每月储蓄',
  cm_total: '固定开支合计',
  pt_avg: '平均',
  pt_med: '中位',
  pt_high: '最高',
  pt_low: '最低',
  pt_range: '每月上下 RM {x}',
  pt_quietx: '记录中最淡的月份是 {m}：扣除工作成本后 {v}。',
  pt_namex: '你可以在{L}中标记你通常收入较少的月份。',
  tx_price_ph: '例如 250,000',
  tx_need_price: '请先输入房价。价格由你提供。',
  au_demo: '演示',
  rx_tryres: '按 {p} 计算，{n} 个月中有 {s} 个月会不够。',
  rc_live_guest: '每加一笔，所有页面即时更新。你的记录可能会继续保留在此浏览器/设备上。不会创建 RuMampu 账号。',
  rc_live_acct: '每加一笔，所有页面即时更新。已登录：你的记录会保留到下次。',
  pt_none: '没有记录月低于这条线。',
  pt_some: '低于这条线的：{m}。',
  cv_q: '一年中，有没有你通常赚得较少的时候？',
  cv_yes: '有',
  cv_no: '没有',
  cv_notsure: '不确定',
  cv_pick: '点选通常较慢的月份。',
  cv_unseen: '你说{slow}通常较慢。你的记录覆盖 {a} 到 {b}，这次测试还没见过慢月份。',
  cv_seen: '你说{slow}通常较慢。你的记录覆盖 {a} 到 {b}，慢月份已在其中。',
  cv_narrow: '你记录的数字彼此过于接近。较弱的月份可能没被记到。',
  cv_varied: '你记录的数字每月不同。但测试仍只认识 {a} 到 {b}。',
  cv_note: '多记几个月有用的前提，是记到对的月份。',
  th_title: '这套房',
  th_price: '房价 (RM)',
  th_fin: '贷款额',
  th_dep: '头期 (RM)',
  th_dep0: 'RM 0 也可以，有 100% 贷款。',
  th_rate: '年利率 (%)',
  th_ten: '年期（年）',
  th_inst: '每月供款',
  th_known: '我已知道每月供款',
  th_knownamt: '每月供款 (RM)',
  th_next: '每月总成本',
  tc_title: '每月总成本',
  tc_point: '供款不等于全部成本。',
  tc_inst: '供款',
  tc_break: '包含哪些',
  tc_run: '开始测试',
  hc_maint: '管理费与储备金',
  hc_insure: '房屋保险',
  hc_assess: '门牌税',
  hc_quit: '地税',
  hc_parking: '车位',
  hc_other: '其他',
  pc_title: '还没算房子之前',
  pc_msg: '在收入最清淡的 {m}，收入比日常开销少了 RM {x}，还没算任何房屋成本。',
  pc_msg2: '再加上房屋支出，无论房价多少，每个月都会不够。先看看收入和开销，测试随时可以再来。',
  pc_btn: '去收支',
  rs_title: '结果',
  rs_how: '这是怎么算的',
  rs_how_body: '每根柱是一个记录月：扣除工作开销的收入，再减固定开支。横线是每月房屋总成本 RM {c}。柱子够不到线，该月就算短缺。',
  rs_limit_slow: '这次测试还没见过你说通常较慢的{m}。下面的计数还没包含那段较慢的日子。',
  rs_limit_thin: '只记录了 {n} 个月，还不足以让这个计数有分量。',
  rs_range: '承担区间',
  rs_compare: '比较付款',
  rs_shock: '如果收入下降',
  rg_lead: '你记录的月份承担过每月 RM {a} 至 RM {b} 的付款。',
  rg_how: '两端是什么意思',
  rg_how_body: 'RM {a}：每个记录月都够。RM {b}：一半的月份够。',
  rg_price: '按 {r}%、{y} 年计，约合房价 RM {p} 至 RM {q}。',
  rg_pin: '你的测试',
  rg_ind: '仅供参考。不是估价，也不是要约。',
  cp_note: '同样的记录月份，三种付款。',
  cp_short: '{n} 个月中 {s} 个短缺',
  cp_gap: '最大缺口 RM {g}',
  cp_pay: '付款 {i} (RM)',
  sh_note: '只是对已记录月份的假设，不是对将来的判断。',
  sh_custom: '自定',
  sh_pct: '下降 (%)',
  sh_head: '按 −{p}% 计：{n} 个记录月中 {s} 个不够。',
  pr_upfront: '购房现金',
  pr_buffer: '现金缓冲',
  pr_docs: '文件与融资',
  pr_pv: '第 3 迭代预览',
  pr_pv_note: '买房之后。仅展示方向，尚未上线。',
  uf_have: '你有',
  uf_need: '需要',
  uf_gap: '缺口',
  uf_dep: '头期',
  uf_legal: '律师费',
  uf_stampT: '印花税（过户）',
  uf_stampL: '印花税（贷款）',
  uf_val: '估价费',
  uf_disb: '杂项支出',
  uf_move: '搬家',
  uf_basic: '基本家当（冰箱、床、窗帘）',
  uf_dep0: '头期 RM 0：购房现金是各项费用和安家，不是头期。',
  bf_def: '让你撑过记录中短缺的月份、且不跌破零，开头所需的最小金额。',
  bf_basis: '来自你自己 {a} 到 {b} 的记录，不是通用规则。',
  bf_zero: '按这套房算，你记录的月份从未跌破零。得数是 RM 0。',
  bf_bal: '逐月滚动余额',
  dc_bank: '银行月结单，6 个月',
  dc_ehail: '电召车收入摘要',
  dc_statdec: '收入法定声明',
  dc_epf: 'EPF 公积金结单',
  dc_commitlist: '现有开支清单',
  dc_sjkp: 'SJKP 公布的条件',
  dc_sj1: '马来西亚公民，18 至 70 岁',
  dc_sj2: '总收入在 SJKP 公布的上限内',
  dc_sj3: '首套房',
  dc_src: '来源：sjkp.com.my，2026 年 8 月',
  dc_65: '65% 核对：待复核',
  dc_65_note: 'SJKP 按总收入计，RuMampu 按扣除工作开销后的收入计。在厘清之前，这里不显示通过或不通过。',
  dc_plain: 'RuMampu 不会替你申请，也无法告诉你银行是否点头。',
  pv_banner: '第 3 迭代预览',
  pv_switch: '切换模式',
  pv_switch_btn: '我已买下这套房',
  pv_switch_note: '估算换成实际数字。购买本身在 RuMampu 之外完成。',
  pv_month: '本月',
  pv_in: '实际收入',
  pv_out: '实际房屋支出',
  pv_left: '剩余现金',
  pv_shortby: '短缺',
  pv_then: '先前测试 vs 实际情况',
  pv_then_a: '先前测试：{n} 个记录月中 {s} 个短缺。',
  pv_then_b: '买房后：头 {n2} 个月中 {s2} 个短缺。',
  pv_then_why: '先前的记录里没有年末月份，买房后遇上了两个。',
  see_pattern: '收入形态',
  see_coverage: '覆盖检查',
  money_record: '记录档案',
  rc_months: '已记录 {n} 个月',
  rc_entries: '{e} 笔，最近 {d}',
  rc_tests: '留存的测试',
  rc_none: '还没有留存的测试。到测试页跑一次。',
  rc_live: '你的财务记录可能会继续保留在此浏览器/设备上。它关联的是匿名访客 ID，不是 RuMampu 账号。',
  rc_keep_line: '每多记一周，下一次测试就多一点你真实的月份。',
  rs_keep: '留存这次测试',
  rs_kept: '已留存',
  entry_saved_n: '已记录。你现在有 {n} 条收入记录。',
  inc_past: '补记过去的月份',
  inc_past_hint: '那个月一个总数就够。',
  pt_bymonth: '逐月',
  pv_keep: '买房后继续记录，同一份记录继续发挥作用。',
  money_expenses: '每日记账',
  ex_sofar: '{m} 至今',
  ex_days: '已记录 {d} 天',
  ex_add: '记一笔',
  ex_scan: '扫描收据',
  ex_preview: '预览',
  ex_bycat: '按类别',
  xc_meals: '吃饭',
  xc_groc: '日用采买',
  xc_transp: '过路费与停车',
  xc_family: '家用',
  xc_other: '其他',
  xc_own: '＋自定类别',
  ex_saved: '已记下。{m} 至今：RM {x}。',
  ex_rule: '记满 20 天，当月才算记录完整。这是 RuMampu 自己的规则。',
  ex_feeds: '{m} 用了你记录的开销 RM {x}，代替伙食和家用的估算。',
  ex_scan_pick: '拍摄或选择收据照片。',
  ex_scan_sample: '用示例收据',
  ex_reading: '正在读取收据……',
  ex_check: '从收据读到的内容，保存前请核对。',
  ex_merchant: '商家',
  ex_total: '总额 (RM)',
  ex_retake: '重拍',
  ex_fromr: '来自收据',
  ex_cat: '类别',
  ex_monthly: '按月汇总',
  ex_see_sum: '查看按月汇总',
  ex_set_lims: '设置消费上限',
  ex_full: '记录完整',
  ex_used: '已用于测试',
  ex_partial: '记录 {d} 天，其余未知',
  ex_limits: '消费上限',
  lm_note: '每月上限由你自己设定，RuMampu 只负责计数。',
  lm_total: '整月',
  lm_limit: '上限 (RM)',
  lm_left: '还剩 RM {x}',
  lm_over: '超出上限 RM {x}',
  lm_none: '未设上限',
  hb_spend: '开销 · {m}',
  hb_income: '收入 · {m}',
  /* App-only keys (backend sync/error copy) kept from the previous build. */
  retry: '重试',
  home_rec_one: '你已记录 1 个月的收入。',
  home_rec_thin_one: '1 个月的记录还很薄。每多记一笔，测试就多看到一点。',
  inc_sync_loading: '正在载入已保存的收入记录……',
  inc_sync_error: '无法连接已保存的记录，请检查后端后重试。',
  inc_invalid_date: '请使用 YYYY-MM-DD 格式的有效日期。',
  inc_invalid_amount: '请输入有效金额，只能使用数字，并且最多保留 2 位小数。',
  inc_save_failed: '收入保存失败，请重试。',
  inc_saving: '保存中……',
  wc_name: '工作成本名称',
  xc_name: '类别名称',
  wc_add: '添加工作成本',
  wc_category: '工作成本类别',
  wc_month: '月份',
  wc_month_note: '正在显示 {m}。请选择当前月或有记录的月份。',
  wc_income_formula: '{income} 收入 − {costs} 本月已记录工作成本。',
  wc_cost_total: '{costs} 是本月已记录的工作成本。',
  wc_no_income: '{m} 没有收入记录。请先添加收入，RuMampu 才能计算该数值。',
  wc_month_unavailable: '请选择当前月或有收入、工作成本记录的月份。',
  wc_entry_amount: '工作成本金额',
  wc_edit_amount: '编辑工作成本金额',
  wc_so_far: '本月截至目前的记录，不是预测值，也不代表完整月总额。',
  wc_no_costs: '本月尚无工作成本记录，并不代表本月没有发生工作成本。',
  wc_summary_unavailable: '最新记录加载完成前，暂不显示月度计算结果。',
  wc_recorded: '已记录工作成本',
  wc_empty: '尚未记录工作成本。',
  wc_entry_invalid: '请选择类别，并输入有效金额和日期。',
  wc_sync_loading: '正在加载工作成本…',
  wc_sync_error: '工作成本同步失败，请重试。',
  wc_save_failed: '工作成本保存失败，请重试。',
  cm_sync_loading: '正在加载固定开支…',
  cm_sync_error: '固定开支同步失败，请重试。',
  cm_save_failed: '固定开支保存失败，请重试。',
  pt_range_total: '记录范围',
  pt_std: '标准差',
  pt_month_count: '已记录 {n} 个月',
  pt_loading: '正在根据已保存记录计算收入形态……',
  pt_error: '无法获取计算后的收入形态；已保存收入没有发生改变。',
  pt_api_required: 'Epic 2 分析仅在后端 API 连接模式下可用。请设置 EXPO_PUBLIC_APP_MODE=api 并启动后端。',
  pt_empty: '记录一个月份后，收入形态就会开始形成。',
  pt_empty_note: '添加收入后，即可逐月查看可用收入。',
  pt_add_income: '添加收入',
  pt_limited_one: '目前只有一个记录月。这里显示该月的事实，但还不能描述更广泛的形态。',
  pt_limited_two: '目前有两个记录月。数字是事实，但可见历史仍然有限。',
  pt_work_basis: '每个记录月只使用该月自身带日期的工作成本记录。',
  pt_rule: '这里的较低收入月，是当前记录中可用收入最低的月份；它不是金融标准，也不是预测。',
  cv_loading: '正在载入已保存的覆盖回答……',
  cv_error: '覆盖回答加载或保存失败；重试不会丢失上一次已确认回答。',
  cv_check: '检查覆盖情况',
  cv_checking: '检查中……',
  cv_select_required: '请至少选择一个慢月份。',
  cv_save_failed: '覆盖回答保存失败，请重试。',
  cv_represented: '收入记录已经覆盖：{m}。',
  cv_unrepresented: '收入记录尚未覆盖：{m}。',
  cv_observation: '在 {n} 个记录月中，可用收入介于 {lo} 与 {hi}，范围为 {range}。这些事实无法确认通常较慢的时期是否具有代表性。',
  cv_api_required: '覆盖检查仅在后端 API 连接模式下可用。请设置 EXPO_PUBLIC_APP_MODE=api 并启动后端。',
  cv_no_history: '目前没有可用于比较的收入记录月。',
  cv_previous: '下方结果是服务器上一次确认的回答；你的新选择尚未保存。',
  tc_inst_desc: '根据你的贷款资料',
  housing_running: '正在计算…',
  housing_run_failed: '住房计算未能完成，请重试。',
  housing_result_required: '请先运行住房测试，以便此页面使用服务器计算的结果。',
  hc_maint_desc: '用于维修和保养',
  hc_insure_desc: '基本房屋保险',
  hc_assess_desc: '缴付给地方政府',
  hc_quit_desc: '土地租金（如适用）',
  hc_parking_desc: '每月停车费用',
  hc_other_desc: '其他经常性费用',
  rs_shortfall_breakdown: '短缺来自哪里',
  rs_existing_shortfall: '还没算房屋成本前已经短缺',
  rs_housing_shortfall: '因为这套房才出现短缺',
  rs_shortfall_breakdown_note: '现有短缺是加入房屋成本前已经低于零的月份。房屋造成的短缺则是加入这次测试的房屋成本后才变成负数的月份。',
  cp_price: '每月 RM {payment} ≈ 房产价值 RM {price}',
  cp_price_note: '仅供参考，按这次测试输入的利率、年限和首付计算。',
  sh_disclaimer: '假设情景，并非预测。',
  pr_coming: '即将推出',
  pr_coming_note: '此部分正在建设中。',
  rc_months_one: '已记录 1 个月',
  rc_summary: '财务记录',
  rc_month_metric: '已记录月份',
  rc_month_metric_one: '已记录月份',
  rc_entry_metric: '财务记录',
  rc_latest_label: '最近记录',
  rc_latest: '最近记录日期：{d}',
  rc_latest_empty: '还没有带日期的收入或支出记录。',
  rc_none_title: '还没有留存的测试',
  rc_none_body: '运行一次住房测试，并把结果留存在这里供本次会话查看。',
  rc_test_action: '前往测试',
  rc_about: '关于你的记录',
  rc_test_session: '仅在本次会话中留存。',
  rc_pay_month: '{p} / 月',
  rc_short_label: '短缺月份',
  rc_short_value: '{n} 个月中 {s} 个',
  rs_keep_hint: '把这个结果加入记录档案，仅供本次会话查看。',
  rs_kept_session: '仅在本次会话中留存。',
  inc_recorded: '已记录收入',
  inc_past_no_min: '有多少历史就补多少，不要求至少 6 或 12 个月。',
  inc_past_month: '历史月份 (YYYY-MM)',
  inc_past_invalid: '请输入早于本月的有效月份。',
  inc_past_exists: '这个月已有收入记录，请选择其他月份。',
  inc_past_amount: '请输入大于零的月收入总额。',
  inc_past_cash: '请输入有效金额，只能使用数字，并且最多保留 2 位小数。',
  inc_month_total: '整月总额',
  inc_import: '从 CSV 导入收入',
  imp_title: '导入收入',
  imp_intro: '请选择 CSV 文件。RuMampu 会先生成预览，确认前不会写入任何收入。',
  imp_format: '必填列：amount、date、source。日期必须早于今天，格式为 YYYY-MM-DD。',
  imp_select: '选择 CSV 文件',
  imp_reading: '正在读取文件……',
  imp_summary: '{name}：共 {total} 行',
  imp_ready: '{n} 行可导入',
  imp_attention: '{n} 行需要处理',
  imp_row: '第 {n} 行',
  imp_raw: '原始内容：{amount} · {date} · {source}',
  imp_confirm: '确认并添加 {n} 笔记录',
  imp_confirming: '正在添加记录……',
  imp_confirmed: '已添加 {n} 笔收入，分析结果已同步更新。',
  imp_failed: '收入文件处理失败，请检查 CSV 后重试。',
  imp_view_pattern: '查看收入形态',
  imp_no_ready: '没有可导入的有效行。',
  pt_chart_accessibility: '逐月计算后的可用收入',
  pt_scroll: '横向滚动可查看全部记录月份。',
  ex_days_one: '已记录 1 天',
  ex_empty: '尚未记录日常支出。',
  ex_sync_loading: '正在载入已保存的支出……',
  ex_sync_error: '支出同步失败，请重试。',
  ex_saving: '正在保存……',
  ex_amount_positive: '请输入大于零的金额。',
  ex_date_invalid: '请输入有效的日历日期。',
  ex_save_failed: '支出保存失败，请重试。',
  ex_take_photo: '拍摄照片',
  ex_choose_photo: '选择照片',
  ex_image_failed: '无法打开收据图片，请重试。',
  ex_scan_failed: '暂时无法读取收据。请重试，或改用手动记账。',
  ex_not_receipt: '这张照片看起来不是收据。请对着收据本身拍摄更清晰的照片。',
  ex_ai_suggested: 'AI 建议',
  ex_scan_partial: '收据上有些信息读不出来。请先补上空白的栏目再保存。',
  as_title: '问问 RuMampu',
  as_hint: '问问你的收支或某个结果……',
  as_send: '发送',
  as_empty: '可以问我关于你的收入、开销或购房测试结果。我只使用你记录过的内容。',
  as_thinking: '思考中……',
  as_error: '助手暂时无法回复，请重试。',
  as_limit: '助手已达到今日消息上限，明天再来吧。',
  as_disclaimer: '解释来自你自己的记录，不是理财建议。',
  ex_partial_one: '记录 1 天，其余未知',
},
};
