/* All user-facing copy in three languages — ported verbatim from the prototype. */

export type Lang = 'en' | 'ms' | 'zh';

export type StringTable = { langname: string; months: string[] } & Record<string, string | string[]>;

export const STRINGS: Record<Lang, StringTable> = {
en: {
  langname: 'English', months: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
  tab_home: 'Home', tab_money: 'Money', tab_test: 'Test', tab_prepare: 'Prepare',
  back: 'Back', add: 'Add', edit: 'Edit', done: 'Done', cancel: 'Cancel', keep: 'Keep', remove: 'Remove', retry: 'Retry',
  saved: 'Saved', unknown: 'Unknown', lang_pick: 'Language',
  prov_user: 'your data', prov_official: 'official', prov_calc: 'calculated', prov_assume: 'assumption',
  provf_user: 'User Data: a figure you entered yourself.',
  provf_official: 'Official Source: a published figure; source and date shown.',
  provf_calc: 'Derived Calculation: arithmetic on your own records. Nothing else added.',
  provf_assume: 'Stress-Test Assumption: an editable default, not a fact about you.',
  ob1: 'RuMampu checks how a home payment fits your quieter months, not just your average ones.',
  ob2: 'It lays the numbers out clearly. The decision is always yours.',
  ob3: 'Begin with whatever you have. Even one week of income is a good start.',
  ob_skip: 'Skip', ob_next: 'Next', ob_start: 'Start',
  ob_slogan: 'Let your real months do the counting.',
  home_rec: 'You have {n} months of income recorded.',
  home_rec_one: 'You have 1 month of income recorded.',
  home_rec_thin: '{n} months is a thin record. Every entry you add lets the test see more.',
  home_rec_thin_one: '1 month is a thin record. Every entry you add lets the test see more.',
  home_test: 'Test a house', home_retest: 'Re-test the house',
  headline: '{s} of your {n} recorded months would have run short.',
  headline_zero: 'None of your {n} recorded months would have run short.',
  gap_lbl: 'Largest gap',
  covspan: '{a} to {b} recorded',
  cov_unchecked: 'Coverage not checked yet',
  cov_missed: 'Your records haven’t seen {m} yet. You said it is usually slower.',
  money_income: 'Income', money_workcosts: 'Work costs', money_commit: 'Commitments',
  money_pattern: 'Income pattern', money_coverage: 'Coverage check',
  net_lbl: 'Income after work costs', per_month: '/ month, average',
  inc_empty: 'Add last week’s earnings. That’s enough to start.',
  inc_recorded: 'Recorded income',
  inc_amount: 'Amount (RM)', inc_date: 'Date', inc_source: 'Source', inc_add: 'Add income',
  inc_neg: 'An amount below zero can’t be saved.',
  inc_outlier: 'Well above your usual entries. Keep it?',
  inc_sync_loading: 'Loading your saved income record…',
  inc_sync_error: 'The saved record could not be reached. Check the backend and try again.',
  inc_invalid_date: 'Use a valid date in YYYY-MM-DD format.',
  inc_invalid_amount: 'Enter a valid cash amount using numbers only, with up to 2 decimal places.',
  inc_save_failed: 'Income could not be saved. Please try again.',
  inc_saving: 'Saving…',
  src_ehail: 'E-hailing', src_freelance: 'Freelance', src_parttime: 'Part-time (fixed)',
  src_own: '+ Your own source', src_name: 'Source name', entry_saved: 'Entry saved',
  wc_name: 'Work-cost name', xc_name: 'Category name',
  wc_petrol: 'Petrol', wc_service: 'Servicing', wc_platform: 'Platform fees', wc_data: 'Phone data', wc_roadtax: 'Road tax & insurance',
  wc_own: '+ Your own cost', wc_note: 'Every later screen uses this number.',
  wc_sync_loading: 'Loading your work costs…',
  wc_sync_error: 'Work costs could not be synced. Try again.',
  wc_save_failed: 'Work cost could not be saved. Please try again.',
  cm_living: 'Living costs', cm_debts: 'Debt repayments', cm_savings: 'Savings',
  cm_rent: 'Rent', cm_food: 'Food', cm_util: 'Utilities', cm_motor: 'Motor loan', cm_ptptn: 'PTPTN', cm_family: 'Family support', cm_save: 'Monthly savings',
  cm_total: 'Total commitments',
  cm_sync_loading: 'Loading your commitments…',
  cm_sync_error: 'Commitments could not be synced. Try again.',
  cm_save_failed: 'Commitment could not be saved. Please try again.',
  pt_avg: 'Average usable income', pt_med: 'Median', pt_high: 'Highest', pt_low: 'Lowest',
  pt_range_total: 'Recorded range', pt_std: 'Standard deviation',
  pt_month_count: '{n} recorded months',
  pt_loading: 'Calculating your income pattern from the saved record…',
  pt_error: 'The calculated income pattern could not be reached. Your saved income has not changed.',
  pt_api_required: 'Epic 2 analysis is available only in connected API mode. Set EXPO_PUBLIC_APP_MODE=api and start the backend.',
  pt_empty: 'Your income pattern starts with a recorded month.',
  pt_empty_note: 'Add income to see usable income month by month.', pt_add_income: 'Add income',
  pt_limited_one: 'This is one recorded month. It shows that month’s facts, but cannot yet describe a broader pattern.',
  pt_limited_two: 'This is two recorded months. The figures are factual, but the visible history is still limited.',
  pt_work_basis: 'Each recorded month uses the current monthly work-cost total of {x}.',
  pt_rule: 'A lower-income month here means the lowest usable-income month in your current record. It is not a financial standard or a prediction.',
  pt_none: 'Add another recorded month before comparing lower-income months.',
  pt_some: 'Lowest in your current record: {m}.',
  cv_q: 'Are there times of year when you usually earn less?',
  cv_yes: 'Yes', cv_no: 'No', cv_notsure: 'Not sure',
  cv_pick: 'Tap the months that are usually slower.',
  cv_loading: 'Loading your saved coverage answer…',
  cv_error: 'Coverage could not be loaded or saved. You can retry without losing the last confirmed answer.',
  cv_check: 'Check coverage', cv_checking: 'Checking…',
  cv_select_required: 'Choose at least one slower month.', cv_save_failed: 'Coverage could not be saved. Please retry.',
  cv_represented: 'Represented in your recorded income: {m}.',
  cv_unrepresented: 'Not yet represented in your recorded income: {m}.',
  cv_observation: 'Across {n} recorded months, usable income ranges from {lo} to {hi}, a spread of {range}. These facts cannot confirm whether your usual slower periods are represented.',
  cv_api_required: 'Coverage checking is available only in connected API mode. Set EXPO_PUBLIC_APP_MODE=api and start the backend.',
  cv_no_history: 'There are no recorded income months to compare yet.',
  cv_previous: 'The result below is the last server-confirmed answer. Your new selection has not been saved.',
  cv_note: 'More months only help if the right months are in there.',
  th_title: 'The house', th_price: 'Property price (RM)', th_fin: 'Financing amount', th_dep: 'Deposit (RM)',
  th_dep0: 'RM 0 is allowed. 100% financing exists.',
  th_rate: 'Rate (% / year)', th_ten: 'Tenure (years)', th_inst: 'Monthly instalment',
  th_known: 'I already know my monthly payment', th_knownamt: 'Monthly payment (RM)',
  th_next: 'Total monthly cost',
  tc_title: 'Total monthly cost', tc_point: 'The instalment is not the whole cost.',
  tc_inst: 'Loan payment (instalment)', tc_inst_desc: 'From your financing details', tc_break: 'What’s inside', tc_run: 'Run the test',
  housing_running: 'Calculating…',
  housing_run_failed: 'The housing calculation could not be completed. Please try again.',
  housing_result_required: 'Run the housing test first so this screen can use the server-calculated result.',
  hc_maint: 'Maintenance & sinking fund', hc_maint_desc: 'For repairs and upkeep', hc_insure: 'Home insurance', hc_insure_desc: 'Basic home insurance', hc_assess: 'Assessment tax', hc_assess_desc: 'Paid to local council', hc_quit: 'Quit rent', hc_quit_desc: 'Land rent (if applicable)', hc_parking: 'Parking', hc_parking_desc: 'Monthly parking cost', hc_other: 'Other', hc_other_desc: 'Any other recurring cost',
  pc_title: 'Before the house',
  pc_msg: 'In {m}, your quietest recorded month, income came in RM {x} below your everyday costs, before any home cost.',
  pc_msg2: 'A home payment on top would leave every month short, at any price. A quick look at income and costs first gives the test firmer ground.',
  pc_btn: 'Go to Money',
  rs_title: 'Result',
  rs_how: 'How this was worked out',
  rs_how_body: 'Each bar is one recorded month: income after work costs, minus commitments. The line is the total monthly home cost, RM {c}. A month runs short when its bar ends below the line.',
  rs_shortfall_breakdown: 'Where the shortfalls came from',
  rs_existing_shortfall: 'Already short before housing',
  rs_housing_shortfall: 'Became short because of this home',
  rs_shortfall_breakdown_note: 'Existing shortfalls were already below zero before the home cost was added. Housing-induced shortfalls are months that only became negative after this tested home cost was applied.',
  rs_limit_slow: 'This test hasn’t seen {m}, which you said is usually slower. The count below doesn’t include that quieter time of year yet.',
  rs_limit_thin: 'Only {n} months recorded. Not enough for this count to carry weight yet.',
  rs_range: 'Carrying range', rs_compare: 'Compare payments', rs_shock: 'If income drops',
  rg_lead: 'Your recorded months carried payments of RM {a} to RM {b} a month.',
  rg_how: 'What the two ends mean',
  rg_how_body: 'RM {a}: every recorded month covered it. RM {b}: half of them did.',
  rg_price: 'At {r}% over {y} years, that is about RM {p} to RM {q} in price.',
  rg_pin: 'your test',
  rg_ind: 'Indicative only. Not a valuation, not an offer.',
  cp_note: 'Same recorded months, three payments.',
  cp_price: 'RM {payment}/month ≈ RM {price} property value',
  cp_price_note: 'Indicative only, using the rate, tenure and deposit entered for this test.',
  cp_short: '{s} of {n} short', cp_gap: 'largest gap RM {g}', cp_pay: 'Payment {i} (RM)',
  sh_disclaimer: 'Hypothetical scenario, not prediction.',
  sh_note: 'Uses your recorded months only. It does not state what will happen in the future.',
  sh_custom: 'Custom', sh_pct: 'Drop (%)',
  sh_head: 'At −{p}%: {s} of {n} recorded months would have run short.',
  pr_upfront: 'Upfront cash', pr_buffer: 'Cash buffer', pr_docs: 'Documents & financing',
  pr_pv: 'Iteration 3 preview', pr_pv_note: 'After buying. Direction only, not shipping yet.',
  pr_coming: 'Coming soon', pr_coming_note: 'This section is under construction.',
  uf_have: 'You have', uf_need: 'You need', uf_gap: 'Gap',
  uf_dep: 'Deposit', uf_legal: 'Legal fees', uf_stampT: 'Stamp duty (transfer)', uf_stampL: 'Stamp duty (loan)', uf_val: 'Valuation', uf_disb: 'Disbursements', uf_move: 'Moving', uf_basic: 'Basics (fridge, bed, curtains)',
  uf_dep0: 'Deposit RM 0: upfront cash is fees and setting up, not the deposit.',
  bf_def: 'The smallest amount you’d have needed at the start to get through the short months in your record without going below zero.',
  bf_basis: 'From your own record, {a} to {b}. Not a general rule.',
  bf_zero: 'With this house, your recorded months never went below zero. The figure works out to RM 0.',
  bf_bal: 'Running balance by month',
  dc_bank: 'Bank statements, 6 months', dc_ehail: 'E-hailing earnings summary', dc_statdec: 'Statutory declaration of income', dc_epf: 'EPF statement', dc_commitlist: 'List of existing commitments',
  dc_sjkp: 'SJKP published criteria',
  dc_sj1: 'Malaysian citizen, age 18 to 70', dc_sj2: 'Gross income within SJKP’s published limit', dc_sj3: 'First home',
  dc_src: 'Source: sjkp.com.my, Aug 2026',
  dc_65: '65% check: needs review',
  dc_65_note: 'SJKP measures gross income; RuMampu measures income after work costs. Until that gap is settled, no pass or fail is shown here.',
  dc_plain: 'RuMampu does not apply for you and cannot tell you whether a bank will say yes.',
  pv_banner: 'Iteration 3 preview',
  pv_switch: 'Switch mode', pv_switch_btn: 'I’ve bought the home',
  pv_switch_note: 'Estimates become actuals. The purchase itself happens outside RuMampu.',
  pv_month: 'This month', pv_in: 'Actual income in', pv_out: 'Actual home costs out',
  pv_left: 'Cash left', pv_shortby: 'Short by',
  pv_then: 'Earlier test vs what happened',
  pv_then_a: 'Your earlier test: {s} short months out of {n} recorded.',
  pv_then_b: 'Since buying: {s2} of your first {n2} months have run short.',
  pv_then_why: 'The earlier record had no year-end month in it. Two arrived after buying.',
  see_pattern: 'Income pattern', see_coverage: 'Coverage check',
  // EN: Epic 8 Your Record localisation keys for US8.1 and US8.2 display copy.
  // 中文：Epic 8 “记录档案”本地化 key，用于 US8.1 和 US8.2 的展示文案。
  money_record: 'Your record',
  rc_months: '{n} months recorded',
  rc_months_one: '1 month recorded',
  rc_summary: 'Financial record',
  rc_month_metric: 'months recorded',
  rc_month_metric_one: 'month recorded',
  rc_entry_metric: 'financial entries',
  rc_entries: '{e} financial entries',
  rc_latest_label: 'Latest entry',
  rc_latest: 'Latest recorded entry: {d}',
  rc_latest_empty: 'No dated income or expense entries yet.',
  rc_tests: 'Kept housing tests',
  rc_none: 'No test kept yet. Run one from the Test tab.',
  rc_none_title: 'No test kept yet',
  rc_none_body: 'Run a housing test and keep the result here for this session.',
  rc_test_action: 'Go to Test',
  rc_live: 'Your record is available only in your current guest session on this browser or device. It is not saved to a RuMampu account.',
  rc_about: 'About your record',
  rc_keep_line: 'Every new week you record gives the next test more of your real months.',
  rc_test_session: 'Kept for this session.',
  rc_pay_month: '{p} / month',
  rc_short_label: 'Short months',
  rc_short_value: '{s} of {n}',
  // EN: Epic 8 Keep This Test action/status copy shown from the housing Result screen.
  // 中文：Epic 8 “留存这次测试”的操作与状态文案，显示在住房测试结果页。
  rs_keep: 'Keep this test', rs_keep_hint: 'Add this result to Your record for this session.', rs_kept: 'Test kept', rs_kept_session: 'Kept for this session.',
  entry_saved_n: 'Entry saved. The analysis now uses {n} months.',
  inc_past: 'Add a past month',
  inc_past_hint: 'One total for that month is enough.',
  inc_past_no_min: 'Add whatever history you have. There is no 6 or 12 month minimum.',
  inc_past_month: 'Past month (YYYY-MM)',
  inc_past_invalid: 'Enter a valid month earlier than the current month.',
  inc_past_exists: 'That month already has income records. Choose another month.',
  inc_past_amount: 'Enter a total greater than zero.',
  inc_past_cash: 'Enter a valid cash amount using numbers only, with up to 2 decimal places.',
  inc_month_total: 'Monthly total',
  inc_import: 'Import income from CSV',
  imp_title: 'Import income',
  imp_intro: 'Choose a CSV file. RuMampu will prepare a preview before anything is added.',
  imp_format: 'Required columns: amount, date, source. Dates must be historical and use YYYY-MM-DD.',
  imp_select: 'Select CSV file',
  imp_reading: 'Reading file…',
  imp_summary: '{name}: {total} rows',
  imp_ready: '{n} ready',
  imp_attention: '{n} need attention',
  imp_row: 'Row {n}',
  imp_raw: 'Original: {amount} · {date} · {source}',
  imp_confirm: 'Confirm and add {n} records',
  imp_confirming: 'Adding records…',
  imp_confirmed: '{n} income records added. Your analyses now use them.',
  imp_failed: 'The income file could not be processed. Check the CSV and try again.',
  imp_view_pattern: 'View income pattern',
  imp_no_ready: 'No valid rows are ready to add.',
  pt_bymonth: 'Month by month',
  pt_chart_accessibility: 'Month-by-month calculated usable income',
  pt_scroll: 'Scroll horizontally to see all recorded months.',
  pv_keep: 'Keep recording after buying. The same record keeps working.',
  money_expenses: 'Daily expenses',
  ex_sofar: '{m} so far', ex_days: '{d} days recorded', ex_days_one: '1 day recorded',
  ex_empty: 'No daily expenses recorded yet.',
  ex_add: 'Add expense', ex_scan: 'Scan a receipt', ex_preview: 'Preview',
  ex_sync_loading: 'Loading your saved expenses…', ex_sync_error: 'Expenses could not be synced. Try again.',
  ex_saving: 'Saving…', ex_amount_positive: 'Enter an amount greater than zero.',
  ex_date_invalid: 'Enter a valid calendar date.', ex_save_failed: 'The expense could not be saved. Try again.',
  ex_bycat: 'By category',
  xc_meals: 'Meals', xc_groc: 'Groceries', xc_transp: 'Tolls & parking', xc_family: 'Family', xc_other: 'Other', xc_own: '+ Your own category',
  ex_saved: 'Saved. {m} so far: RM {x}.',
  ex_rule: 'A month counts as fully recorded from 20 logged days. RuMampu’s own rule.',
  ex_feeds: '{m} used your recorded expenses, RM {x}, in place of the food and family estimate.',
  ex_scan_pick: 'Take or choose a photo of the receipt.',
  ex_take_photo: 'Take a photo', ex_choose_photo: 'Choose a photo',
  ex_image_failed: 'The receipt image could not be opened. Try again.',
  ex_scan_sample: 'Use a sample receipt',
  ex_reading: 'Reading the receipt…',
  ex_check: 'Read from your receipt. Check it before saving.',
  ex_merchant: 'Shop', ex_total: 'Total (RM)', ex_retake: 'Retake', ex_fromr: 'from receipt', ex_cat: 'Category',
  ex_monthly: 'Monthly summary',
  ex_full: 'fully recorded', ex_used: 'used in the test',
  ex_partial: '{d} days, rest of month unknown', ex_partial_one: '1 day, rest of month unknown',
  ex_limits: 'Spending limits',
  lm_note: 'The limits are yours to set. RuMampu only counts.',
  lm_total: 'Whole month', lm_limit: 'Limit (RM)',
  lm_left: 'RM {x} left',
  lm_over: 'RM {x} past your limit',
  lm_none: 'no limit set',
  hb_spend: 'Spending · {m}', hb_income: 'Income · {m}'
},
ms: {
  langname: 'Bahasa Melayu',
  months: ['Jan','Feb','Mac','Apr','Mei','Jun','Jul','Ogo','Sep','Okt','Nov','Dis'],
  tab_home: 'Rumah',
  tab_money: 'Duit',
  tab_test: 'Cuba',
  tab_prepare: 'Sediakan',
  back: 'Balik',
  add: 'Tambah',
  edit: 'Edit',
  done: 'Siap',
  cancel: 'Batal',
  keep: 'Simpan',
  remove: 'Padam',
  retry: 'Cuba sekali lagi',
  saved: 'Disimpan',
  unknown: 'Tak tahu',
  lang_pick: 'Bahasa',
  prov_user: 'data anda',
  prov_official: 'rasmi',
  prov_calc: 'dikira',
  prov_assume: 'andaian',
  provf_user: 'Data Pengguna: angka yang anda masukkan sendiri.',
  provf_official: 'Sumber Rasmi: angka diterbitkan; sumber dan tarikh dinyatakan.',
  provf_calc: 'Kiraan Terbitan: aritmetik ke atas rekod anda sendiri. Tiada tokok tambah.',
  provf_assume: 'Andaian Ujian Tekanan: nilai lalai boleh ubah, bukan fakta tentang anda.',
  ob1: 'RuMampu tengok macam mana bayaran rumah boleh muat dengan bulan yang lembap, bukan purata je.',
  ob2: 'Nombor-nombor ni jelas nampak. Anda yang tentukan keputusan.',
  ob3: 'Mula dengan apa yang ada. Duit seminggu pun dah cukup baik untuk mula.',
  ob_skip: 'Langkau',
  ob_next: 'Seterusnya',
  ob_start: 'Mula',
  ob_slogan: 'Biar bulan sebenar anda yang mengira.',
  home_rec: 'Anda ada {n} bulan duit masuk direkod.',
  home_rec_one: 'Anda ada 1 bulan duit masuk direkod.',
  home_rec_thin: '{n} bulan ialah rekod yang nipis. Setiap catatan baharu membantu ujian nampak lebih.',
  home_rec_thin_one: '1 bulan ialah rekod yang nipis. Setiap catatan baharu membantu ujian nampak lebih.',
  home_test: 'Cuba sebuah rumah',
  home_retest: 'Cuba semula rumah itu',
  headline: '{s} daripada {n} bulan direkod anda tak cukup.',
  headline_zero: 'Kesemua {n} bulan direkod anda menutup kos ni.',
  gap_lbl: 'Jurang terbesar',
  covspan: '{a} hingga {b} direkod',
  cov_unchecked: 'Liputan belum disemak',
  cov_missed: 'Rekod anda belum nampak {m}. Anda kata ia biasanya lembap.',
  money_income: 'Duit masuk',
  money_workcosts: 'Kos kerja',
  money_commit: 'Tanggungan',
  money_pattern: 'Cara duit masuk',
  money_coverage: 'Semak cukup tak',
  net_lbl: 'Duit masuk lepas tolak kos kerja',
  per_month: '/ bulan, purata',
  inc_empty: 'Masukkan duit minggu lepas. Dah cukup untuk mula.',
  inc_amount: 'Berapa (RM)',
  inc_date: 'Tarikh',
  inc_source: 'Dari mana',
  inc_add: 'Tambah duit masuk',
  inc_neg: 'Tak boleh simpan kalau kurang daripada kosong.',
  inc_outlier: 'Jauh lebih tinggi daripada catatan biasa anda. Nak simpan?',
  inc_sync_loading: 'Sedang muat rekod duit masuk tersimpan anda…',
  inc_sync_error: 'Tak boleh dapat rekod simpan. Semak server dan cuba lagi.',
  inc_invalid_date: 'Gunakan tarikh betul bentuk YYYY-MM-DD.',
  inc_invalid_amount: 'Masukkan jumlah wang yang sah menggunakan nombor sahaja, dengan maksimum 2 tempat perpuluhan.',
  inc_save_failed: 'Duit masuk tak boleh simpan. Sila cuba lagi.',
  inc_saving: 'Menyimpan…',
  src_ehail: 'E-hailing',
  src_freelance: 'Kerja bebas',
  src_parttime: 'Separuh masa (tetap)',
  src_own: '+ Sumber anda sendiri',
  src_name: 'Nama sumber',
  entry_saved: 'Catatan disimpan',
  wc_name: 'Nama kos kerja',
  xc_name: 'Nama kategori',
  wc_petrol: 'Petrol',
  wc_service: 'Servis kenderaan',
  wc_platform: 'Yuran platform',
  wc_data: 'Data telefon',
  wc_roadtax: 'Cukai jalan & insurans',
  wc_own: '+ Kos anda sendiri',
  wc_note: 'Setiap skrin lepas ni guna angka ni.',
  wc_sync_loading: 'Memuatkan kos kerja anda…',
  wc_sync_error: 'Kos kerja tak boleh disegerakkan. Cuba lagi.',
  wc_save_failed: 'Kos kerja tak boleh simpan. Sila cuba lagi.',
  cm_living: 'Kos sara hidup',
  cm_debts: 'Bayar hutang',
  cm_savings: 'Simpanan',
  cm_rent: 'Sewa',
  cm_food: 'Makanan',
  cm_util: 'Utiliti',
  cm_motor: 'Pinjaman motosikal',
  cm_ptptn: 'PTPTN',
  cm_family: 'Bantuan keluarga',
  cm_save: 'Simpanan bulanan',
  cm_total: 'Jumlah tanggungan',
  cm_sync_loading: 'Memuatkan tanggungan anda…',
  cm_sync_error: 'Tanggungan tak boleh disegerakkan. Cuba lagi.',
  cm_save_failed: 'Tanggungan tak boleh simpan. Sila cuba lagi.',
  pt_avg: 'Purata duit boleh guna',
  pt_med: 'Penengah',
  pt_high: 'Tertinggi',
  pt_low: 'Terendah',
  pt_range_total: 'Julat direkod',
  pt_std: 'Sisihan piawai',
  pt_month_count: '{n} bulan direkod',
  pt_loading: 'Mengira cara duit masuk daripada rekod tersimpan…',
  pt_error: 'Cara duit masuk yang dikira tak boleh dicapai. Duit masuk tersimpan anda tak berubah.',
  pt_api_required: 'Analisis Epic 2 hanya ada dalam mod API bersambung. Tetapkan EXPO_PUBLIC_APP_MODE=api dan mulakan backend.',
  pt_empty: 'Cara duit masuk mula dengan satu bulan direkod.',
  pt_empty_note: 'Tambah duit masuk untuk nampak duit boleh guna bulan demi bulan.',
  pt_add_income: 'Tambah duit masuk',
  pt_limited_one: 'Ini satu bulan direkod. Ia tunjuk fakta bulan tu, tapi belum boleh gambarkan cara yang lebih luas.',
  pt_limited_two: 'Ini dua bulan direkod. Angka ni berdasarkan fakta, tapi sejarah yang nampak masih terhad.',
  pt_work_basis: 'Setiap bulan direkod guna jumlah kos kerja bulanan semasa sebanyak {x}.',
  pt_rule: 'Bulan kurang duit masuk di sini ialah bulan duit boleh guna terendah dalam rekod semasa anda. Ia bukan piawaian kewangan atau ramalan.',
  pt_none: 'Tambah satu lagi bulan direkod sebelum banding bulan kurang duit masuk.',
  pt_some: 'Terendah dalam rekod semasa anda: {m}.',
  cv_q: 'Ada musim anda biasanya kurang duit masuk?',
  cv_yes: 'Ya',
  cv_no: 'Tidak',
  cv_notsure: 'Tak pasti',
  cv_pick: 'Tandakan bulan yang biasanya lembap.',
  cv_loading: 'Memuatkan jawapan liputan tersimpan…',
  cv_error: 'Liputan tak boleh dimuatkan atau disimpan. Anda boleh cuba lagi tanpa hilang jawapan terakhir yang disahkan.',
  cv_check: 'Semak liputan',
  cv_checking: 'Menyemak…',
  cv_select_required: 'Pilih sekurang-kurangnya satu bulan lembap.',
  cv_save_failed: 'Liputan tak boleh simpan. Sila cuba lagi.',
  cv_represented: 'Dalam rekod duit masuk anda: {m}.',
  cv_unrepresented: 'Belum dalam rekod duit masuk anda: {m}.',
  cv_observation: 'Dalam {n} bulan direkod, duit boleh guna antara {lo} dan {hi}, dengan julat {range}. Fakta ni tak boleh sahkan sama ada tempoh lembap biasa anda ada.',
  cv_api_required: 'Semakan liputan hanya ada dalam mod API bersambung. Tetapkan EXPO_PUBLIC_APP_MODE=api dan mulakan backend.',
  cv_no_history: 'Belum ada bulan duit masuk direkod untuk dibandingkan.',
  cv_previous: 'Hasil di bawah ialah jawapan terakhir yang disahkan oleh pelayan. Pilihan baharu anda belum disimpan.',
  cv_note: 'Bulan tambahan hanya membantu kalau bulan yang betul ada di dalamnya.',
  th_title: 'Rumah tu',
  th_price: 'Harga rumah (RM)',
  th_fin: 'Jumlah pembiayaan',
  th_dep: 'Bayaran muka (RM)',
  th_dep0: 'RM 0 dibenarkan. Pembiayaan 100% ada.',
  th_rate: 'Kadar (% / tahun)',
  th_ten: 'Tempoh (tahun)',
  th_inst: 'Bayar bulanan',
  th_known: 'Saya dah tahu bayar bulanan saya',
  th_knownamt: 'Bayar bulanan (RM)',
  th_next: 'Jumlah kos bulanan',
  tc_title: 'Jumlah kos bulanan',
  tc_point: 'Bayar bulanan bukan keseluruhan kos.',
  tc_inst: 'Bayar bulanan',
  tc_inst_desc: 'Daripada butiran pembiayaan anda',
  tc_break: 'Apa dalam tu',
  tc_run: 'Jalankan ujian',
  housing_running: 'Sedang kira…',
  housing_run_failed: 'Pengiraan rumah tak boleh selesai. Sila cuba lagi.',
  housing_result_required: 'Jalankan ujian rumah dulu supaya skrin ni boleh guna hasil yang dikira oleh pelayan.',
  hc_maint: 'Penyelenggaraan & tabung penjelas',
  hc_maint_desc: 'Untuk pembaikan dan penyelenggaraan',
  hc_insure: 'Insurans rumah',
  hc_insure_desc: 'Insurans rumah asas',
  hc_assess: 'Cukai pintu',
  hc_assess_desc: 'Dibayar kepada pihak berkuasa tempatan',
  hc_quit: 'Cukai tanah',
  hc_quit_desc: 'Sewa tanah (jika berkenaan)',
  hc_parking: 'Parkir',
  hc_parking_desc: 'Kos parkir bulanan',
  hc_other: 'Lain-lain',
  hc_other_desc: 'Kos berulang lain',
  pc_title: 'Sebelum rumah',
  pc_msg: 'Pada {m}, bulan paling lembap dalam rekod anda, duit masuk RM {x} kurang daripada kos harian anda, sebelum sebarang kos rumah.',
  pc_msg2: 'Bayar rumah di atasnya akan buat semua bulan kurang, pada apa jua harga. Semak dulu duit masuk dan kos supaya ujian ni lebih kukuh.',
  pc_btn: 'Pergi ke Duit',
  rs_title: 'Keputusan',
  rs_how: 'Macam mana ia dikira',
  rs_how_body: 'Setiap bar ialah satu bulan direkod: duit masuk lepas tolak kos kerja, tolak tanggungan. Garisan ialah jumlah kos rumah bulanan, RM {c}. Bulan dikira kurang bila barnya habis bawah garisan.',
  rs_shortfall_breakdown: 'Punca kekurangan',
  rs_existing_shortfall: 'Sudah kurang sebelum kos rumah',
  rs_housing_shortfall: 'Jadi kurang sebab rumah ni',
  rs_shortfall_breakdown_note: 'Kekurangan sedia ada dah bawah kosong sebelum kos rumah ditambah. Kekurangan sebab rumah ialah bulan yang jadi negatif lepas kos rumah ujian ni digunakan.',
  rs_limit_slow: 'Ujian ni belum nampak {m}, yang anda kata biasanya lembap. Kiraan di bawah belum masuk musim yang lebih lembap tu.',
  rs_limit_thin: 'Baru {n} bulan direkod. Belum cukup untuk kiraan ni bermakna.',
  rs_range: 'Julat terbawa',
  rs_compare: 'Banding bayar',
  rs_shock: 'Kalau duit masuk turun',
  rg_lead: 'Bulan-bulan direkod anda boleh tanggung bayar RM {a} hingga RM {b} sebulan.',
  rg_how: 'Maksud dua hujung tu',
  rg_how_body: 'RM {a}: semua bulan direkod menutupnya. RM {b}: separuh daripadanya.',
  rg_price: 'Pada {r}% selama {y} tahun, tu lebih kurang RM {p} hingga RM {q} harga rumah.',
  rg_pin: 'ujian anda',
  rg_ind: 'Petunjuk je. Bukan penilaian, bukan tawaran.',
  cp_note: 'Bulan direkod yang sama, tiga bayar.',
  cp_price: 'RM {payment}/bulan ≈ nilai rumah RM {price}',
  cp_price_note: 'Anggaran je, guna kadar, tempoh dan deposit yang dimasukkan untuk ujian ni.',
  cp_short: '{s} daripada {n} kurang',
  cp_gap: 'jurang terbesar RM {g}',
  cp_pay: 'Bayar {i} (RM)',
  sh_disclaimer: 'Senario hipotesis, bukan ramalan.',
  sh_note: 'Hanya guna bulan yang anda rekod. Ia tak cakap apa yang akan jadi masa depan.',
  sh_custom: 'Sendiri',
  sh_pct: 'Turun (%)',
  sh_head: 'Pada −{p}%: {s} daripada {n} bulan direkod tak cukup.',
  pr_upfront: 'Duit permulaan',
  pr_buffer: 'Duit simpanan',
  pr_docs: 'Dokumen & pembiayaan',
  pr_pv: 'Pratonton Iterasi 3',
  pr_pv_note: 'Lepas beli. Hala tuju je, belum dilancarkan.',
  pr_coming: 'Akan datang',
  pr_coming_note: 'Bahagian ni sedang dibina.',
  uf_have: 'Anda ada',
  uf_need: 'Anda perlukan',
  uf_gap: 'Jurang',
  uf_dep: 'Bayar muka',
  uf_legal: 'Yuran guaman',
  uf_stampT: 'Duti setem (pindah milik)',
  uf_stampL: 'Duti setem (pinjaman)',
  uf_val: 'Penilaian rumah',
  uf_disb: 'Perbelanjaan pelbagai guaman',
  uf_move: 'Pindah rumah',
  uf_basic: 'Asas (peti sejuk, katil, langsir)',
  uf_dep0: 'Deposit RM 0: duit permulaan ialah yuran dan persiapan, bukan deposit.',
  bf_def: 'Jumlah paling kecil yang anda perlukan pada mula untuk lepas bulan-bulan kurang dalam rekod anda tanpa jatuh bawah kosong.',
  bf_basis: 'Daripada rekod anda sendiri, {a} hingga {b}. Bukan peraturan umum.',
  bf_zero: 'Dengan rumah ni, bulan direkod anda tak pernah jatuh bawah kosong. Kiraannya RM 0.',
  bf_bal: 'Baki berjalan ikut bulan',
  dc_bank: 'Penyata bank, 6 bulan',
  dc_ehail: 'Ringkasan duit masuk e-hailing',
  dc_statdec: 'Surat akuan berkanun duit masuk',
  dc_epf: 'Penyata KWSP',
  dc_commitlist: 'Senarai tanggungan sedia ada',
  dc_sjkp: 'Kriteria terbitan SJKP',
  dc_sj1: 'Warganegara Malaysia, umur 18 hingga 70',
  dc_sj2: 'Duit masuk kasar dalam had terbitan SJKP',
  dc_sj3: 'Rumah pertama',
  dc_src: 'Sumber: sjkp.com.my, Ogo 2026',
  dc_65: 'Semakan 65%: perlu semakan semula',
  dc_65_note: 'SJKP ukur duit masuk kasar; RuMampu ukur duit masuk lepas tolak kos kerja. Selagi beza tu belum selesai, tiada keputusan ditunjukkan di sini.',
  dc_plain: 'RuMampu tak mohon bagi pihak anda dan tak boleh cakap sama ada bank akan kata ya.',
  pv_banner: 'Pratonton Iterasi 3',
  pv_switch: 'Tukar mod',
  pv_switch_btn: 'Saya dah beli rumah tu',
  pv_switch_note: 'Anggaran bertukar kepada angka sebenar. Pembelian berlaku di luar RuMampu.',
  pv_month: 'Bulan ini',
  pv_in: 'Duit masuk sebenar',
  pv_out: 'Kos rumah sebenar keluar',
  pv_left: 'Baki tunai',
  pv_shortby: 'Kurang sebanyak',
  pv_then: 'Ujian awal vs yang berlaku',
  pv_then_a: 'Ujian awal anda: {s} bulan kurang daripada {n} direkod.',
  pv_then_b: 'Sejak membeli: {s2} daripada {n2} bulan pertama anda kurang.',
  pv_then_why: 'Rekod awal tiada bulan hujung tahun di dalamnya. Dua bulan begitu tiba selepas membeli.',
  see_pattern: 'Cara duit masuk',
  see_coverage: 'Semak cukup tak',
  // EN: Epic 8 Your Record localisation keys for US8.1 and US8.2 display copy.
  // 中文：Epic 8 "记录档案"本地化 key，用于 US8.1 和 US8.2 的展示文案。
  money_record: 'Rekod anda',
  rc_months: '{n} bulan direkod',
  rc_months_one: '1 bulan direkod',
  rc_summary: 'Rekod kewangan',
  rc_month_metric: 'bulan direkod',
  rc_month_metric_one: 'bulan direkod',
  rc_entry_metric: 'catatan kewangan',
  rc_entries: '{e} catatan kewangan',
  rc_latest_label: 'Catatan terkini',
  rc_latest: 'Catatan terkini: {d}',
  rc_latest_empty: 'Belum ada catatan duit masuk atau perbelanjaan bertarikh.',
  rc_tests: 'Ujian rumah disimpan',
  rc_none: 'Belum ada ujian disimpan. Jalankan satu dari tab Cuba.',
  rc_none_title: 'Belum ada ujian disimpan',
  rc_none_body: 'Jalankan ujian rumah dan simpan hasilnya di sini untuk sesi ini.',
  rc_test_action: 'Pergi ke Cuba',
  rc_live: 'Rekod anda hanya ada dalam sesi tetamu sekarang pada pelayar atau peranti ni. Ia tak disimpan ke akaun RuMampu.',
  rc_about: 'Tentang rekod anda',
  rc_keep_line: 'Setiap minggu baharu yang anda rekod bagi ujian seterusnya lebih banyak bulan sebenar anda.',
  rc_test_session: 'Disimpan untuk sesi ni.',
  rc_pay_month: '{p} / bulan',
  rc_short_label: 'Bulan kurang',
  rc_short_value: '{s} daripada {n}',
  // EN: Epic 8 Keep This Test action/status copy shown from the housing Result screen.
  // 中文：Epic 8 "留存这次测试"的操作与状态文案，显示在住房测试结果页。
  rs_keep: 'Simpan ujian ni',
  rs_keep_hint: 'Tambah hasil ni ke Rekod anda untuk sesi ni.',
  rs_kept: 'Ujian disimpan',
  rs_kept_session: 'Disimpan untuk sesi ni.',
  entry_saved_n: 'Catatan disimpan. Analisis sekarang guna {n} bulan.',
  inc_recorded: 'Pendapatan direkodkan',
  inc_past: 'Tambah bulan lalu',
  inc_past_hint: 'Satu jumlah untuk bulan tu dah cukup.',
  inc_past_no_min: 'Tambah sejarah yang anda ada. Tak ada minimum 6 atau 12 bulan.',
  inc_past_month: 'Bulan lalu (YYYY-MM)',
  inc_past_invalid: 'Masukkan bulan betul yang lebih awal daripada bulan sekarang.',
  inc_past_exists: 'Bulan tu dah ada rekod duit masuk. Pilih bulan lain.',
  inc_past_amount: 'Masukkan jumlah yang lebih besar daripada kosong.',
  inc_past_cash: 'Masukkan jumlah wang yang sah menggunakan nombor sahaja, dengan maksimum 2 tempat perpuluhan.',
  inc_month_total: 'Jumlah bulanan',
  inc_import: 'Import duit masuk daripada CSV',
  imp_title: 'Import duit masuk',
  imp_intro: 'Pilih fail CSV. RuMampu akan sediakan pratonton sebelum sebarang data ditambah.',
  imp_format: 'Lajur wajib: amount, date, source. Tarikh mesti tarikh lalu dalam format YYYY-MM-DD.',
  imp_select: 'Pilih fail CSV',
  imp_reading: 'Membaca fail…',
  imp_summary: '{name}: {total} baris',
  imp_ready: '{n} sedia',
  imp_attention: '{n} perlu perhatian',
  imp_row: 'Baris {n}',
  imp_raw: 'Asal: {amount} · {date} · {source}',
  imp_confirm: 'Sahkan dan tambah {n} rekod',
  imp_confirming: 'Menambah rekod…',
  imp_confirmed: '{n} rekod duit masuk ditambah. Analisis anda sekarang gunakannya.',
  imp_failed: 'Fail duit masuk tak boleh diproses. Semak CSV dan cuba lagi.',
  imp_view_pattern: 'Lihat cara duit masuk',
  imp_no_ready: 'Tiada baris sah yang sedia untuk ditambah.',
  pt_bymonth: 'Bulan demi bulan',
  pt_chart_accessibility: 'Duit boleh guna dikira bulan demi bulan',
  pt_scroll: 'Tatal secara mendatar untuk lihat semua bulan direkod.',
  pv_keep: 'Terus rekod lepas beli. Rekod yang sama terus berfungsi.',
  money_expenses: 'Perbelanjaan harian',
  ex_sofar: '{m} setakat ni',
  ex_days: '{d} hari direkod',
  ex_days_one: '1 hari direkod',
  ex_empty: 'Belum ada perbelanjaan harian direkod.',
  ex_add: 'Tambah perbelanjaan',
  ex_scan: 'Imbas resit',
  ex_preview: 'Pratonton',
  ex_sync_loading: 'Memuatkan perbelanjaan tersimpan anda…',
  ex_sync_error: 'Perbelanjaan tak boleh disegerakkan. Cuba lagi.',
  ex_saving: 'Menyimpan…',
  ex_amount_positive: 'Masukkan jumlah yang lebih besar daripada kosong.',
  ex_date_invalid: 'Masukkan tarikh kalendar yang sah.',
  ex_save_failed: 'Perbelanjaan tak boleh simpan. Cuba lagi.',
  ex_bycat: 'Ikut kategori',
  xc_meals: 'Makan',
  xc_groc: 'Barang dapur',
  xc_transp: 'Tol & parkir',
  xc_family: 'Keluarga',
  xc_other: 'Lain-lain',
  xc_own: '+ Kategori anda',
  ex_saved: 'Disimpan. {m} setakat ni: RM {x}.',
  ex_rule: 'Sebulan dikira lengkap bila 20 hari direkod. Peraturan RuMampu sendiri.',
  ex_feeds: '{m} guna perbelanjaan direkod anda, RM {x}, gantikan anggaran makanan dan keluarga.',
  ex_scan_pick: 'Ambil atau pilih gambar resit.',
  ex_take_photo: 'Ambil foto',
  ex_choose_photo: 'Pilih foto',
  ex_image_failed: 'Gambar resit tak boleh buka. Cuba lagi.',
  ex_scan_sample: 'Guna resit contoh',
  ex_reading: 'Membaca resit…',
  ex_check: 'Dibaca daripada resit anda. Semak sebelum menyimpan.',
  ex_merchant: 'Kedai',
  ex_total: 'Jumlah (RM)',
  ex_retake: 'Ambil semula',
  ex_fromr: 'daripada resit',
  ex_cat: 'Kategori',
  ex_monthly: 'Ringkasan bulanan',
  ex_full: 'lengkap direkod',
  ex_used: 'digunakan dalam ujian',
  ex_partial: '{d} hari, hari lain tak diketahui',
  ex_partial_one: '1 hari, hari lain tak diketahui',
  ex_limits: 'Had perbelanjaan',
  lm_note: 'Had ni anda yang tetapkan. RuMampu hanya kira.',
  lm_total: 'Keseluruhan bulan',
  lm_limit: 'Had (RM)',
  lm_left: 'RM {x} lagi',
  lm_over: 'RM {x} lebih daripada had anda',
  lm_none: 'tiada had ditetapkan',
  hb_spend: 'Perbelanjaan · {m}',
  hb_income: 'Duit masuk · {m}'
},
zh: {
  langname: '中文', months: ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'],
  tab_home: '主页', tab_money: '收支', tab_test: '测试', tab_prepare: '准备',
  back: '返回', add: '添加', edit: '修改', done: '完成', cancel: '取消', keep: '保留', remove: '删除', retry: '重试',
  saved: '已保存', unknown: '未知', lang_pick: '语言',
  prov_user: '你的记录', prov_official: '官方', prov_calc: '计算所得', prov_assume: '假设',
  provf_user: '用户数据：你自己输入的数字。',
  provf_official: '官方来源：已公布的数字，注明来源和日期。',
  provf_calc: '推导计算：只对你自己的记录做算术，别无其他。',
  provf_assume: '压力测试假设：可修改的默认值，不是关于你的事实。',
  ob1: 'RuMampu 帮你看看，房屋月供在收入较慢的月份是否也过得去，而不只看平均。',
  ob2: '它把数字清楚地摆出来，决定始终在你手上。',
  ob3: '有什么就从什么开始，一周的收入已是很好的起点。',
  ob_skip: '跳过', ob_next: '下一步', ob_start: '开始',
  ob_slogan: '让真实的月份，替你算一算。',
  home_rec: '你已记录 {n} 个月的收入。',
  home_rec_one: '你已记录 1 个月的收入。',
  home_rec_thin: '{n} 个月的记录还很薄。每多记一笔，测试就多看到一点。',
  home_rec_thin_one: '1 个月的记录还很薄。每多记一笔，测试就多看到一点。',
  home_test: '测试一套房', home_retest: '重新测试这套房',
  headline: '在已记录的 {n} 个月中，{s} 个月的钱不够。',
  headline_zero: '已记录的 {n} 个月都够付这笔成本。',
  gap_lbl: '最大缺口',
  covspan: '已记录 {a} 至 {b}',
  cov_unchecked: '覆盖情况尚未检查',
  cov_missed: '你的记录还没见过{m}。你说那时通常较慢。',
  money_income: '收入', money_workcosts: '工作开销', money_commit: '固定开支',
  money_pattern: '收入形态', money_coverage: '覆盖检查',
  net_lbl: '扣除工作开销后的收入', per_month: '/ 月，平均',
  inc_empty: '先记上周的收入，就足够开始了。',
  inc_amount: '金额 (RM)', inc_date: '日期', inc_source: '来源', inc_add: '添加收入',
  inc_neg: '低于零的金额无法保存。',
  inc_outlier: '比你平常的记录高很多。保留吗？',
  inc_sync_loading: '正在载入已保存的收入记录……',
  inc_sync_error: '无法连接已保存的记录，请检查后端后重试。',
  inc_invalid_date: '请使用 YYYY-MM-DD 格式的有效日期。',
  inc_invalid_amount: '请输入有效金额，只能使用数字，并且最多保留 2 位小数。',
  inc_save_failed: '收入保存失败，请重试。',
  inc_saving: '保存中……',
  src_ehail: '电召车', src_freelance: '自由接单', src_parttime: '兼职（固定）',
  src_own: '＋自定来源', src_name: '来源名称', entry_saved: '已记录',
  wc_name: '工作成本名称', xc_name: '类别名称',
  wc_petrol: '汽油', wc_service: '车辆保养', wc_platform: '平台抽成', wc_data: '手机流量', wc_roadtax: '路税与车险',
  wc_own: '＋自定开销', wc_note: '之后每个页面都用这个数字。',
  wc_sync_loading: '正在加载工作成本…',
  wc_sync_error: '工作成本同步失败，请重试。',
  wc_save_failed: '工作成本保存失败，请重试。',
  cm_living: '生活开销', cm_debts: '还债', cm_savings: '储蓄',
  cm_rent: '房租', cm_food: '伙食', cm_util: '水电', cm_motor: '摩托车贷款', cm_ptptn: 'PTPTN', cm_family: '家用', cm_save: '每月储蓄',
  cm_total: '固定开支合计',
  cm_sync_loading: '正在加载固定开支…',
  cm_sync_error: '固定开支同步失败，请重试。',
  cm_save_failed: '固定开支保存失败，请重试。',
  pt_avg: '平均可用收入', pt_med: '中位数', pt_high: '最高', pt_low: '最低',
  pt_range_total: '记录范围', pt_std: '标准差',
  pt_month_count: '已记录 {n} 个月',
  pt_loading: '正在根据已保存记录计算收入形态……',
  pt_error: '无法获取计算后的收入形态；已保存收入没有发生改变。',
  pt_api_required: 'Epic 2 分析仅在后端 API 连接模式下可用。请设置 EXPO_PUBLIC_APP_MODE=api 并启动后端。',
  pt_empty: '记录一个月份后，收入形态就会开始形成。',
  pt_empty_note: '添加收入后，即可逐月查看可用收入。', pt_add_income: '添加收入',
  pt_limited_one: '目前只有一个记录月。这里显示该月的事实，但还不能描述更广泛的形态。',
  pt_limited_two: '目前有两个记录月。数字是事实，但可见历史仍然有限。',
  pt_work_basis: '每个记录月均使用当前月度工作成本总额 {x}。',
  pt_rule: '这里的较低收入月，是当前记录中可用收入最低的月份；它不是金融标准，也不是预测。',
  pt_none: '再添加一个记录月后，才能比较较低收入月份。',
  pt_some: '当前记录中的最低月份：{m}。',
  cv_q: '一年中，有没有你通常赚得较少的时候？',
  cv_yes: '有', cv_no: '没有', cv_notsure: '不确定',
  cv_pick: '点选通常较慢的月份。',
  cv_loading: '正在载入已保存的覆盖回答……',
  cv_error: '覆盖回答加载或保存失败；重试不会丢失上一次已确认回答。',
  cv_check: '检查覆盖情况', cv_checking: '检查中……',
  cv_select_required: '请至少选择一个慢月份。', cv_save_failed: '覆盖回答保存失败，请重试。',
  cv_represented: '收入记录已经覆盖：{m}。',
  cv_unrepresented: '收入记录尚未覆盖：{m}。',
  cv_observation: '在 {n} 个记录月中，可用收入介于 {lo} 与 {hi}，范围为 {range}。这些事实无法确认通常较慢的时期是否具有代表性。',
  cv_api_required: '覆盖检查仅在后端 API 连接模式下可用。请设置 EXPO_PUBLIC_APP_MODE=api 并启动后端。',
  cv_no_history: '目前没有可用于比较的收入记录月。',
  cv_previous: '下方结果是服务器上一次确认的回答；你的新选择尚未保存。',
  cv_note: '多记几个月有用的前提，是记到对的月份。',
  th_title: '这套房', th_price: '房价 (RM)', th_fin: '贷款额', th_dep: '头期 (RM)',
  th_dep0: 'RM 0 也可以，有 100% 贷款。',
  th_rate: '年利率 (%)', th_ten: '年期（年）', th_inst: '每月供款',
  th_known: '我已知道每月供款', th_knownamt: '每月供款 (RM)',
  th_next: '每月总成本',
  tc_title: '每月总成本', tc_point: '供款不等于全部成本。',
  tc_inst: '贷款供款（每月供款）', tc_inst_desc: '根据你的贷款资料', tc_break: '包含哪些', tc_run: '开始测试',
  housing_running: '正在计算…',
  housing_run_failed: '住房计算未能完成，请重试。',
  housing_result_required: '请先运行住房测试，以便此页面使用服务器计算的结果。',
  hc_maint: '管理费与储备金', hc_maint_desc: '用于维修和保养', hc_insure: '房屋保险', hc_insure_desc: '基本房屋保险', hc_assess: '门牌税', hc_assess_desc: '缴付给地方政府', hc_quit: '地税', hc_quit_desc: '土地租金（如适用）', hc_parking: '车位', hc_parking_desc: '每月停车费用', hc_other: '其他', hc_other_desc: '其他经常性费用',
  pc_title: '还没算房子之前',
  pc_msg: '在收入最清淡的 {m}，收入比日常开销少了 RM {x}，还没算任何房屋成本。',
  pc_msg2: '再加上房屋支出，无论房价多少，每个月都会不够。先看看收入和开销，测试随时可以再来。',
  pc_btn: '去收支',
  rs_title: '结果',
  rs_how: '这是怎么算的',
  rs_how_body: '每根柱是一个记录月：扣除工作开销的收入，再减固定开支。横线是每月房屋总成本 RM {c}。柱子够不到线，该月就算短缺。',
  rs_shortfall_breakdown: '短缺来自哪里',
  rs_existing_shortfall: '还没算房屋成本前已经短缺',
  rs_housing_shortfall: '因为这套房才出现短缺',
  rs_shortfall_breakdown_note: '现有短缺是加入房屋成本前已经低于零的月份。房屋造成的短缺则是加入这次测试的房屋成本后才变成负数的月份。',
  rs_limit_slow: '这次测试还没见过你说通常较慢的{m}。下面的计数还没包含那段较慢的日子。',
  rs_limit_thin: '只记录了 {n} 个月，还不足以让这个计数有分量。',
  rs_range: '承担区间', rs_compare: '比较付款', rs_shock: '如果收入下降',
  rg_lead: '你记录的月份承担过每月 RM {a} 至 RM {b} 的付款。',
  rg_how: '两端是什么意思',
  rg_how_body: 'RM {a}：每个记录月都够。RM {b}：一半的月份够。',
  rg_price: '按 {r}%、{y} 年计，约合房价 RM {p} 至 RM {q}。',
  rg_pin: '你的测试',
  rg_ind: '仅供参考。不是估价，也不是要约。',
  cp_note: '同样的记录月份，三种付款。',
  cp_price: '每月 RM {payment} ≈ 房产价值 RM {price}',
  cp_price_note: '仅供参考，按这次测试输入的利率、年限和首付计算。',
  cp_short: '{n} 个月中 {s} 个短缺', cp_gap: '最大缺口 RM {g}', cp_pay: '付款 {i} (RM)',
  sh_disclaimer: '假设情景，并非预测。',
  sh_note: '仅使用您已记录的月份，不代表未来一定会发生什么。',
  sh_custom: '自定', sh_pct: '下降 (%)',
  sh_head: '按 −{p}% 计：{n} 个记录月中 {s} 个不够。',
  pr_upfront: '购房现金', pr_buffer: '现金缓冲', pr_docs: '文件与融资',
  pr_pv: '第 3 迭代预览', pr_pv_note: '买房之后。仅展示方向，尚未上线。',
  pr_coming: '即将推出', pr_coming_note: '此部分正在建设中。',
  uf_have: '你有', uf_need: '需要', uf_gap: '缺口',
  uf_dep: '头期', uf_legal: '律师费', uf_stampT: '印花税（过户）', uf_stampL: '印花税（贷款）', uf_val: '估价费', uf_disb: '杂项支出', uf_move: '搬家', uf_basic: '基本家当（冰箱、床、窗帘）',
  uf_dep0: '头期 RM 0：购房现金是各项费用和安家，不是头期。',
  bf_def: '让你撑过记录中短缺的月份、且不跌破零，开头所需的最小金额。',
  bf_basis: '来自你自己 {a} 到 {b} 的记录，不是通用规则。',
  bf_zero: '按这套房算，你记录的月份从未跌破零。得数是 RM 0。',
  bf_bal: '逐月滚动余额',
  dc_bank: '银行月结单，6 个月', dc_ehail: '电召车收入摘要', dc_statdec: '收入法定声明', dc_epf: 'EPF 公积金结单', dc_commitlist: '现有开支清单',
  dc_sjkp: 'SJKP 公布的条件',
  dc_sj1: '马来西亚公民，18 至 70 岁', dc_sj2: '总收入在 SJKP 公布的上限内', dc_sj3: '首套房',
  dc_src: '来源：sjkp.com.my，2026 年 8 月',
  dc_65: '65% 核对：待复核',
  dc_65_note: 'SJKP 按总收入计，RuMampu 按扣除工作开销后的收入计。在厘清之前，这里不显示通过或不通过。',
  dc_plain: 'RuMampu 不会替你申请，也无法告诉你银行是否点头。',
  pv_banner: '第 3 迭代预览',
  pv_switch: '切换模式', pv_switch_btn: '我已买下这套房',
  pv_switch_note: '估算换成实际数字。购买本身在 RuMampu 之外完成。',
  pv_month: '本月', pv_in: '实际收入', pv_out: '实际房屋支出',
  pv_left: '剩余现金', pv_shortby: '短缺',
  pv_then: '先前测试 vs 实际情况',
  pv_then_a: '先前测试：{n} 个记录月中 {s} 个短缺。',
  pv_then_b: '买房后：头 {n2} 个月中 {s2} 个短缺。',
  pv_then_why: '先前的记录里没有年末月份，买房后遇上了两个。',
  see_pattern: '收入形态', see_coverage: '覆盖检查',
  // EN: Epic 8 Your Record localisation keys for US8.1 and US8.2 display copy.
  // 中文：Epic 8 “记录档案”本地化 key，用于 US8.1 和 US8.2 的展示文案。
  money_record: '记录档案',
  rc_months: '已记录 {n} 个月',
  rc_months_one: '已记录 1 个月',
  rc_summary: '财务记录',
  rc_month_metric: '已记录月份',
  rc_month_metric_one: '已记录月份',
  rc_entry_metric: '财务记录',
  rc_entries: '{e} 笔财务记录',
  rc_latest_label: '最近记录',
  rc_latest: '最近记录日期：{d}',
  rc_latest_empty: '还没有带日期的收入或支出记录。',
  rc_tests: '留存的住房测试',
  rc_none: '还没有留存的测试。到测试页跑一次。',
  rc_none_title: '还没有留存的测试',
  rc_none_body: '运行一次住房测试，并把结果留存在这里供本次会话查看。',
  rc_test_action: '前往测试',
  rc_live: '你的记录只在此浏览器或设备的当前访客会话中可用，不会保存到 RuMampu 账户。',
  rc_about: '关于你的记录',
  rc_keep_line: '每多记一周，下一次测试就多一点你真实的月份。',
  rc_test_session: '仅在本次会话中留存。',
  rc_pay_month: '{p} / 月',
  rc_short_label: '短缺月份',
  rc_short_value: '{n} 个月中 {s} 个',
  // EN: Epic 8 Keep This Test action/status copy shown from the housing Result screen.
  // 中文：Epic 8 “留存这次测试”的操作与状态文案，显示在住房测试结果页。
  rs_keep: '留存这次测试', rs_keep_hint: '把这个结果加入记录档案，仅供本次会话查看。', rs_kept: '测试已留存', rs_kept_session: '仅在本次会话中留存。',
  entry_saved_n: '已记录。分析现在用上 {n} 个月。',
  inc_recorded: '已记录收入',
  inc_past: '补记过去的月份',
  inc_past_hint: '那个月一个总数就够。',
  inc_past_no_min: '有多少历史就补多少，不要求至少 6 或 12 个月。',
  inc_past_month: '历史月份 (YYYY-MM)',
  inc_past_invalid: '请输入早于本月的有效月份。',
  inc_past_exists: '这个月已有收入记录，请选择其他月份。',
  inc_past_amount: '请输入大于零的月收入总额。',
  inc_past_cash: '请输入有效金额，只能使用数字，并且最多保留 2 位小数。',
  inc_month_total: '整月总额',
  inc_import: '从 CSV 导入收入',
  imp_title: '导入收入',
  imp_intro: '请选择 CSV 文件。RuMampu 会先生成预览，确认前不会写入任何收入。',
  imp_format: '必填列：amount、date、source。日期必须早于今天，格式为 YYYY-MM-DD。',
  imp_select: '选择 CSV 文件',
  imp_reading: '正在读取文件……',
  imp_summary: '{name}：共 {total} 行',
  imp_ready: '{n} 行可导入',
  imp_attention: '{n} 行需要处理',
  imp_row: '第 {n} 行',
  imp_raw: '原始内容：{amount} · {date} · {source}',
  imp_confirm: '确认并添加 {n} 笔记录',
  imp_confirming: '正在添加记录……',
  imp_confirmed: '已添加 {n} 笔收入，分析结果已同步更新。',
  imp_failed: '收入文件处理失败，请检查 CSV 后重试。',
  imp_view_pattern: '查看收入形态',
  imp_no_ready: '没有可导入的有效行。',
  pt_bymonth: '逐月',
  pt_chart_accessibility: '逐月计算后的可用收入',
  pt_scroll: '横向滚动可查看全部记录月份。',
  pv_keep: '买房后继续记录，同一份记录继续发挥作用。',
  money_expenses: '每日记账',
  ex_sofar: '{m} 至今', ex_days: '已记录 {d} 天', ex_days_one: '已记录 1 天',
  ex_empty: '尚未记录日常支出。',
  ex_add: '记一笔', ex_scan: '扫描收据', ex_preview: '预览',
  ex_sync_loading: '正在载入已保存的支出……', ex_sync_error: '支出同步失败，请重试。',
  ex_saving: '正在保存……', ex_amount_positive: '请输入大于零的金额。',
  ex_date_invalid: '请输入有效的日历日期。', ex_save_failed: '支出保存失败，请重试。',
  ex_bycat: '按类别',
  xc_meals: '吃饭', xc_groc: '日用采买', xc_transp: '过路费与停车', xc_family: '家用', xc_other: '其他', xc_own: '＋自定类别',
  ex_saved: '已记下。{m} 至今：RM {x}。',
  ex_rule: '记满 20 天，当月才算记录完整。这是 RuMampu 自己的规则。',
  ex_feeds: '{m} 用了你记录的开销 RM {x}，代替伙食和家用的估算。',
  ex_scan_pick: '拍摄或选择收据照片。',
  ex_take_photo: '拍摄照片', ex_choose_photo: '选择照片',
  ex_image_failed: '无法打开收据图片，请重试。',
  ex_scan_sample: '用示例收据',
  ex_reading: '正在读取收据……',
  ex_check: '从收据读到的内容，保存前请核对。',
  ex_merchant: '商家', ex_total: '总额 (RM)', ex_retake: '重拍', ex_fromr: '来自收据', ex_cat: '类别',
  ex_monthly: '按月汇总',
  ex_full: '记录完整', ex_used: '已用于测试',
  ex_partial: '记录 {d} 天，其余未知', ex_partial_one: '记录 1 天，其余未知',
  ex_limits: '消费上限',
  lm_note: '上限由你自己设定，RuMampu 只负责计数。',
  lm_total: '整月', lm_limit: '上限 (RM)',
  lm_left: '还剩 RM {x}',
  lm_over: '超出上限 RM {x}',
  lm_none: '未设上限',
  hb_spend: '开销 · {m}', hb_income: '收入 · {m}'
}
};
