/* All user-facing copy in three languages — ported verbatim from the prototype. */

export type Lang = 'en' | 'ms' | 'zh';

export type StringTable = { langname: string; months: string[] } & Record<string, string | string[]>;

export const STRINGS: Record<Lang, StringTable> = {
en: {
  langname: 'English', months: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
  tab_home: 'Home', tab_money: 'Money', tab_test: 'Test', tab_prepare: 'Prepare',
  back: 'Back', add: 'Add', edit: 'Edit', done: 'Done', cancel: 'Cancel', keep: 'Keep', remove: 'Remove',
  saved: 'Saved', unknown: 'Unknown', lang_pick: 'Language',
  prov_user: 'your data', prov_official: 'official', prov_calc: 'calculated', prov_assume: 'assumption',
  provf_user: 'User Data: a figure you entered yourself.',
  provf_official: 'Official Source: a published figure; source and date shown.',
  provf_calc: 'Derived Calculation: arithmetic on your own records. Nothing else added.',
  provf_assume: 'Stress-Test Assumption: an editable default, not a fact about you.',
  ob1: 'RuMampu checks how a home payment fits your quieter months, not just your average ones.',
  ob2: 'It lays the numbers out clearly. The decision is always yours.',
  ob3: 'Begin with whatever you have. Even one week of income is a good start.',
  ob_skip: 'Skip', ob_next: 'Next', ob_start: 'Start',
  ob_slogan: 'Let your real months do the counting.',
  home_rec: 'You have {n} months of income recorded.',
  home_rec_thin: '{n} months is a thin record. Every entry you add lets the test see more.',
  home_test: 'Test a house', home_retest: 'Re-test the house',
  headline: '{s} of your {n} recorded months would have run short.',
  headline_zero: 'None of your {n} recorded months would have run short.',
  gap_lbl: 'Largest gap',
  covspan: '{a} to {b} recorded',
  cov_unchecked: 'Coverage not checked yet',
  cov_missed: 'Your records haven’t seen {m} yet. You said it is usually slower.',
  money_income: 'Income', money_workcosts: 'Work costs', money_commit: 'Commitments',
  money_pattern: 'Income pattern', money_coverage: 'Coverage check',
  net_lbl: 'Income after work costs', per_month: '/ month, average',
  inc_empty: 'Add last week’s earnings. That’s enough to start.',
  inc_amount: 'Amount (RM)', inc_date: 'Date', inc_source: 'Source', inc_add: 'Add income',
  inc_neg: 'An amount below zero can’t be saved.',
  inc_outlier: 'Well above your usual entries. Keep it?',
  src_ehail: 'E-hailing', src_freelance: 'Freelance', src_parttime: 'Part-time (fixed)',
  src_own: '+ Your own source', src_name: 'Source name', entry_saved: 'Entry saved',
  wc_petrol: 'Petrol', wc_service: 'Servicing', wc_platform: 'Platform fees', wc_data: 'Phone data', wc_roadtax: 'Road tax & insurance',
  wc_own: '+ Your own cost', wc_note: 'Every later screen uses this number.',
  cm_living: 'Living costs', cm_debts: 'Debt repayments', cm_savings: 'Savings',
  cm_rent: 'Rent', cm_food: 'Food', cm_util: 'Utilities', cm_motor: 'Motor loan', cm_ptptn: 'PTPTN', cm_family: 'Family support', cm_save: 'Monthly savings',
  cm_total: 'Total commitments',
  pt_avg: 'Average', pt_med: 'Median', pt_high: 'Highest', pt_low: 'Lowest',
  pt_range: 'about ± RM {x} around the average',
  pt_rule: 'A lower-income month here means one below 75% of your average. RuMampu’s own rule, not a financial standard.',
  pt_none: 'No recorded month fell below that line.',
  pt_some: 'Below that line: {m}.',
  cv_q: 'Are there times of year when you usually earn less?',
  cv_yes: 'Yes', cv_no: 'No', cv_notsure: 'Not sure',
  cv_pick: 'Tap the months that are usually slower.',
  cv_unseen: 'You said {slow} is usually slower. Your records cover {a} to {b}, so this test hasn’t seen a slow month yet.',
  cv_seen: 'You said {slow} is usually slower. Your records cover {a} to {b}, and a slow month is in there.',
  cv_narrow: 'Your recorded amounts sit unusually close together. Weaker months may be missing from the record.',
  cv_varied: 'Your recorded amounts differ month to month. The test still only knows {a} to {b}.',
  cv_note: 'More months only help if the right months are in there.',
  th_title: 'The house', th_price: 'Property price (RM)', th_fin: 'Financing amount', th_dep: 'Deposit (RM)',
  th_dep0: 'RM 0 is allowed. 100% financing exists.',
  th_rate: 'Rate (% / year)', th_ten: 'Tenure (years)', th_inst: 'Monthly instalment',
  th_known: 'I already know my monthly payment', th_knownamt: 'Monthly payment (RM)',
  th_next: 'Total monthly cost',
  tc_title: 'Total monthly cost', tc_point: 'The instalment is not the whole cost.',
  tc_inst: 'Instalment', tc_break: 'What’s inside', tc_run: 'Run the test',
  hc_maint: 'Maintenance & sinking fund', hc_insure: 'Home insurance', hc_assess: 'Assessment tax', hc_quit: 'Quit rent', hc_parking: 'Parking', hc_other: 'Other',
  pc_title: 'Before the house',
  pc_msg: 'In {m}, your quietest recorded month, income came in RM {x} below your everyday costs, before any home cost.',
  pc_msg2: 'A home payment on top would leave every month short, at any price. A quick look at income and costs first gives the test firmer ground.',
  pc_btn: 'Go to Money',
  rs_title: 'Result',
  rs_how: 'How this was worked out',
  rs_how_body: 'Each bar is one recorded month: income after work costs, minus commitments. The line is the total monthly home cost, RM {c}. A month runs short when its bar ends below the line.',
  rs_limit_slow: 'This test hasn’t seen {m}, which you said is usually slower. The count below doesn’t include that quieter time of year yet.',
  rs_limit_thin: 'Only {n} months recorded. Not enough for this count to carry weight yet.',
  rs_range: 'Carrying range', rs_compare: 'Compare payments', rs_shock: 'If income drops',
  rg_lead: 'Your recorded months carried payments of RM {a} to RM {b} a month.',
  rg_how: 'What the two ends mean',
  rg_how_body: 'RM {a}: every recorded month covered it. RM {b}: half of them did.',
  rg_price: 'At {r}% over {y} years, that is about RM {p} to RM {q} in price.',
  rg_pin: 'your test',
  rg_ind: 'Indicative only. Not a valuation, not an offer.',
  cp_note: 'Same recorded months, three payments.',
  cp_short: '{s} of {n} short', cp_gap: 'largest gap RM {g}', cp_pay: 'Payment {i} (RM)',
  sh_note: 'A hypothetical about your recorded months, not about what lies ahead.',
  sh_custom: 'Custom', sh_pct: 'Drop (%)',
  sh_head: 'At −{p}%: {s} of {n} recorded months would have run short.',
  pr_upfront: 'Upfront cash', pr_buffer: 'Cash buffer', pr_docs: 'Documents & financing',
  pr_pv: 'Iteration 3 preview', pr_pv_note: 'After buying. Direction only, not shipping yet.',
  uf_have: 'You have', uf_need: 'You need', uf_gap: 'Gap',
  uf_dep: 'Deposit', uf_legal: 'Legal fees', uf_stampT: 'Stamp duty (transfer)', uf_stampL: 'Stamp duty (loan)', uf_val: 'Valuation', uf_disb: 'Disbursements', uf_move: 'Moving', uf_basic: 'Basics (fridge, bed, curtains)',
  uf_dep0: 'Deposit RM 0: upfront cash is fees and setting up, not the deposit.',
  bf_def: 'The smallest amount you’d have needed at the start to get through the short months in your record without going below zero.',
  bf_basis: 'From your own record, {a} to {b}. Not a general rule.',
  bf_zero: 'With this house, your recorded months never went below zero. The figure works out to RM 0.',
  bf_bal: 'Running balance by month',
  dc_bank: 'Bank statements, 6 months', dc_ehail: 'E-hailing earnings summary', dc_statdec: 'Statutory declaration of income', dc_epf: 'EPF statement', dc_commitlist: 'List of existing commitments',
  dc_sjkp: 'SJKP published criteria',
  dc_sj1: 'Malaysian citizen, age 18 to 70', dc_sj2: 'Gross income within SJKP’s published limit', dc_sj3: 'First home',
  dc_src: 'Source: sjkp.com.my, Aug 2026',
  dc_65: '65% check: needs review',
  dc_65_note: 'SJKP measures gross income; RuMampu measures income after work costs. Until that gap is settled, no pass or fail is shown here.',
  dc_plain: 'RuMampu does not apply for you and cannot tell you whether a bank will say yes.',
  pv_banner: 'Iteration 3 preview',
  pv_switch: 'Switch mode', pv_switch_btn: 'I’ve bought the home',
  pv_switch_note: 'Estimates become actuals. The purchase itself happens outside RuMampu.',
  pv_month: 'This month', pv_in: 'Actual income in', pv_out: 'Actual home costs out',
  pv_left: 'Cash left', pv_shortby: 'Short by',
  pv_then: 'Earlier test vs what happened',
  pv_then_a: 'Your earlier test: {s} short months out of {n} recorded.',
  pv_then_b: 'Since buying: {s2} of your first {n2} months have run short.',
  pv_then_why: 'The earlier record had no year-end month in it. Two arrived after buying.',
  see_pattern: 'Income pattern', see_coverage: 'Coverage check',
  money_record: 'Your record',
  rc_months: '{n} months recorded',
  rc_entries: '{e} entries, latest {d}',
  rc_tests: 'Kept tests',
  rc_none: 'No test kept yet. Run one from the Test tab.',
  rc_live: 'Every screen updates as you add. In this preview, the record lives only in this session.',
  rc_keep_line: 'Every new week you record gives the next test more of your real months.',
  rs_keep: 'Keep this test', rs_kept: 'Test kept',
  entry_saved_n: 'Entry saved. The analysis now uses {n} months.',
  inc_past: 'Add a past month',
  inc_past_hint: 'One total for that month is enough.',
  pt_bymonth: 'Month by month',
  pv_keep: 'Keep recording after buying. The same record keeps working.',
  money_expenses: 'Daily expenses',
  ex_sofar: '{m} so far', ex_days: '{d} days recorded',
  ex_add: 'Add expense', ex_scan: 'Scan a receipt', ex_preview: 'Preview',
  ex_bycat: 'By category',
  xc_meals: 'Meals', xc_groc: 'Groceries', xc_transp: 'Tolls & parking', xc_family: 'Family', xc_other: 'Other', xc_own: '+ Your own category',
  ex_saved: 'Saved. {m} so far: RM {x}.',
  ex_rule: 'A month counts as fully recorded from 20 logged days. RuMampu’s own rule.',
  ex_feeds: '{m} used your recorded expenses, RM {x}, in place of the food and family estimate.',
  ex_scan_pick: 'Take or choose a photo of the receipt.',
  ex_scan_sample: 'Use a sample receipt',
  ex_reading: 'Reading the receipt…',
  ex_check: 'Read from your receipt. Check it before saving.',
  ex_merchant: 'Shop', ex_total: 'Total (RM)', ex_retake: 'Retake', ex_fromr: 'from receipt', ex_cat: 'Category',
  ex_monthly: 'Monthly summary',
  ex_full: 'fully recorded', ex_used: 'used in the test',
  ex_partial: '{d} days, rest of month unknown',
  ex_limits: 'Spending limits',
  lm_note: 'The limits are yours to set. RuMampu only counts.',
  lm_total: 'Whole month', lm_limit: 'Limit (RM)',
  lm_left: 'RM {x} left',
  lm_over: 'RM {x} past your limit',
  lm_none: 'no limit set',
  hb_spend: 'Spending · {m}', hb_income: 'Income · {m}'
},
ms: {
  langname: 'Bahasa Melayu', months: ['Jan','Feb','Mac','Apr','Mei','Jun','Jul','Ogo','Sep','Okt','Nov','Dis'],
  tab_home: 'Utama', tab_money: 'Wang', tab_test: 'Uji', tab_prepare: 'Sedia',
  back: 'Kembali', add: 'Tambah', edit: 'Ubah', done: 'Selesai', cancel: 'Batal', keep: 'Kekalkan', remove: 'Buang',
  saved: 'Disimpan', unknown: 'Tidak diketahui', lang_pick: 'Bahasa',
  prov_user: 'data anda', prov_official: 'rasmi', prov_calc: 'dikira', prov_assume: 'andaian',
  provf_user: 'Data Pengguna: angka yang anda masukkan sendiri.',
  provf_official: 'Sumber Rasmi: angka diterbitkan; sumber dan tarikh dinyatakan.',
  provf_calc: 'Kiraan Terbitan: aritmetik ke atas rekod anda sendiri. Tiada tokok tambah.',
  provf_assume: 'Andaian Ujian Tekanan: nilai lalai boleh ubah, bukan fakta tentang anda.',
  ob1: 'RuMampu melihat bagaimana bayaran rumah muat dengan bulan yang lebih perlahan, bukan hanya purata anda.',
  ob2: 'Ia membentangkan angka dengan jelas. Keputusan sentiasa di tangan anda.',
  ob3: 'Mulakan dengan apa yang ada. Pendapatan seminggu pun sudah satu permulaan yang baik.',
  ob_skip: 'Langkau', ob_next: 'Seterusnya', ob_start: 'Mula',
  ob_slogan: 'Biar bulan sebenar anda yang mengira.',
  home_rec: 'Anda ada {n} bulan pendapatan direkod.',
  home_rec_thin: '{n} bulan ialah rekod yang nipis. Setiap catatan baharu membantu ujian melihat lebih.',
  home_test: 'Uji sebuah rumah', home_retest: 'Uji semula rumah itu',
  headline: '{s} daripada {n} bulan direkod anda tidak akan cukup.',
  headline_zero: 'Kesemua {n} bulan direkod anda menutup kos ini.',
  gap_lbl: 'Jurang terbesar',
  covspan: '{a} hingga {b} direkod',
  cov_unchecked: 'Liputan belum disemak',
  cov_missed: 'Rekod anda belum melihat {m}. Anda kata ia biasanya perlahan.',
  money_income: 'Pendapatan', money_workcosts: 'Kos kerja', money_commit: 'Komitmen',
  money_pattern: 'Corak pendapatan', money_coverage: 'Semakan liputan',
  net_lbl: 'Pendapatan selepas kos kerja', per_month: '/ bulan, purata',
  inc_empty: 'Masukkan pendapatan minggu lepas. Itu sudah cukup untuk bermula.',
  inc_amount: 'Jumlah (RM)', inc_date: 'Tarikh', inc_source: 'Sumber', inc_add: 'Tambah pendapatan',
  inc_neg: 'Jumlah bawah sifar tidak dapat disimpan.',
  inc_outlier: 'Jauh lebih tinggi daripada catatan biasa anda. Kekalkan?',
  src_ehail: 'E-hailing', src_freelance: 'Kerja bebas', src_parttime: 'Separuh masa (tetap)',
  src_own: '+ Sumber anda sendiri', src_name: 'Nama sumber', entry_saved: 'Catatan disimpan',
  wc_petrol: 'Petrol', wc_service: 'Servis kenderaan', wc_platform: 'Yuran platform', wc_data: 'Data telefon', wc_roadtax: 'Cukai jalan & insurans',
  wc_own: '+ Kos anda sendiri', wc_note: 'Setiap skrin selepas ini menggunakan angka ini.',
  cm_living: 'Kos sara hidup', cm_debts: 'Bayaran hutang', cm_savings: 'Simpanan',
  cm_rent: 'Sewa', cm_food: 'Makanan', cm_util: 'Utiliti', cm_motor: 'Pinjaman motosikal', cm_ptptn: 'PTPTN', cm_family: 'Sokongan keluarga', cm_save: 'Simpanan bulanan',
  cm_total: 'Jumlah komitmen',
  pt_avg: 'Purata', pt_med: 'Penengah', pt_high: 'Tertinggi', pt_low: 'Terendah',
  pt_range: 'lebih kurang ± RM {x} sekitar purata',
  pt_rule: 'Bulan pendapatan rendah di sini bermaksud bawah 75% purata anda. Peraturan RuMampu sendiri, bukan piawaian kewangan.',
  pt_none: 'Tiada bulan direkod jatuh bawah garis itu.',
  pt_some: 'Bawah garis itu: {m}.',
  cv_q: 'Ada musim anda biasanya kurang pendapatan?',
  cv_yes: 'Ya', cv_no: 'Tidak', cv_notsure: 'Tak pasti',
  cv_pick: 'Tandakan bulan yang biasanya perlahan.',
  cv_unseen: 'Anda kata {slow} biasanya perlahan. Rekod anda meliputi {a} hingga {b}, jadi ujian ini belum melihat bulan perlahan.',
  cv_seen: 'Anda kata {slow} biasanya perlahan. Rekod anda meliputi {a} hingga {b}, dan bulan perlahan ada di dalamnya.',
  cv_narrow: 'Angka direkod anda terlalu rapat antara satu sama lain. Bulan lemah mungkin tiada dalam rekod.',
  cv_varied: 'Angka direkod anda berbeza dari bulan ke bulan. Ujian ini tetap hanya kenal {a} hingga {b}.',
  cv_note: 'Bulan tambahan hanya membantu jika bulan yang betul ada di dalamnya.',
  th_title: 'Rumah itu', th_price: 'Harga hartanah (RM)', th_fin: 'Jumlah pembiayaan', th_dep: 'Bayaran muka (RM)',
  th_dep0: 'RM 0 dibenarkan. Pembiayaan 100% wujud.',
  th_rate: 'Kadar (% / tahun)', th_ten: 'Tempoh (tahun)', th_inst: 'Ansuran bulanan',
  th_known: 'Saya sudah tahu bayaran bulanan saya', th_knownamt: 'Bayaran bulanan (RM)',
  th_next: 'Jumlah kos bulanan',
  tc_title: 'Jumlah kos bulanan', tc_point: 'Ansuran bukan keseluruhan kos.',
  tc_inst: 'Ansuran', tc_break: 'Apa di dalamnya', tc_run: 'Jalankan ujian',
  hc_maint: 'Penyelenggaraan & tabung penjelas', hc_insure: 'Insurans rumah', hc_assess: 'Cukai pintu', hc_quit: 'Cukai tanah', hc_parking: 'Parkir', hc_other: 'Lain-lain',
  pc_title: 'Sebelum rumah',
  pc_msg: 'Pada {m}, bulan paling perlahan dalam rekod anda, pendapatan RM {x} di bawah kos harian anda, sebelum sebarang kos rumah.',
  pc_msg2: 'Bayaran rumah di atasnya akan menjadikan semua bulan kurang, pada apa jua harga. Semak dahulu pendapatan dan kos supaya ujian ini berpijak lebih kukuh.',
  pc_btn: 'Pergi ke Wang',
  rs_title: 'Keputusan',
  rs_how: 'Bagaimana ia dikira',
  rs_how_body: 'Setiap bar ialah satu bulan direkod: pendapatan selepas kos kerja, tolak komitmen. Garisan ialah jumlah kos rumah bulanan, RM {c}. Bulan dikira kurang bila barnya berakhir di bawah garisan.',
  rs_limit_slow: 'Ujian ini belum melihat {m}, yang anda kata biasanya perlahan. Kiraan di bawah belum merangkumi musim yang lebih perlahan itu.',
  rs_limit_thin: 'Baru {n} bulan direkod. Belum cukup untuk kiraan ini membawa makna.',
  rs_range: 'Julat terbawa', rs_compare: 'Banding bayaran', rs_shock: 'Jika pendapatan turun',
  rg_lead: 'Bulan-bulan direkod anda membawa bayaran RM {a} hingga RM {b} sebulan.',
  rg_how: 'Maksud dua hujung itu',
  rg_how_body: 'RM {a}: semua bulan direkod menutupnya. RM {b}: separuh daripadanya.',
  rg_price: 'Pada {r}% selama {y} tahun, itu sekitar RM {p} hingga RM {q} harga rumah.',
  rg_pin: 'ujian anda',
  rg_ind: 'Petunjuk sahaja. Bukan penilaian, bukan tawaran.',
  cp_note: 'Bulan direkod yang sama, tiga bayaran.',
  cp_short: '{s} daripada {n} kurang', cp_gap: 'jurang terbesar RM {g}', cp_pay: 'Bayaran {i} (RM)',
  sh_note: 'Andaian ke atas bulan direkod anda, bukan tentang masa hadapan.',
  sh_custom: 'Sendiri', sh_pct: 'Turun (%)',
  sh_head: 'Pada −{p}%: {s} daripada {n} bulan direkod tidak akan cukup.',
  pr_upfront: 'Tunai permulaan', pr_buffer: 'Penampan tunai', pr_docs: 'Dokumen & pembiayaan',
  pr_pv: 'Pratonton Iterasi 3', pr_pv_note: 'Selepas membeli. Hala tuju sahaja, belum dilancarkan.',
  uf_have: 'Anda ada', uf_need: 'Anda perlu', uf_gap: 'Jurang',
  uf_dep: 'Bayaran muka', uf_legal: 'Yuran guaman', uf_stampT: 'Duti setem (pindah milik)', uf_stampL: 'Duti setem (pinjaman)', uf_val: 'Penilaian hartanah', uf_disb: 'Perbelanjaan pelbagai guaman', uf_move: 'Pindah rumah', uf_basic: 'Asas (peti sejuk, katil, langsir)',
  uf_dep0: 'Deposit RM 0: tunai permulaan ialah yuran dan persiapan, bukan deposit.',
  bf_def: 'Jumlah terkecil yang anda perlukan pada permulaan untuk melepasi bulan-bulan kurang dalam rekod anda tanpa jatuh bawah sifar.',
  bf_basis: 'Daripada rekod anda sendiri, {a} hingga {b}. Bukan peraturan umum.',
  bf_zero: 'Dengan rumah ini, bulan direkod anda tidak pernah jatuh bawah sifar. Kiraannya RM 0.',
  bf_bal: 'Baki berjalan ikut bulan',
  dc_bank: 'Penyata bank, 6 bulan', dc_ehail: 'Ringkasan pendapatan e-hailing', dc_statdec: 'Surat akuan berkanun pendapatan', dc_epf: 'Penyata KWSP', dc_commitlist: 'Senarai komitmen sedia ada',
  dc_sjkp: 'Kriteria terbitan SJKP',
  dc_sj1: 'Warganegara Malaysia, umur 18 hingga 70', dc_sj2: 'Pendapatan kasar dalam had terbitan SJKP', dc_sj3: 'Rumah pertama',
  dc_src: 'Sumber: sjkp.com.my, Ogo 2026',
  dc_65: 'Semakan 65%: perlu semakan semula',
  dc_65_note: 'SJKP mengukur pendapatan kasar; RuMampu mengukur pendapatan selepas kos kerja. Selagi beza itu belum selesai, tiada keputusan ditunjukkan di sini.',
  dc_plain: 'RuMampu tidak memohon bagi pihak anda dan tidak dapat memberitahu sama ada bank akan kata ya.',
  pv_banner: 'Pratonton Iterasi 3',
  pv_switch: 'Tukar mod', pv_switch_btn: 'Saya sudah beli rumah itu',
  pv_switch_note: 'Anggaran bertukar kepada angka sebenar. Pembelian berlaku di luar RuMampu.',
  pv_month: 'Bulan ini', pv_in: 'Pendapatan sebenar masuk', pv_out: 'Kos rumah sebenar keluar',
  pv_left: 'Baki tunai', pv_shortby: 'Kurang sebanyak',
  pv_then: 'Ujian awal vs yang berlaku',
  pv_then_a: 'Ujian awal anda: {s} bulan kurang daripada {n} direkod.',
  pv_then_b: 'Sejak membeli: {s2} daripada {n2} bulan pertama anda kurang.',
  pv_then_why: 'Rekod awal tiada bulan hujung tahun di dalamnya. Dua bulan begitu tiba selepas membeli.',
  see_pattern: 'Corak pendapatan', see_coverage: 'Semakan liputan',
  money_record: 'Rekod anda',
  rc_months: '{n} bulan direkod',
  rc_entries: '{e} catatan, terkini {d}',
  rc_tests: 'Ujian disimpan',
  rc_none: 'Belum ada ujian disimpan. Jalankan satu dari tab Uji.',
  rc_live: 'Setiap skrin dikemas kini apabila anda menambah. Dalam pratonton ini, rekod hanya wujud dalam sesi ini.',
  rc_keep_line: 'Setiap minggu baharu yang anda rekodkan memberi ujian seterusnya lebih banyak bulan sebenar anda.',
  rs_keep: 'Simpan ujian ini', rs_kept: 'Ujian disimpan',
  entry_saved_n: 'Catatan disimpan. Analisis kini menggunakan {n} bulan.',
  inc_past: 'Tambah bulan lalu',
  inc_past_hint: 'Satu jumlah untuk bulan itu sudah cukup.',
  pt_bymonth: 'Bulan demi bulan',
  pv_keep: 'Terus merekod selepas membeli. Rekod yang sama terus berfungsi.',
  money_expenses: 'Perbelanjaan harian',
  ex_sofar: '{m} setakat ini', ex_days: '{d} hari direkod',
  ex_add: 'Tambah perbelanjaan', ex_scan: 'Imbas resit', ex_preview: 'Pratonton',
  ex_bycat: 'Ikut kategori',
  xc_meals: 'Makan', xc_groc: 'Barang dapur', xc_transp: 'Tol & parkir', xc_family: 'Keluarga', xc_other: 'Lain-lain', xc_own: '+ Kategori anda',
  ex_saved: 'Disimpan. {m} setakat ini: RM {x}.',
  ex_rule: 'Sebulan dikira lengkap apabila 20 hari direkodkan. Peraturan RuMampu sendiri.',
  ex_feeds: '{m} menggunakan perbelanjaan direkod anda, RM {x}, menggantikan anggaran makanan dan keluarga.',
  ex_scan_pick: 'Ambil atau pilih gambar resit.',
  ex_scan_sample: 'Guna resit contoh',
  ex_reading: 'Membaca resit…',
  ex_check: 'Dibaca daripada resit anda. Semak sebelum menyimpan.',
  ex_merchant: 'Kedai', ex_total: 'Jumlah (RM)', ex_retake: 'Ambil semula', ex_fromr: 'daripada resit', ex_cat: 'Kategori',
  ex_monthly: 'Ringkasan bulanan',
  ex_full: 'lengkap direkod', ex_used: 'digunakan dalam ujian',
  ex_partial: '{d} hari, hari lain tidak diketahui',
  ex_limits: 'Had perbelanjaan',
  lm_note: 'Had ini anda yang tetapkan. RuMampu hanya mengira.',
  lm_total: 'Keseluruhan bulan', lm_limit: 'Had (RM)',
  lm_left: 'RM {x} lagi',
  lm_over: 'RM {x} melebihi had anda',
  lm_none: 'tiada had ditetapkan',
  hb_spend: 'Perbelanjaan · {m}', hb_income: 'Pendapatan · {m}'
},
zh: {
  langname: '中文', months: ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'],
  tab_home: '主页', tab_money: '收支', tab_test: '测试', tab_prepare: '准备',
  back: '返回', add: '添加', edit: '修改', done: '完成', cancel: '取消', keep: '保留', remove: '删除',
  saved: '已保存', unknown: '未知', lang_pick: '语言',
  prov_user: '你的记录', prov_official: '官方', prov_calc: '计算所得', prov_assume: '假设',
  provf_user: '用户数据：你自己输入的数字。',
  provf_official: '官方来源：已公布的数字，注明来源和日期。',
  provf_calc: '推导计算：只对你自己的记录做算术，别无其他。',
  provf_assume: '压力测试假设：可修改的默认值，不是关于你的事实。',
  ob1: 'RuMampu 帮你看看，房屋月供在收入较慢的月份是否也过得去，而不只看平均。',
  ob2: '它把数字清楚地摆出来，决定始终在你手上。',
  ob3: '有什么就从什么开始，一周的收入已是很好的起点。',
  ob_skip: '跳过', ob_next: '下一步', ob_start: '开始',
  ob_slogan: '让真实的月份，替你算一算。',
  home_rec: '你已记录 {n} 个月的收入。',
  home_rec_thin: '{n} 个月的记录还很薄。每多记一笔，测试就多看到一点。',
  home_test: '测试一套房', home_retest: '重新测试这套房',
  headline: '在已记录的 {n} 个月中，{s} 个月的钱不够。',
  headline_zero: '已记录的 {n} 个月都够付这笔成本。',
  gap_lbl: '最大缺口',
  covspan: '已记录 {a} 至 {b}',
  cov_unchecked: '覆盖情况尚未检查',
  cov_missed: '你的记录还没见过{m}。你说那时通常较慢。',
  money_income: '收入', money_workcosts: '工作开销', money_commit: '固定开支',
  money_pattern: '收入形态', money_coverage: '覆盖检查',
  net_lbl: '扣除工作开销后的收入', per_month: '/ 月，平均',
  inc_empty: '先记上周的收入，就足够开始了。',
  inc_amount: '金额 (RM)', inc_date: '日期', inc_source: '来源', inc_add: '添加收入',
  inc_neg: '低于零的金额无法保存。',
  inc_outlier: '比你平常的记录高很多。保留吗？',
  src_ehail: '电召车', src_freelance: '自由接单', src_parttime: '兼职（固定）',
  src_own: '＋自定来源', src_name: '来源名称', entry_saved: '已记录',
  wc_petrol: '汽油', wc_service: '车辆保养', wc_platform: '平台抽成', wc_data: '手机流量', wc_roadtax: '路税与车险',
  wc_own: '＋自定开销', wc_note: '之后每个页面都用这个数字。',
  cm_living: '生活开销', cm_debts: '还债', cm_savings: '储蓄',
  cm_rent: '房租', cm_food: '伙食', cm_util: '水电', cm_motor: '摩托车贷款', cm_ptptn: 'PTPTN', cm_family: '家用', cm_save: '每月储蓄',
  cm_total: '固定开支合计',
  pt_avg: '平均', pt_med: '中位', pt_high: '最高', pt_low: '最低',
  pt_range: '大约在平均值 ± RM {x} 之间',
  pt_rule: '这里的低收入月，指低于你平均值 75% 的月份。这是 RuMampu 自己的规则，不是金融标准。',
  pt_none: '没有记录月低于这条线。',
  pt_some: '低于这条线的：{m}。',
  cv_q: '一年中，有没有你通常赚得较少的时候？',
  cv_yes: '有', cv_no: '没有', cv_notsure: '不确定',
  cv_pick: '点选通常较慢的月份。',
  cv_unseen: '你说{slow}通常较慢。你的记录覆盖 {a} 到 {b}，这次测试还没见过慢月份。',
  cv_seen: '你说{slow}通常较慢。你的记录覆盖 {a} 到 {b}，慢月份已在其中。',
  cv_narrow: '你记录的数字彼此过于接近。较弱的月份可能没被记到。',
  cv_varied: '你记录的数字每月不同。但测试仍只认识 {a} 到 {b}。',
  cv_note: '多记几个月有用的前提，是记到对的月份。',
  th_title: '这套房', th_price: '房价 (RM)', th_fin: '贷款额', th_dep: '头期 (RM)',
  th_dep0: 'RM 0 也可以，有 100% 贷款。',
  th_rate: '年利率 (%)', th_ten: '年期（年）', th_inst: '每月供款',
  th_known: '我已知道每月供款', th_knownamt: '每月供款 (RM)',
  th_next: '每月总成本',
  tc_title: '每月总成本', tc_point: '供款不等于全部成本。',
  tc_inst: '供款', tc_break: '包含哪些', tc_run: '开始测试',
  hc_maint: '管理费与储备金', hc_insure: '房屋保险', hc_assess: '门牌税', hc_quit: '地税', hc_parking: '车位', hc_other: '其他',
  pc_title: '还没算房子之前',
  pc_msg: '在收入最清淡的 {m}，收入比日常开销少了 RM {x}，还没算任何房屋成本。',
  pc_msg2: '再加上房屋支出，无论房价多少，每个月都会不够。先看看收入和开销，测试随时可以再来。',
  pc_btn: '去收支',
  rs_title: '结果',
  rs_how: '这是怎么算的',
  rs_how_body: '每根柱是一个记录月：扣除工作开销的收入，再减固定开支。横线是每月房屋总成本 RM {c}。柱子够不到线，该月就算短缺。',
  rs_limit_slow: '这次测试还没见过你说通常较慢的{m}。下面的计数还没包含那段较慢的日子。',
  rs_limit_thin: '只记录了 {n} 个月，还不足以让这个计数有分量。',
  rs_range: '承担区间', rs_compare: '比较付款', rs_shock: '如果收入下降',
  rg_lead: '你记录的月份承担过每月 RM {a} 至 RM {b} 的付款。',
  rg_how: '两端是什么意思',
  rg_how_body: 'RM {a}：每个记录月都够。RM {b}：一半的月份够。',
  rg_price: '按 {r}%、{y} 年计，约合房价 RM {p} 至 RM {q}。',
  rg_pin: '你的测试',
  rg_ind: '仅供参考。不是估价，也不是要约。',
  cp_note: '同样的记录月份，三种付款。',
  cp_short: '{n} 个月中 {s} 个短缺', cp_gap: '最大缺口 RM {g}', cp_pay: '付款 {i} (RM)',
  sh_note: '只是对已记录月份的假设，不是对将来的判断。',
  sh_custom: '自定', sh_pct: '下降 (%)',
  sh_head: '按 −{p}% 计：{n} 个记录月中 {s} 个不够。',
  pr_upfront: '购房现金', pr_buffer: '现金缓冲', pr_docs: '文件与融资',
  pr_pv: '第 3 迭代预览', pr_pv_note: '买房之后。仅展示方向，尚未上线。',
  uf_have: '你有', uf_need: '需要', uf_gap: '缺口',
  uf_dep: '头期', uf_legal: '律师费', uf_stampT: '印花税（过户）', uf_stampL: '印花税（贷款）', uf_val: '估价费', uf_disb: '杂项支出', uf_move: '搬家', uf_basic: '基本家当（冰箱、床、窗帘）',
  uf_dep0: '头期 RM 0：购房现金是各项费用和安家，不是头期。',
  bf_def: '让你撑过记录中短缺的月份、且不跌破零，开头所需的最小金额。',
  bf_basis: '来自你自己 {a} 到 {b} 的记录，不是通用规则。',
  bf_zero: '按这套房算，你记录的月份从未跌破零。得数是 RM 0。',
  bf_bal: '逐月滚动余额',
  dc_bank: '银行月结单，6 个月', dc_ehail: '电召车收入摘要', dc_statdec: '收入法定声明', dc_epf: 'EPF 公积金结单', dc_commitlist: '现有开支清单',
  dc_sjkp: 'SJKP 公布的条件',
  dc_sj1: '马来西亚公民，18 至 70 岁', dc_sj2: '总收入在 SJKP 公布的上限内', dc_sj3: '首套房',
  dc_src: '来源：sjkp.com.my，2026 年 8 月',
  dc_65: '65% 核对：待复核',
  dc_65_note: 'SJKP 按总收入计，RuMampu 按扣除工作开销后的收入计。在厘清之前，这里不显示通过或不通过。',
  dc_plain: 'RuMampu 不会替你申请，也无法告诉你银行是否点头。',
  pv_banner: '第 3 迭代预览',
  pv_switch: '切换模式', pv_switch_btn: '我已买下这套房',
  pv_switch_note: '估算换成实际数字。购买本身在 RuMampu 之外完成。',
  pv_month: '本月', pv_in: '实际收入', pv_out: '实际房屋支出',
  pv_left: '剩余现金', pv_shortby: '短缺',
  pv_then: '先前测试 vs 实际情况',
  pv_then_a: '先前测试：{n} 个记录月中 {s} 个短缺。',
  pv_then_b: '买房后：头 {n2} 个月中 {s2} 个短缺。',
  pv_then_why: '先前的记录里没有年末月份，买房后遇上了两个。',
  see_pattern: '收入形态', see_coverage: '覆盖检查',
  money_record: '记录档案',
  rc_months: '已记录 {n} 个月',
  rc_entries: '{e} 笔，最近 {d}',
  rc_tests: '留存的测试',
  rc_none: '还没有留存的测试。到测试页跑一次。',
  rc_live: '每加一笔，所有页面即时更新。在这个原型里，记录只保存在本次会话中。',
  rc_keep_line: '每多记一周，下一次测试就多一点你真实的月份。',
  rs_keep: '留存这次测试', rs_kept: '已留存',
  entry_saved_n: '已记录。分析现在用上 {n} 个月。',
  inc_past: '补记过去的月份',
  inc_past_hint: '那个月一个总数就够。',
  pt_bymonth: '逐月',
  pv_keep: '买房后继续记录，同一份记录继续发挥作用。',
  money_expenses: '每日记账',
  ex_sofar: '{m} 至今', ex_days: '已记录 {d} 天',
  ex_add: '记一笔', ex_scan: '扫描收据', ex_preview: '预览',
  ex_bycat: '按类别',
  xc_meals: '吃饭', xc_groc: '日用采买', xc_transp: '过路费与停车', xc_family: '家用', xc_other: '其他', xc_own: '＋自定类别',
  ex_saved: '已记下。{m} 至今：RM {x}。',
  ex_rule: '记满 20 天，当月才算记录完整。这是 RuMampu 自己的规则。',
  ex_feeds: '{m} 用了你记录的开销 RM {x}，代替伙食和家用的估算。',
  ex_scan_pick: '拍摄或选择收据照片。',
  ex_scan_sample: '用示例收据',
  ex_reading: '正在读取收据……',
  ex_check: '从收据读到的内容，保存前请核对。',
  ex_merchant: '商家', ex_total: '总额 (RM)', ex_retake: '重拍', ex_fromr: '来自收据', ex_cat: '类别',
  ex_monthly: '按月汇总',
  ex_full: '记录完整', ex_used: '已用于测试',
  ex_partial: '记录 {d} 天，其余未知',
  ex_limits: '消费上限',
  lm_note: '上限由你自己设定，RuMampu 只负责计数。',
  lm_total: '整月', lm_limit: '上限 (RM)',
  lm_left: '还剩 RM {x}',
  lm_over: '超出上限 RM {x}',
  lm_none: '未设上限',
  hb_spend: '开销 · {m}', hb_income: '收入 · {m}'
}
};
