# Generated by Django 6.1 on 2026-09-13 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0003_savedhousingtest"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("osm_relation_id", models.BigIntegerField(blank=True, null=True)),
                ("centroid_lat", models.FloatField(blank=True, null=True)),
                ("centroid_lng", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "district",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PriceAgg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quarter", models.TextField()),
                ("property_type", models.TextField()),
                ("sales_count", models.IntegerField()),
                (
                    "total_value_rm",
                    models.DecimalField(decimal_places=2, max_digits=16, null=True),
                ),
                (
                    "mean_price_rm",
                    models.DecimalField(decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "median_price_rm",
                    models.DecimalField(decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "p25_price_rm",
                    models.DecimalField(decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "p75_price_rm",
                    models.DecimalField(decimal_places=2, max_digits=14, null=True),
                ),
                ("under_300k", models.IntegerField(null=True)),
                ("under_500k", models.IntegerField(null=True)),
                ("preliminary", models.BooleanField(default=False)),
                ("source", models.TextField(default="NAPIC Open Transaction Data")),
                ("loaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "price_agg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mukim", models.TextField(blank=True)),
                ("scheme_area", models.TextField(blank=True)),
                ("txn_date", models.DateField()),
                ("quarter", models.TextField()),
                ("property_type", models.TextField()),
                ("tenure", models.TextField(blank=True)),
                ("land_area", models.FloatField(null=True)),
                ("floor_area", models.FloatField(null=True)),
                ("price_rm", models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                "db_table": "property_transaction",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
            options={
                "db_table": "state",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StateIncome",
            fields=[
                (
                    "state",
                    models.OneToOneField(
                        db_column="state_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="housing.state",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "income_mean",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "income_median",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "expenditure_mean",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "gini",
                    models.DecimalField(decimal_places=3, max_digits=5, null=True),
                ),
                (
                    "poverty",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("source", models.TextField(default="DOSM HIES")),
            ],
            options={
                "db_table": "state_income",
                "managed": False,
            },
        ),
    ]
