# Generated by Django 6.1 on 2026-10-05 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0005_savedhousingtest_snapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=40, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("loaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PriceIndexPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.CharField(max_length=3)),
                ("property_type", models.CharField(max_length=20)),
                ("quarter", models.CharField(max_length=6)),
                ("index_value", models.FloatField()),
                ("sales", models.PositiveIntegerField()),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_points",
                        to="housing.pricemodelversion",
                    ),
                ),
            ],
            options={
                "ordering": ["quarter"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version", "state_code", "property_type", "quarter"),
                        name="unique_price_index_point",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceRangeCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.CharField(max_length=3)),
                ("state", models.CharField(max_length=40)),
                ("district", models.CharField(max_length=60)),
                ("property_type", models.CharField(max_length=20)),
                ("tenure", models.CharField(max_length=1)),
                ("storeys", models.PositiveSmallIntegerField(default=0)),
                ("size_band", models.CharField(max_length=8)),
                ("n_sales_2y", models.PositiveIntegerField()),
                ("size_m2", models.PositiveIntegerField()),
                ("p10", models.PositiveIntegerField()),
                ("p50", models.PositiveIntegerField()),
                ("p90", models.PositiveIntegerField()),
                ("y1_p10", models.PositiveIntegerField()),
                ("y1_p50", models.PositiveIntegerField()),
                ("y1_p90", models.PositiveIntegerField()),
                ("y2_p10", models.PositiveIntegerField()),
                ("y2_p50", models.PositiveIntegerField()),
                ("y2_p90", models.PositiveIntegerField()),
                ("y3_p10", models.PositiveIntegerField()),
                ("y3_p50", models.PositiveIntegerField()),
                ("y3_p90", models.PositiveIntegerField()),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="housing.pricemodelversion",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["version", "state_code", "property_type"],
                        name="housing_pri_version_3463e1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "version",
                            "district",
                            "property_type",
                            "tenure",
                            "size_band",
                        ),
                        name="unique_price_cell",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.CharField(max_length=3)),
                ("property_type", models.CharField(max_length=20)),
                ("years", models.PositiveSmallIntegerField()),
                ("growth_low", models.FloatField()),
                ("growth_mid", models.FloatField()),
                ("growth_high", models.FloatField()),
                ("prob_price_fall", models.FloatField()),
                ("annual_trend", models.FloatField()),
                ("annual_trend_p10", models.FloatField()),
                ("annual_trend_p90", models.FloatField()),
                ("sales_last4q", models.PositiveIntegerField()),
                ("data_quality", models.CharField(max_length=5)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="housing.pricemodelversion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version", "state_code", "property_type", "years"),
                        name="unique_price_scenario",
                    )
                ],
            },
        ),
    ]
