# Generated by Django 6.1 on 2026-10-10 07:58

from django.db import migrations, models


def keep_only_latest_active(apps, schema_editor):
    PriceModelVersion = apps.get_model('housing', 'PriceModelVersion')
    active = PriceModelVersion.objects.filter(is_active=True).order_by('-loaded_at', '-pk')
    keep = active.values_list('pk', flat=True).first()
    if keep is not None:
        active.exclude(pk=keep).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_price_model_tables'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='priceindexpoint',
            constraint=models.CheckConstraint(condition=models.Q(('index_value__gt', 0)), name='price_index_value_positive'),
        ),
        migrations.RunPython(keep_only_latest_active, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='pricemodelversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_price_model'),
        ),
        migrations.AddConstraint(
            model_name='pricerangecell',
            constraint=models.CheckConstraint(condition=models.Q(('p10__gt', 0), ('p10__lte', models.F('p50')), ('p50__lte', models.F('p90'))), name='price_cell_today_ordered_positive'),
        ),
        migrations.AddConstraint(
            model_name='pricerangecell',
            constraint=models.CheckConstraint(condition=models.Q(('y1_p10__gt', 0), ('y1_p10__lte', models.F('y1_p50')), ('y1_p50__lte', models.F('y1_p90'))), name='price_cell_y1_ordered_positive'),
        ),
        migrations.AddConstraint(
            model_name='pricerangecell',
            constraint=models.CheckConstraint(condition=models.Q(('y2_p10__gt', 0), ('y2_p10__lte', models.F('y2_p50')), ('y2_p50__lte', models.F('y2_p90'))), name='price_cell_y2_ordered_positive'),
        ),
        migrations.AddConstraint(
            model_name='pricerangecell',
            constraint=models.CheckConstraint(condition=models.Q(('y3_p10__gt', 0), ('y3_p10__lte', models.F('y3_p50')), ('y3_p50__lte', models.F('y3_p90'))), name='price_cell_y3_ordered_positive'),
        ),
        migrations.AddConstraint(
            model_name='pricescenario',
            constraint=models.CheckConstraint(condition=models.Q(('growth_low__lte', models.F('growth_mid')), ('growth_mid__lte', models.F('growth_high'))), name='price_scenario_growth_ordered'),
        ),
        migrations.AddConstraint(
            model_name='pricescenario',
            constraint=models.CheckConstraint(condition=models.Q(('annual_trend__lte', models.F('annual_trend_p90')), ('annual_trend_p10__lte', models.F('annual_trend'))), name='price_scenario_trend_ordered'),
        ),
        migrations.AddConstraint(
            model_name='pricescenario',
            constraint=models.CheckConstraint(condition=models.Q(('prob_price_fall__gte', 0), ('prob_price_fall__lte', 1)), name='price_scenario_probability_valid'),
        ),
    ]
