# Generated by Django 6.1 on 2026-08-24 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField()),
                ('record_basis', models.CharField(choices=[('entry', 'Individual entries'), ('monthly_total', 'Monthly total')], default='entry', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_periods', to='finance.guestprofile')),
            ],
            options={
                'ordering': ['period_month'],
            },
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('is_custom', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to='finance.guestprofile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IncomeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField()),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_method', models.CharField(choices=[('manual', 'Manual entry'), ('historical_total', 'Historical monthly total')], default='manual', max_length=24)),
                ('user_confirmed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to='finance.financialperiod')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to='finance.guestprofile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_entries', to='finance.incomesource')),
            ],
            options={
                'ordering': ['income_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='financialperiod',
            constraint=models.UniqueConstraint(fields=('profile', 'period_month'), name='unique_profile_financial_period'),
        ),
        migrations.AddConstraint(
            model_name='incomesource',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('profile', 'slug'), name='unique_profile_income_source_slug'),
        ),
    ]
