# Generated by Django 6.1 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomeentry",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name="income_entries",
                to="finance.incomesource",
            ),
        ),
        migrations.AddConstraint(
            model_name="incomeentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("entry_method", "historical_total")),
                fields=("profile", "period"),
                name="unique_historical_total_per_period",
            ),
        ),
    ]
