# Generated by Django 6.1 on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_historical_month_integrity"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkCostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=40)),
                ("name", models.CharField(max_length=120)),
                (
                    "monthly_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_custom", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_cost_items",
                        to="finance.guestprofile",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.AddConstraint(
            model_name="workcostitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug", ""), _negated=True),
                fields=("profile", "slug"),
                name="unique_profile_work_cost_slug",
            ),
        ),
    ]
