# Generated by Django 6.1 on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_work_cost_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commitment_type",
                    models.CharField(
                        choices=[
                            ("living", "Living cost"),
                            ("debt", "Debt payment"),
                            ("savings", "Savings"),
                        ],
                        max_length=12,
                    ),
                ),
                ("slug", models.SlugField(max_length=40)),
                ("name", models.CharField(max_length=120)),
                (
                    "monthly_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_daily_variable", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitment_items",
                        to="finance.guestprofile",
                    ),
                ),
            ],
            options={"ordering": ["commitment_type", "id"]},
        ),
        migrations.AddConstraint(
            model_name="commitmentitem",
            constraint=models.UniqueConstraint(
                fields=("profile", "slug"),
                name="unique_profile_commitment_slug",
            ),
        ),
    ]
