# Generated by Django 6.1 on 2026-08-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expense_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='merchant',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='user_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='entry_method',
            field=models.CharField(choices=[('manual', 'Manual entry'), ('receipt', 'Receipt confirmed by user')], default='manual', max_length=24),
        ),
    ]
