# Generated by Django 6.1 on 2026-08-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_expense_receipt_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeentry',
            name='entry_method',
            field=models.CharField(choices=[('manual', 'Manual entry'), ('historical_total', 'Historical monthly total'), ('import', 'Confirmed historical import')], default='manual', max_length=24),
        ),
        migrations.CreateModel(
            name='IncomeImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('preview', 'Awaiting confirmation'), ('confirmed', 'Confirmed')], default='preview', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_import_batches', to='finance.guestprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IncomeImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_amount', models.CharField(blank=True, max_length=64)),
                ('raw_date', models.CharField(blank=True, max_length=32)),
                ('raw_source', models.CharField(blank=True, max_length=160)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('income_date', models.DateField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('error_code', models.CharField(blank=True, max_length=160)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='finance.incomeimportbatch')),
                ('imported_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='finance.incomeentry')),
            ],
            options={
                'ordering': ['row_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_income_import_batch_row')],
            },
        ),
    ]
