# Generated by Django 6.1 on 2026-08-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_income_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeentry',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='income_entries', to='finance.incomesource'),
        ),
    ]
