# Generated by Django 6.1 on 2026-08-25

import django.db.models.deletion
import finance.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_alter_incomeentry_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("not_sure", "Not sure"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "slower_months",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[finance.validators.validate_slower_months],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_coverage",
                        to="finance.guestprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="incomecoverage",
            constraint=models.CheckConstraint(
                condition=models.Q(("answer__in", ("yes", "no", "not_sure"))),
                name="valid_income_coverage_answer",
            ),
        ),
    ]
