# Generated by Django 6.1 on 2026-09-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_income_coverage"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkCostEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="work_cost_entries",
                        to="finance.workcostitem",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_cost_entries",
                        to="finance.guestprofile",
                    ),
                ),
            ],
            options={"ordering": ["-cost_date", "-id"]},
        ),
        migrations.AddConstraint(
            model_name="workcostentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="work_cost_entry_amount_positive",
            ),
        ),
    ]
