# Generated by Django 6.1 on 2026-09-07 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_work_cost_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAppState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upfront_costs', models.JSONField(blank=True, default=list)),
                ('docs_checked', models.JSONField(blank=True, default=list)),
                ('bought_home', models.BooleanField(default=False)),
                ('expense_limits', models.JSONField(blank=True, default=dict)),
                ('compare_payments', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rumampu_app_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
