# Generated by Django 6.1 on 2026-09-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_userappstate_last_record_exported_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userappstate",
            name="buffer_state",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userappstate",
            name="kept_tests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userappstate",
            name="plan_horizon",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userappstate",
            name="pot_moved_months",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userappstate",
            name="saving_plan",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userappstate",
            name="village_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
