# Generated by Django 6.1 on 2026-09-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_expense_monthly_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappstate',
            name='cash_on_hand_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
