# Generated by Django 6.1 on 2026-10-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_userappstate_cash_on_hand_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappstate',
            name='pot_moved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
