# Generated by Django 6.1 on 2026-10-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_userappstate_learning_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcostentry',
            name='merchant',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
