# Generated by Django 6.1 on 2026-10-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_userappstate_experience_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(max_length=80)),
                ('operation', models.CharField(max_length=80)),
                ('request_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(null=True)),
                ('response_data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='finance_ide_created_69e24f_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner_key', 'operation', 'request_key'), name='unique_idempotent_create_request')],
            },
        ),
    ]
